src/objects/AcceleratorSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to be configured by the Accelerator implementator.</description>
    <fields>
        <fullName>ClusterFieldForPublicGroups__c</fullName>
        <defaultValue>&quot;ExternalId__c&quot;</defaultValue>
        <description>When a cluster is created, a public group is created. This field determines which cluster field will be used as the name of the public group that is created for the cluster.</description>
        <inlineHelpText>When a cluster is created, a public group is created. This field determines which cluster field will be used as the name of the public group that is created for the cluster.</inlineHelpText>
        <label>Cluster Field for Public Groups</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaxSizeDesktop__c</fullName>
        <defaultValue>1280</defaultValue>
        <description>Defines the maximum size (logical resolution) that an image can have for desktop when uploading a media element.</description>
        <inlineHelpText>Defines the maximum size (logical resolution) that an image can have for desktop when uploading a media element.</inlineHelpText>
        <label>Max. Size Desktop</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MaxSizeMobile__c</fullName>
        <defaultValue>480</defaultValue>
        <label>Max. Size Mobile</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MaxSizeTablet__c</fullName>
        <defaultValue>768</defaultValue>
        <description>Defines the maximum size (logical resolution) that an image can have for tablet when uploading a media element.</description>
        <inlineHelpText>Defines the maximum size (logical resolution) that an image can have for tablet when uploading a media element.</inlineHelpText>
        <label>Max. Size Tablet</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalesforceDomain__c</fullName>
        <label>Salesforce Domain</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Accelerator Settings</label>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>DefaultLanguage__c</fullName>
        <label>Default Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AvailableLanguages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OtherLanguages__c</fullName>
        <description>Languages that Content Admins will be able to translate and community users can select in the community. For Cluster Groups, you need to select all languages defined below the hierarchy.</description>
        <inlineHelpText>Languages that Content Admins will be able to translate and community users can select in the community. For Cluster Groups, you need to select all languages defined below the hierarchy.</inlineHelpText>
        <label>Other Languages</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AvailableLanguages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ParentCluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Cluster</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>- Parent Cluster record can only be of Group or Root type.
- Cluster Root cannot have a Parent Cluster.</errorMessage>
            <filterItems>
                <field>Cluster__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Cluster Group, Cluster Root</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Cluster Root</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Related Clusters</relationshipLabel>
        <relationshipName>RelatedClusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterGroup</fullName>
        <active>true</active>
        <description>Represents a grouping cluster of other grouping clusters or cluster leafs. (Ex.: EMEA, Africa, Latam).</description>
        <label>Cluster Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ClusterUser__c.object
<CustomObject>
    <description>Determines which users have access to the cluster, the access type (Read Only or Read/Write), it&apos;s child clusters and the configuration below the cluster (ex.: Content, Components, Tags, etc.).</description>
    <fields>
        <fullName>AccessLevel__c</fullName>
        <label>Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read Only Down</fullName>
                </value>
                <value>
                    <fullName>Read/Write</fullName>
                </value>
                <value>
                    <fullName>Read All ORG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipName>ClusterGovernance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ClusterUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cluster User</label>
    <nameField>
        <displayFormat>CU-{00000}</displayFormat>
        <label>Cluster User #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner component. Each banner component has a given aspect ratio and orientation for its presentation. It also has a given behavior for presenting its content such as carousel or appear-disappear effect.</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner content. This content will scroll or appear-fade inside a Banner. The data this type of content allows are Media elements</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContentAssignment__c.object
<CustomObject>
    <description>Manages the direct assignment of Content to Components</description>
    <fields>
        <fullName>Component__c</fullName>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipName>ComponentContentAssignment</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipName>ComponentContentAssignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content Assignment</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Content Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MediaElement__c.object
<CustomObject>
    <description>Represents the repository of media elements that can be assigned to multiple contents.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FileURLDesktop__c</fullName>
        <description>Stores the URL of the desktop file related to the media element.</description>
        <inlineHelpText>Stores the URL of the desktop file related to the media element.</inlineHelpText>
        <label>File URL Desktop</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FileURLMobile__c</fullName>
        <description>Stores the URL of the mobile file related to the media element.</description>
        <inlineHelpText>Stores the URL of the mobile file related to the media element.</inlineHelpText>
        <label>File URL Mobile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FileURLTablet__c</fullName>
        <description>Stores the URL of the tablet file related to the media element.</description>
        <inlineHelpText>Stores the URL of the tablet file related to the media element.</inlineHelpText>
        <label>File URL Tablet</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Media Element</label>
    <nameField>
        <label>Media Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media elements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Translation__c.object
<CustomObject>
    <description>Translates Content or Media elements into a given language</description>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Translations</relationshipLabel>
        <relationshipName>Translations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MediaElement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Media Element</label>
        <referenceTo>MediaElement__c</referenceTo>
        <relationshipLabel>Translations</relationshipLabel>
        <relationshipName>Translations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Translation</label>
    <nameField>
        <label>Translation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Translations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MockupFactory.cls
public class MockupFactory {
    /*public static void createRecords(){
        //Cluster Root
        String name = 'Argentina';
        generateAcceleratorSetting();
        //List<Cluster__c> clusterRootList = createclusterRoot(new List<String>{name});
        List<Cluster__c> clusterRootList = createCluster(name, null, 1, 'ClusterRoot');
        Cluster__c cg = clusterRootList[0];

        //Cluster
        //List<Cluster__c> clusterList = createCluster(clusterRootList);
        List<Cluster__c> clusterList = createCluster(cg.Name, cg.Id, 1, 'ClusterGroup');
        
        Cluster__c clusterArg = clusterList[0];
        
        //Banner
        String nameRecordType = 'Banner';
        List<Component__c> componentList = createComponent(nameRecordType, 2);

        //Content
        List<Content__c> contentList = createContent(nameRecordType, clusterList[0], 5);
        
        //ContentAssignment
        List<ContentAssignment__c> contentAssignmentList = createContentAssignment(contentList, componentList);
        
        //MediaElement
        List<MediaElement__c> mediaElementList = createMediaElement(1);
        List<ContentDocumentLink> contentDocumentLinkList = createContentDocumentLink(mediaElementList);
        String fileUrl = AcceleratorSettings__c.getInstance().SalesforceDomain__c + '/sfc/servlet.shepherd/document/download/' + contentDocumentLinkList[0].ContentDocumentId;
        for(Integer i = 0; i < mediaElementList.size(); i++){
            mediaElementList[i].FileURLDesktop__c = fileUrl;
            mediaElementList[i].FileURLMobile__c = fileUrl;
            mediaElementList[i].FileURLTablet__c = fileUrl;
        }
        update mediaElementList;
        
        //Translations
        Map<String,String> apiNameTypeMap = new Map<String, String>();
        apiNameTypeMap.put('DetailTitle__c','Text');
        apiNameTypeMap.put('ListDescription__c','TextArea');
        apiNameTypeMap.put('DetailDescription__c','TextAreaRich');
        apiNameTypeMap.put('TestFieldError','Text');
        List<Translation__c> translationList = createTranslation(contentList[0], apiNameTypeMap, 'en_US');
    }*/
    
    // Before to create first cluster, run just one time.
    public static void generateAcceleratorSetting(){

        AcceleratorSettings__c acceleratorSetting  = new AcceleratorSettings__c ( 
            MaxSizeDesktop__c= 1280, 
            MaxSizeMobile__c = 480, 
            MaxSizeTablet__c = 768,
            ClusterFieldForPublicGroups__c='ExternalId__c');
        insert acceleratorSetting;
    }
    //Create Cluster__c, sure to call generateAcceleratorSetting() one time before
    public static List<Cluster__c> createCluster(String clusterName, String parentClusterId, Integer quantity, String clusterType){
        List<Cluster__c> clusterList = new List<Cluster__c>();
        RecordType rtGroup = [SELECT Id FROM RecordType WHERE SobjectType = 'Cluster__c' AND DeveloperName =: clusterType];

        Id parentClusterId2 = (Id) parentClusterId;

        for(Integer i = 0; i < quantity; i++){
            if(quantity>1){
                clusterList.add(new Cluster__c(Name = clusterName+i, ParentCluster__c = parentClusterId, RecordTypeId = rtGroup.Id));
            }else{
                clusterList.add(new Cluster__c(Name = clusterName, ParentCluster__c = parentClusterId, RecordTypeId = rtGroup.Id));
            }
            
        }
        insert clusterList;
        
        System.debug('MockupFactory clusterList: '+clusterList);
        return clusterList;
    }

   public static List<Cluster__c> createCluster(String clusterName, List<String> parentClusterIdList, Integer quantity, String clusterType, String defaultLanguage, String otherLangeuage){
        List<Cluster__c> clusterList = new List<Cluster__c>();
        RecordType rtGroup = [SELECT Id FROM RecordType WHERE SobjectType = 'Cluster__c' AND DeveloperName =: clusterType];
        System.debug('MockupFactorycreateCluster parentClusterIdList: ' + parentClusterIdList);
        if(parentClusterIdList!=null){
            integer j = 0;
            for(Id parentClusterId: parentClusterIdList){
                for(Integer i = 0; i < quantity; i++){
                    if(quantity>1){
                        clusterList.add(new Cluster__c(Name = clusterName+j+i, ParentCluster__c = parentClusterId, RecordTypeId = rtGroup.Id, DefaultLanguage__c = defaultLanguage, OtherLanguages__c = otherLangeuage));
                    }else{
                        clusterList.add(new Cluster__c(Name = clusterName, ParentCluster__c = parentClusterId, RecordTypeId = rtGroup.Id, DefaultLanguage__c = defaultLanguage, OtherLanguages__c = otherLangeuage));
                    }
                    
                }
                j++;
            }
        }else{
            for(Integer i = 0; i < quantity; i++){
                if(quantity>1){
                    clusterList.add(new Cluster__c(Name = clusterName+i, ParentCluster__c = null, RecordTypeId = rtGroup.Id, DefaultLanguage__c = defaultLanguage, OtherLanguages__c = otherLangeuage));
                }else{
                    clusterList.add(new Cluster__c(Name = clusterName, ParentCluster__c = null, RecordTypeId = rtGroup.Id, DefaultLanguage__c = defaultLanguage, OtherLanguages__c = otherLangeuage));
                }
                
            }
        }

        //Id parentClusterId2 = (Id) parentClusterId;
        System.debug('MockupFactory clusterList: '+clusterList);

        insert clusterList;
        
        System.debug('MockupFactory clusterList: '+clusterList);
        return clusterList;
    }


    //Create Cluster__c (Root) by names
    /*public static List<Cluster__c> createClusterRoot(List<String> nameList){
        List<Cluster__c> clusterRootList = new List<Cluster__c>();
        RecordType rtRoot = [SELECT Id FROM RecordType WHERE SobjectType = 'Cluster__c' AND DeveloperName = 'ClusterRoot'];

        for(String name : nameList){
            clusterRootList.add(new Cluster__c(Name = name, RecordTypeId = rtRoot.Id));
        }
        insert clusterRootList;
        return clusterRootList;
    }

    //Create Cluster__c by clusterRootList
    public static List<Cluster__c> createCluster(List<Cluster__c> clusterRootList){
        List<Cluster__c> clusterList = new List<Cluster__c>();
        RecordType rtGroup = [SELECT Id FROM RecordType WHERE SobjectType = 'Cluster__c' AND DeveloperName = 'ClusterGroup'];

        for(Cluster__c cRoot : clusterRootList){
            clusterList.add(new Cluster__c(Name = cRoot.name, ParentCluster__c = cRoot.id, RecordTypeId = rtGroup.Id));
        }
        insert clusterList;
        return clusterList;
    }*/

    public static User createUser(String username, String email){
        User user = new User();
        user.username = username;
        user.email = email;
        insert user;
        return user;
    }

    public static List<ClusterUser__c> createClusterUser(Id clusterId, Id userId, Integer quantity, String accessLevel){

        //ClusterUser__c clusterUser = new ClusterUser__c(Cluster__c=clusterId, User__c=userId, AccessLevel__c=accessLevel);
        List<ClusterUser__c> clusterUserList = new List<ClusterUser__c>();
        for(integer i; i<quantity; i++){
            clusterUserList.add( new ClusterUser__c(Cluster__c=clusterId, User__c=userId, AccessLevel__c=accessLevel));
        }
        return clusterUserList;

    }

    public static void deleteClusterByName(String clusterName){

        Cluster__c getClusterRoot = [SELECT Id FROM Cluster__c WHERE name = :clusterName LIMIT 1];
        delete getClusterRoot;
    }

    //Create Component__c by RecordTypeName
    public static List<Component__c> createComponent(String nameRecordType, Integer quantity){
        List<Component__c> componentList= new List<Component__c>();
        RecordType recordT = [SELECT id FROM RecordType WHERE SobjectType = 'Component__c' AND Name =: nameRecordType LIMIT 1];
        
        for(Integer i = 0; i < quantity; i++){
            componentList.add(new Component__c(Name = nameRecordType + ' ' + i,
                                    ExternalId__c = nameRecordType +'Component_' + i,
                                    Datasource__c = 'ManualAssignment',
                                    Status__c = 'Available',
                                    RecordTypeId = recordT.id));
        }
        insert componentList;
        return componentList;
    }

    //Create Content__c by RecordTypeName
    public static List<Content__c> createContent(String nameRecordType, Cluster__c clusterArg, Integer quantity){
        List<Content__c> contentList = new List<Content__c>();
        RecordType recordT = [SELECT id FROM RecordType WHERE SobjectType = 'Content__c' AND Name =: nameRecordType LIMIT 1];

        for(Integer i = 0; i < quantity; i++){
            contentList.add(new Content__c(Name = nameRecordType + ' ' + i,
                                    ExternalId__c = nameRecordType + 'Content_' + i,
                                    RecordTypeId = recordT.id,
                                    Cluster__c = clusterArg.id));
        }
        insert contentList;
        return contentList;
    }

    //Create ContentAssignment__c by Content && Component
    public static List<ContentAssignment__c> createContentAssignment(List<Content__c> contentList, List<Component__c> componentList){
        List<ContentAssignment__c> contentAssignmentList = new List<ContentAssignment__c>();
        Integer quantity = 0;
        if(contentList != null && componentList != null){
            quantity = contentList.size() < componentList.size() ? contentList.size() : componentList.size();
        }
        for(Integer i = 0; i < quantity; i++){
            contentAssignmentList.add(new ContentAssignment__c(Content__c = contentList[i].id,
                                    Component__c = componentList[i].id));
        }
        insert contentAssignmentList;
        return contentAssignmentList;
    }

    //Create MediaElement__c
    public static List<MediaElement__c> createMediaElement(Integer quantity){
        List<MediaElement__c> mediaElementList = new List<MediaElement__c>();
        
        for(Integer i = 0; i < quantity; i++){
            mediaElementList.add(new MediaElement__c(Name = 'MediaElement ' + i,
                                    ExternalId__c = 'MediaElement_' + i));
        }
        insert mediaElementList;
        return mediaElementList;
    }

    //Create ContentDocumentLink
    public static List<ContentDocumentLink> createContentDocumentLink(List<MediaElement__c> mediaElementList){
        List<ContentDocumentLink> contentDocumentLinkList = new List<ContentDocumentLink>();
        
        String base64Data = 'iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==';
        ContentVersion cv = new ContentVersion(
            ContentLocation = 'S',
            VersionData = EncodingUtil.base64Decode(base64Data),
            Title = 'ContentVersion',
            PathOnClient = 'ContentVersion');
        insert cv;

        String contentDocument = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
        for(MediaElement__c mediaElement : mediaElementList){
            contentDocumentLinkList.add(new ContentDocumentLink(
                            ContentDocumentId = contentDocument,
                            LinkedEntityId = mediaElement.Id,
                            ShareType = 'V' ));
        }
        insert contentDocumentLinkList;
        return contentDocumentLinkList;
    }

    //Create Translation__c
    public static List<Translation__c> createTranslation(Content__c content, Map<String,String> apiNameTypeMap, String language){
        List<Translation__c> translationList= new List<Translation__c>();
                
        for(String key : apiNameTypeMap.keyset()){
            String typeField = apiNameTypeMap.get(key);
            Translation__c translation = new Translation__c(Name = 'Translation ' + key + ' ' + typeField,
                                    Content__c = content.Id,
                                    FieldApiName__c = key,
                                    FieldType__c = typeField,
                                    LanguageCode__c = language);

            if(typeField == 'Text'){
                translation.TranslationText__c = key + ' Translate ';
            }else {
                if(typeField == 'TextArea'){
                    translation.TranslationTextArea__c = key + ' Translated';
                } else {
                    if(typeField == 'TextAreaRich'){
                        translation.TranslationTextAreaRich__c = key + ' Translated';
                    } else {
                        if(typeField == 'URL'){
                            translation.TranslationURL__c = key + ' Translated';
                        } else {
                            if(typeField == 'Email'){
                                translation.TranslationURL__c = key + ' Translated';
                            }
                        }
                    }
                }
            }
            translationList.add(translation);
        }
        insert translationList;
        return translationList;
    }
}