src/objects/AudienceUser__c.object
<CustomObject>
    <description>Relationship between Users and Navigation variants. You can view the specific user for an specific audience for access to the community preview.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipName>Audienceusers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Audience User</label>
    <nameField>
        <label>Audience user Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audience Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AudienceUserTriggersTest.cls
@isTest
private class AudienceUserTriggersTest {
    @testSetup
    static void generateAcceleratorSetting(){
        MockupFactory.generateAcceleratorSetting();
        
    }
@isTest
	static void insertAudienceUserTest(){
		/* Comment: Comprueba que al crear un AudienceUser__c se inserta
		con el correspondiente ExternalId__c */
		
		//When
		Test.startTest();
		List<Cluster__c> clusterList = MockupFactory.createCluster('ClusterRootTest', null, 1, 'ClusterRoot', 'CRT');
		User us = MockupFactory.createUser('userTest@cg.com','test@testinguser.com');
		AudienceUser__c AU = MockupFactory.createAudienceUser('AudienceUser1',clusterList[0].Id,'Active',us.Id);
		Test.stopTest();

		//Then
		AudienceUser__c audienceUserTestResult =[SELECT Id, ExternalId__c FROM AudienceUser__c WHERE Id =: AU.Id];
		System.assertNotEquals(audienceUserTestResult.ExternalId__c, null);
	}

	@isTest
	static void updateAudienceUserTest(){
		/* Comment: Comprueba que al actualizar un AudienceUser__c se actualiza
		con el correspondiente ExternalId__c */

		//Given
	    List<Cluster__c> clusterList = MockupFactory.createCluster('ClusterRootTest', null, 1, 'ClusterRoot', 'CRT');
		User us = MockupFactory.createUser('userTest@cg.com','test@testinguser.com');
		AudienceUser__c AU = MockupFactory.createAudienceUser('AudienceUser1',clusterList[0].Id,'Active',us.Id);
		AU.ExternalId__c = '';
		

		
		//When
		Test.startTest();
		update(AU);
		Test.stopTest();

		//Then
		AudienceUser__c audienceUserTest2 =[SELECT Id, ExternalId__c FROM AudienceUser__c WHERE Id =: AU.Id];
		System.assertNotEquals(audienceUserTest2.ExternalId__c, null);
	}

}