src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>BrandContent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <recordTypes>
        <fullName>Brand</fullName>
        <active>true</active>
        <description>Represents the highest level of a Brand tree.</description>
        <label>Brand</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterGroup</fullName>
        <active>true</active>
        <description>Represents a grouping cluster of other grouping clusters or cluster leafs. (Ex.: EMEA, Africa, Latam).</description>
        <label>Cluster Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>URLRedirect__c</fullName>
        <defaultValue>&apos;http://&apos;</defaultValue>
        <label>URL Redirect</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>Recipe</fullName>
        <active>true</active>
        <description>Configure a new Recipe content. This content will be shown inside a Recipe</description>
        <label>Recipe</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContentCartItem__c.object
<CustomObject>
    <description>Represent the content item on the content cart.</description>
    <fields>
        <fullName>Content__c</fullName>
        <description>Master detail to content record</description>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Content Cart Items</relationshipLabel>
        <relationshipName>Content_Cart_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Content Cart Item</label>
    <nameField>
        <label>Content Cart Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MediaElement__c.object
<CustomObject>
    <description>Represents the repository of media elements that can be assigned to multiple contents.</description>
    <fields>
        <fullName>FileURLDesktop__c</fullName>
        <description>Stores the URL of the desktop file related to the media element.</description>
        <inlineHelpText>Stores the URL of the desktop file related to the media element.</inlineHelpText>
        <label>File URL Desktop</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Media Element</label>
    <nameField>
        <label>Media Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media elements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MediaElementAssignment__c.object
<CustomObject>
    <description>Holds the relationship between each media element and the Contents it is beeing used on. This relationship can also be categorized</description>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>MediaElementAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MediaElement__c</fullName>
        <label>Media Element</label>
        <referenceTo>MediaElement__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <label>Placement</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Media Element Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Media Element Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Element Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Recipe__c.object
<CustomObject>
    <description>Represents the recipes and contains the elements related to them as ingredients, instructions and the relationship with the corresponding brand</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Determine which cluster is associated with the recipe.</description>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Recipes</relationshipLabel>
        <relationshipName>Recipes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Recipes</relationshipLabel>
        <relationshipName>Recipes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recipe</label>
    <nameField>
        <label>Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RecipeIngredient__c.object
<CustomObject>
    <description>represents the ingredients of a recipe</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the brand to which it belongs</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Recipes Ingredients</relationshipLabel>
        <relationshipName>RecipesIngredients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recipe__c</fullName>
        <description>Represent the recipe</description>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Recipes Ingredients</relationshipLabel>
        <relationshipName>RecipesIngredients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Recipe Ingredient</label>
    <nameField>
        <label>Recipe Ingredient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes Ingredients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RecipeStep__c.object
<CustomObject>
    <description>steps to make in the recipe</description>
    <fields>
        <fullName>Recipe__c</fullName>
        <description>Represent the recipe</description>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Recipes Steps</relationshipLabel>
        <relationshipName>RecipesSteps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Recipe Step</label>
    <nameField>
        <label>Recipe Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CG_AssetDetailControllerTest.cls
@isTest
private class CG_AssetDetailControllerTest {


	@testSetup
    static void setupTest(){
    	String nameRecordType = 'Recipe';
    	Integer quantity = 3;
    	MockupFactory.generateAcceleratorSetting();
        
        String name = 'Argentina';
        List<Cluster__c> clusterRootList = MockupFactory.createCluster(name, null, 1, 'ClusterRoot', 'CRT');
        Cluster__c cg = clusterRootList[0];
        List<Cluster__c> clusterList = MockupFactory.createCluster('BuenosAires', cg.Id, 1, 'ClusterGroup', 'CGT');

    	List<Content__c> contentList = MockupFactory.createContent(nameRecordType, clusterList[0], 1);

		List<MediaElement__c> mediaElementList= MockupFactory.createMediaElement(quantity);

		List<MediaElementAssignment__c> mediaElementAssList = new List<MediaElementAssignment__c>();
        
        for(Integer i = 0; i < mediaElementList.size(); i++){
            mediaElementAssList.add(new MediaElementAssignment__c(Content__c = contentList[0].id,
                                    MediaElement__c = mediaElementList[i].id));
        }
        insert mediaElementAssList;

        List<ContentDocumentLink> contentDocList = MockupFactory.createContentDocumentLink(mediaElementList);
	
    }
/*
	@isTest 
	static void getRecordsTest() {
		//When
		Content__c cont = [SELECT id from Content__c limit 1];

		//Given
		Test.startTest();
		CG_AssetDetailController.ContentWrapper contWr = CG_AssetDetailController.getRecord(cont.id, null);
		Test.stopTest();
		
		//Then
		System.assertNotEquals(contWr, null);
	}
*/


	@isTest 
	static void downloadAllItemsTest() {
		//When
		Content__c cont = [SELECT id from Content__c limit 1];
		CG_AssetDetailController.ContentWrapper contWr = CG_AssetDetailController.getRecord(cont.id, null);
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());


		//Given
		Test.startTest();
		Map <String, String> imagenMap = CG_AssetDetailController.downloadAllItems(JSON.serialize(contWr));
		Test.stopTest();
		
		//Then
		System.assertEquals(imagenMap.keySet().size(), 0);
	}


	@isTest 
	static void initDataExternalTest() {
		//When
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		List<MediaElement__c> mediaElementList = [SELECT Id FROM MediaElement__c];

        for(MediaElement__c media : mediaElementList){
        	media.FileURLDesktop__c='https://www.google.com/logos/doodles/2018/gottfried-wilhelm-leibnizs-372nd-birthday-4525892901535744-2x';
        }
        update mediaElementList;

        Content__c cont = [SELECT id from Content__c limit 1];
		CG_AssetDetailController.ContentWrapper contWr = CG_AssetDetailController.getRecord(cont.id, null);
		//Given
		Test.startTest();
		Map <String, String> imagenMap = CG_AssetDetailController.downloadAllItems(JSON.serialize(contWr));
		Test.stopTest();
		
		//Then
		System.assertEquals(imagenMap.keySet().size(), 0);
	}

	@isTest
	static void getRecordsRecipeTest(){
		//When
		List<Content__c> contentList = [SELECT id FROM Content__c];
		Content__c cont = contentList[0];
		cont.URLRedirect__c='http://example.com/example/test';
		update cont;

		List<MediaElementAssignment__c> meaList = [SELECT Id, MediaElement__c, Placement__c FROM MediaElementAssignment__c];
		meaList[0].Placement__c='RecipeImageList';
		meaList[1].Placement__c='RecipeImageDetail';
		meaList[2].Placement__c='BrandImageList';
		update meaList;

		List<Brand__c> brandList = MockupFactory.createBrand('BrandTest', 1, null);
		brandList[0].BrandContent__c= cont.Id;
		update brandList;

		List<Recipe__c> recipesList = MockupFactory.createRecipes('recipeTest', 1, cont.Id, null);
		List<RecipeStep__c> stepsList = MockupFactory.createRecipeStep('stepTest', 1, recipesList[0].id);
		List<RecipeIngredient__c> ingredientsList = MockupFactory.createRecipeIngredientBrand('IngredientsList', 1, recipesList[0].id, brandList[0].Id, brandList[0].Id);
		List<RecipeIngredient__c> ingredientNotBrand = MockupFactory.createRecipeIngredientWithoutBrand('IngredientsNotBrandList', 1, recipesList[0].id);

		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		//Given
		Test.startTest();
		CG_AssetDetailController.ContentWrapper contWr = CG_AssetDetailController.getRecord(cont.id, null);
		Map <String, String> contZip = CG_AssetDetailController.downloadAllItems(JSON.serialize(contWr));
		Test.stopTest();
		
		//Then
		System.assertNotEquals(contWr, null);
	}

		@isTest
	static void getRecordsBrandTest(){
		//When
		 List<Cluster__c> clusterRootList = MockupFactory.createCluster('America', null, 1, 'ClusterRoot', 'Ame');
		List<Content__c> contentList = MockupFactory.createContent('Brand Detail',clusterRootList[0], 1);
		Content__c cont = contentList[0];
		cont.URLRedirect__c='http://example.com/example/test';
		update cont;

		List<MediaElementAssignment__c> meaList = [SELECT Id, MediaElement__c, Placement__c FROM MediaElementAssignment__c];
		meaList[0].Placement__c='BrandImageBanner';
		meaList[1].Placement__c='BrandImageLogo';
		meaList[2].Placement__c='BrandImageList';
		update meaList;


		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		//Given
		Test.startTest();
		CG_AssetDetailController.ContentWrapper contWr = CG_AssetDetailController.getRecord(cont.id, null);
		
		Test.stopTest();
		
		//Then
		System.assertNotEquals(contWr, null);
	}
	

	@isTest
	static void addToCartTest(){
		//When
		List<Content__c> contentList = [SELECT id FROM Content__c];
		//Given
		Test.startTest();
		CG_AssetDetailController.addToCart(contentList[0].id);
		Test.stopTest();
		
		//Then
		List<ContentCartItem__c> contentCart = [SELECT id FROM ContentCartItem__c];
		System.assertNotEquals(contentCart, null);
	}

}