src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <recordTypes>
        <fullName>Brand</fullName>
        <active>true</active>
        <description>Represents the highest level of a Brand tree.</description>
        <label>Brand</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SocialNetwork__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Social Network</relationshipLabel>
        <relationshipName>Social_Network</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Navigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Navigation</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Social Network (Navigation)</relationshipLabel>
        <relationshipName>Social_Network1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Social Network</label>
    <nameField>
        <label>SocialNetwork Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Network</pluralLabel>
    <recordTypes>
        <fullName>Twitter</fullName>
        <active>true</active>
        <label>Twitter</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CG_SocialNetworkControllerTest.cls
@isTest
public with sharing class CG_SocialNetworkControllerTest {
	
	@isTest
	public static void setNetworkData(){
		//Given
		MockupFactory.generateAcceleratorSetting();
		List<Cluster__c> cluster = MockupFactory.createCluster('ClusterTest', null, 1, 'ClusterRoot', 'CRT');
		List<Navigation__c> navigation = MockupFactory.createNavigation('TestNav', 'http://www.google.com/', 1 , cluster[0].Id);
		List<Brand__c> brand = MockupFactory.createBrand('BrandTest', 1, cluster[0].Id);
		List<SocialNetwork__c> socialNetwork = MockupFactory.createSocialNetworks('Test','test',brand[0].Id,navigation[0].Id,'Twitter');
		
		//Then
		Test.startTest();
		CG_SocialNetworkController.NetworkWrapper socialNetworkToBrand = CG_SocialNetworkController.getSocialNetworks(brand[0].Id);
		Test.stopTest();
	}
}