src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>BrandContent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MasterBrand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>BrandVariants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <recordTypes>
        <fullName>Brand</fullName>
        <active>true</active>
        <description>Represents the highest level of a Brand tree.</description>
        <label>Brand</label>
    </recordTypes>
    <recordTypes>
        <fullName>BrandVariant</fullName>
        <active>true</active>
        <description>Represents a grouping brand of other grouping brands or brand leafs.</description>
        <label>Brand Variant</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LinkDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Link Detail</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner component. Each banner component has a given aspect ratio and orientation for its presentation. It also has a given behavior for presenting its content such as carousel or appear-disappear effect.</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LinkDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Link Detail</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner content. This content will scroll or appear-fade inside a Banner. The data this type of content allows are Media elements</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MediaElement__c.object
<CustomObject>
    <description>Represents the repository of media elements that can be assigned to multiple contents.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Describes the media element stating things such as what can you see in a photograph (Ex. Child feeding a dog)</description>
        <label>Description</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FileURLDesktop__c</fullName>
        <description>Stores the URL of the desktop file related to the media element.</description>
        <inlineHelpText>Stores the URL of the desktop file related to the media element.</inlineHelpText>
        <label>File URL Desktop</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Media Element</label>
    <nameField>
        <label>Media Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media elements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MediaElementAssignment__c.object
<CustomObject>
    <description>Holds the relationship between each media element and the Contents it is beeing used on. This relationship can also be categorized</description>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>MediaElementAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MediaElement__c</fullName>
        <label>Media Element</label>
        <referenceTo>MediaElement__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <label>Placement</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Media Element Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Media Element Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Element Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CG_BrandDetailController.cls
public with sharing class CG_BrandDetailController {

    public class BrandDetailWrapper{
        @auraEnabled public Component__c component;
        @auraEnabled public String description;
        @auraEnabled public String title;
        @auraEnabled public String imageLogoURL;
        @auraEnabled public String imageBannerURL;
        @auraEnabled public boolean isVariant;
        @auraEnabled public boolean showContent;
        @auraEnabled public list<VariantWrapper> variants;
        public BrandDetailWrapper(){
            variants = new list<VariantWrapper>();
        }
    }

    public class VariantWrapper{
        @auraEnabled public String imageURL;
        @auraEnabled public String title;
        @auraEnabled public String id;
    }

    @auraEnabled
    public static BrandDetailWrapper getBrandWrapper(String brandId, String componentExternalId){
        BrandDetailWrapper bw = new BrandDetailWrapper();

        if(componentExternalId != null && componentExternalId != ''){
            bw.component = [SELECT Id, LinkDetail__r.URL__c FROM Component__c WHERE ExternalId__c =: componentExternalId];
        }

        if(brandId != null && brandId != '')
        {   
            bw.showContent = true;

            Brand__c brand = [SELECT Id, Name, BrandContent__c, BrandContent__r.Description__c, BrandContent__r.Title__c, MasterBrand__c, RecordType.DeveloperName, Description__c FROM Brand__c WHERE id = :brandId];
            if(brand.RecordType.DeveloperName == 'BrandVariant'){
                bw.isVariant = true;
                bw.description = brand.BrandContent__r.Description__c;
                bw.title = brand.BrandContent__r.Title__c;
            }

            if(brand.RecordType.DeveloperName == 'Brand'){
                bw.isVariant = false;
                bw.description = brand.BrandContent__r.Description__c;
                // GET BANNER URL AND LOGO URL
                list<MediaElementAssignment__c> brandContent = [SELECT MediaElement__r.FileURLDesktop__c, Placement__c  FROM MediaElementAssignment__c WHERE Content__c = :brand.BrandContent__c];
                for(MediaElementAssignment__c mediaElement : brandContent){
                    if(mediaElement.Placement__c == 'BrandImageBanner'){
                        bw.imageBannerURL = mediaElement.MediaElement__r.FileURLDesktop__c;
                    }
                    if(mediaElement.Placement__c == 'BrandImageLogo'){
                        bw.imageLogoURL = mediaElement.MediaElement__r.FileURLDesktop__c;
                    }
                }
                // GET THE RELATEDS 4 BRANDS
                list<Brand__c> relatedBrands = [SELECT Id, Name, BrandContent__c, BrandContent__r.Title__c FROM Brand__c WHERE MasterBrand__c =: brand.Id AND RecordType.DeveloperName = 'BrandVariant' ORDER BY LastModifiedDate DESC LIMIT 4];
                set<String> relatedBrandsContents = new set<String>();
                for (Brand__c rb : relatedBrands){
                    relatedBrandsContents.add(rb.BrandContent__c);
                }
                list<MediaElementAssignment__c> relatedContent = [SELECT MediaElement__r.FileURLDesktop__c, Content__c  FROM MediaElementAssignment__c WHERE Content__c IN: relatedBrandsContents];
                set<VariantWrapper> variants = new set<VariantWrapper>();
                for(Brand__c b : relatedBrands){
                    VariantWrapper vw = new VariantWrapper();
                    for(MediaElementAssignment__c content : relatedContent){
                        if(b.BrandContent__c == content.Content__c){
                            vw.title = b.BrandContent__r.Title__c;
                            vw.imageURL = content.MediaElement__r.FileURLDesktop__c;
                            vw.id = b.Id;
                            if(variants.size() < 4){
                                variants.add(vw);
                            }
                        }
                    }
                }
                if(variants != null){
                    bw.variants.addAll(variants);
                }
            }
        }
        else{
            bw.showContent=false;
        }
        return bw;
    }

}