src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <recordTypes>
        <fullName>Brand</fullName>
        <active>true</active>
        <description>Represents the highest level of a Brand tree.</description>
        <label>Brand</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SocialNetwork__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Social Network</relationshipLabel>
        <relationshipName>Social_Network</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Navigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Navigation</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Social Network (Navigation)</relationshipLabel>
        <relationshipName>Social_Network1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Social Network</label>
    <nameField>
        <label>SocialNetwork Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Network</pluralLabel>
    <recordTypes>
        <fullName>Twitter</fullName>
        <active>true</active>
        <label>Twitter</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SocialNetworkTriggersTest.cls
@isTest(seeAllData = false)
public with sharing class SocialNetworkTriggersTest {
	
	@testSetup
	static void generateCustomSettings(){
		MockupFactory.generateAcceleratorSetting();
	}

	@isTest
	public static void insertExternalId(){
		//Given
		List<Cluster__c> cluster = MockupFactory.createCluster('ClusterTest', null, 1, 'ClusterRoot', 'CRT');
		List<Navigation__c> navigation = MockupFactory.createNavigation('TestNav', 'http://www.google.com/', 1 , cluster[0].Id);
		List<Brand__c> brand = MockupFactory.createBrand('BrandTest', 1, cluster[0].Id);
		
		//When
		Test.startTest();
		List<SocialNetwork__c> socialNetwork = MockupFactory.createSocialNetworks('Test','test',brand[0].Id,navigation[0].Id, 'Twitter');
		Test.stopTest();

		//Then
		SocialNetwork__c socialNetworkResult = [SELECT Id, ExternalId__c FROM SocialNetwork__c WHERE Id =: socialNetwork[0].Id];
		System.assertNotEquals(socialNetworkResult.ExternalId__c, null);
	}

	@isTest
	public static void updateExternalId(){
		//Given
		List<Cluster__c> cluster = MockupFactory.createCluster('ClusterTest', null, 1, 'ClusterRoot', 'CRT');
		List<Navigation__c> navigation = MockupFactory.createNavigation('TestNav', 'http://www.google.com/', 1 , cluster[0].Id);
		List<Brand__c> brand = MockupFactory.createBrand('BrandTest', 1, cluster[0].Id);
		
		//When
		Test.startTest();
		List<SocialNetwork__c> socialNetwork = MockupFactory.createSocialNetworks('Test','test',brand[0].Id,navigation[0].Id, 'Twitter');
		socialNetwork[0].ExternalId__c = 'Test2';
		update socialNetwork[0];
		Test.stopTest();

		//Then
		SocialNetwork__c socialNetworkResult = [SELECT Id, ExternalId__c FROM SocialNetwork__c WHERE Id =: socialNetwork[0].Id];
		System.assertNotEquals(socialNetworkResult.ExternalId__c, null);	
	}
}