src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>BrandContent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MasterBrand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>BrandVariants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <recordTypes>
        <fullName>Brand</fullName>
        <active>true</active>
        <description>Represents the highest level of a Brand tree.</description>
        <label>Brand</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NavigationMode__c</fullName>
        <label>Navigation Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Horizontal-Simple</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URLRedirect__c</fullName>
        <defaultValue>&apos;http://&apos;</defaultValue>
        <label>URL Redirect</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>BrandDetail</fullName>
        <active>true</active>
        <description>Configure a new Brand Detail content. This content will display a a brand detail including all it related brands. The data this type of content allows are Media elements</description>
        <label>Brand Detail</label>
    </recordTypes>
    <recordTypes>
        <fullName>Recipe</fullName>
        <active>true</active>
        <description>Configure a new Recipe content. This content will be shown inside a Recipe</description>
        <label>Recipe</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MediaElement__c.object
<CustomObject>
    <description>Represents the repository of media elements that can be assigned to multiple contents.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Describes the media element stating things such as what can you see in a photograph (Ex. Child feeding a dog)</description>
        <label>Description</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FileURLDesktop__c</fullName>
        <description>Stores the URL of the desktop file related to the media element.</description>
        <inlineHelpText>Stores the URL of the desktop file related to the media element.</inlineHelpText>
        <label>File URL Desktop</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Media Element</label>
    <nameField>
        <label>Media Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media elements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MediaElementAssignment__c.object
<CustomObject>
    <description>Holds the relationship between each media element and the Contents it is beeing used on. This relationship can also be categorized</description>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>MediaElementAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MediaElement__c</fullName>
        <label>Media Element</label>
        <referenceTo>MediaElement__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <label>Placement</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Media Element Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Media Element Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Element Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Recipe__c.object
<CustomObject>
    <description>Represents the recipes and contains the elements related to them as ingredients, instructions and the relationship with the corresponding brand</description>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Recipes</relationshipLabel>
        <relationshipName>Recipes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Recipe</label>
    <nameField>
        <label>Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RecipeIngredient__c.object
<CustomObject>
    <description>represents the ingredients of a recipe</description>
    <fields>
        <fullName>BrandVariant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the Brand Variant to which it belongs</description>
        <label>Brand Variant</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Recipes Ingredients (Brand Variant)</relationshipLabel>
        <relationshipName>RecipesIngredientsVariant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the brand to which it belongs</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Recipes Ingredients</relationshipLabel>
        <relationshipName>RecipesIngredients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomIngredient__c</fullName>
        <description>List of custom ingredients that do not belong to any brand</description>
        <label>Custom Ingredient</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CustomIngredient</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Field to order ingredients</description>
        <label>Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OtherIngredient__c</fullName>
        <description>list of other ingredients that do not belong to the brand</description>
        <label>Other Ingredient</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>List of quantities values for an ingredient in the recipe</description>
        <label>Quantity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Quantity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recipe__c</fullName>
        <description>Represent the recipe</description>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Recipes Ingredients</relationshipLabel>
        <relationshipName>RecipesIngredients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <description>List of unit for a quantity in a recipe</description>
        <label>Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit</valueSetName>
        </valueSet>
    </fields>
    <label>Recipe Ingredient</label>
    <nameField>
        <label>Recipe Ingredient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes Ingredients</pluralLabel>
    <recordTypes>
        <fullName>BrandIngredient</fullName>
        <active>true</active>
        <description>Represent an Ingredient with Brand</description>
        <label>Brand Ingredient</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RecipeStep__c.object
<CustomObject>
    <description>steps to make in the recipe</description>
    <fields>
        <fullName>Order__c</fullName>
        <description>Field to order Steps</description>
        <label>Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recipe__c</fullName>
        <description>Represent the recipe</description>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Recipes Steps</relationshipLabel>
        <relationshipName>RecipesSteps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Step__c</fullName>
        <description>description of step</description>
        <label>Step</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Recipe Step</label>
    <nameField>
        <label>Recipe Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tag__c.object
<CustomObject>
    <description>Short phrase or word to be used as a search criteria or joint criteria between different objects (Ex. Joint between Content and Components)</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Describe where this Tag will be used</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TagAssignment__c.object
<CustomObject>
    <description>The way to assign tags to Content or to Components</description>
    <fields>
        <fullName>Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tag_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tag</label>
        <referenceTo>Tag__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>TagAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tag Assignment</label>
    <nameField>
        <displayFormat>TAS-{000000000}</displayFormat>
        <label>Tag Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tag Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/CustomIngredient.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ice</fullName>
    </customValue>
    <customValue>
        <fullName>Ice Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Water</fullName>
    </customValue>
    <description>List of custom ingredients that do not belong to any brand</description>
    <masterLabel>Custom Ingredient</masterLabel>
</GlobalValueSet>

src/globalValueSets/Quantity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>List of quantities values for RecipeIngredient__c</description>
    <masterLabel>Quantity</masterLabel>
</GlobalValueSet>

src/globalValueSets/Unit.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>gr</fullName>
    </customValue>
    <customValue>
        <fullName>kg</fullName>
    </customValue>
    <customValue>
        <fullName>oz</fullName>
    </customValue>
    <description>List of units for RecipeIngredient__c</description>
    <masterLabel>Unit</masterLabel>
</GlobalValueSet>

src/classes/CG_AssetDetailController.cls
public with sharing class CG_AssetDetailController {
    //WRAPPERS
    public class ContentWrapper{
        @auraEnabled public String detailTitle;     
        @auraEnabled public String longDescription;
        @auraEnabled public String mediaElementImageURL;
        @auraEnabled public String mediaElementImageDocumentId;
        @auraEnabled public Boolean disableAdd;
        @auraEnabled public Boolean disableDownload;
        @auraEnabled public List<TagWrapper> tagsList;
        @auraEnabled public Boolean isRecipie;
        @auraEnabled public String pdfUrl;
        @auraEnabled public String ingredients;
        @auraEnabled public String instructions;
        @auraEnabled public String urlPrimaryImage;
        @auraEnabled public String urlPrimaryImageDocumentId;
        @auraEnabled public String urlFeaturingImage;
        @auraEnabled public String brandTitle;
        @auraEnabled public String urlBrandLink;

        public ContentWrapper(){
            isRecipie=false;
            detailTitle=' ';
            longDescription=' ';
            ingredients='';
            instructions=''; 
            urlPrimaryImageDocumentId=null;//'';
            mediaElementImageDocumentId='';
            disableAdd=false;
            disableDownload=false;
            tagsList= new List<TagWrapper>();
        }
	}

    public class TagWrapper{
        @auraEnabled public String detailTitle;
        @auraEnabled public String tagLink;
        public TagWrapper(String title, String link){
            detailTitle=title;
            tagLink= link;
        }
    }

/**
* Load all Wrappers attributes for the contentId. externalId is used to find the tags url
* and urlBrand for Featuring's image 
**/
    @AuraEnabled
    public static ContentWrapper getRecord(Id contentId, String externalId){
        Content__c content = getcontent(contentId);
        
        ContentWrapper contentWrapper = new ContentWrapper();
        if(content != null){
            contentWrapper.detailTitle = content.Title__c;

            contentWrapper.longDescription = content.Description__c;
            contentWrapper.tagsList = getTags(contentId, externalId);            

            System.debug('DEBUG: content.RecordType.DeveloperName: '+content.RecordType.DeveloperName);
            System.debug('DeveloperName: '+content.RecordType.DeveloperName);
            if(content.RecordType.DeveloperName == 'Recipe'){

                contentWrapper.isRecipie = true;
                //contentWrapper.pdfUrl = content.PDFURL__c;  ????????????? PREGUNTAR A LIHUE
                contentWrapper.pdfUrl =content.URLRedirect__c;	

				for(RecipeIngredient__c ing : [Select Id, CustomIngredient__c, OtherIngredient__c, Name, Quantity__c, Unit__c, BrandVariant__c, RecordType.DeveloperName  from RecipeIngredient__c where Recipe__r.content__c =: contentId order by Order__c]){                
               
                    if(String.isNotEmpty(ing.Quantity__c+ing.Unit__c)){
                       contentWrapper.ingredients= contentWrapper.ingredients + ing.Quantity__c+ing.Unit__c+' ';
                    }
                    if( ing.RecordType.DeveloperName.equalsIgnoreCase('BrandIngredient')){
                       contentWrapper.ingredients= contentWrapper.ingredients + ing.Name+'<br/>';
                    } 
                    if(String.isNotEmpty(ing.CustomIngredient__c)){
                        contentWrapper.ingredients= contentWrapper.ingredients + ing.CustomIngredient__c+'<br/>';
                    }
                    if(String.isNotEmpty(ing.OtherIngredient__c)){
                        contentWrapper.ingredients= contentWrapper.ingredients + ing.OtherIngredient__c+'<br/>';
                    }
                }

                for(RecipeStep__c step : [Select Id, Name, Order__c, Step__c from RecipeStep__c where Recipe__r.content__c =: contentId order by Order__c]){
                    contentWrapper.instructions = contentWrapper.instructions + step.Order__c+' '+ step.Step__c +'<br/>';
                }

                Map<String,String> mediaMap = searchMediasRecipes(contentId, externalId);

                if(String.isNotEmpty(mediaMap.get('RecipeImageDetail'))){
                    contentWrapper.urlPrimaryImage = mediaMap.get('RecipeImageDetail');
                    contentWrapper.urlPrimaryImageDocumentId = mediaMap.get('RecipeImageDetail').right(18);
                }
                if(String.isNotEmpty(mediaMap.get('RecipeImageList'))){
                    contentWrapper.mediaElementImageURL = mediaMap.get('RecipeImageList');
                    contentWrapper.mediaElementImageDocumentId = mediaMap.get('RecipeImageList').right(18);
                }

                if(String.isNotEmpty(mediaMap.get('BrandImageList'))){
                    contentWrapper.urlFeaturingImage = mediaMap.get('BrandImageList');
                }
                contentWrapper.brandTitle = mediaMap.get('brandTitle');

                contentWrapper.disableAdd = (String.isEmpty(mediaMap.get('RecipeImageDetail')) && String.isEmpty(mediaMap.get('RecipeImageList')));
                contentWrapper.disableDownload = (String.isEmpty(mediaMap.get('RecipeImageDetail')) && String.isEmpty(mediaMap.get('RecipeImageList')));

                contentWrapper.urlBrandLink = mediaMap.get('urlBrandLink');

            }else if(!content.MediaElementAssignments__r.isEmpty() && content.MediaElementAssignments__r[0].MediaElement__c != null){
                contentWrapper.mediaElementImageURL = content.MediaElementAssignments__r[0].MediaElement__r.FileURLDesktop__c;
                contentWrapper.mediaElementImageDocumentId = contentWrapper.mediaElementImageURL.right(18);
                contentWrapper.disableAdd=false;
                contentWrapper.disableDownload=false;
            }
        }
    
        return contentWrapper;
    }

/**
* This method is called to add a mediaElement to the cart
* url is the url of the mediaElement image
* urlPrimary is the url for the second image (only for recipes) 
**/ 

    @AuraEnabled
    public static void addToCart(Id contentId){ 
        Boolean isInserted = CG_ContentCartController.addContentToCart(contentId);
        if (!isInserted){
        	throw new AuraHandledException(System.Label.DuplicateItem);
        }
    }
    
    /**
    * obtains the corresponding CP_content_c for the requested contentId
    **/
    private static Content__c getcontent(Id contentId){

        Content__c content;
        try{
            //search for asset-details page
            //Ingredients__c, Instructions__c,
        	 content = [SELECT Id, RecordType.DeveloperName, Title__c, Description__c, URLRedirect__c, 
                       (SELECT Id, MediaElement__c, Placement__c, MediaElement__r.FileURLDesktop__c FROM MediaElementAssignments__r WHERE Placement__c = 'assetImage')
                        FROM Content__c
                        WHERE Id =:contentId]; 

            //search for assets page
            //Ingredients__c, Instructions__c,
            if(content.RecordType.DeveloperName == 'BrandDetail'){
                content = [SELECT Id, RecordType.DeveloperName, Title__c, Description__c, URLRedirect__c,
                       (SELECT Id, MediaElement__c, Placement__c, MediaElement__r.FileURLDesktop__c FROM MediaElementAssignments__r WHERE Placement__c = 'BrandImageList') //'brandVariantCatalogImage')
                        FROM Content__c
                        WHERE Id =:contentId]; 
            }
/* NO EXISTEN ESTOS RECORD TYPE
            //Ingredients__c, Instructions__c,
            if(content.RecordType.DeveloperName == 'Product'){
                content = [SELECT Id, RecordType.DeveloperName, Title__c, Description__c, URLRedirect__c,
                       (SELECT Id, MediaElement__c, Placement__c, MediaElement__r.FileURLDesktop__c FROM MediaElementAssignments__r WHERE Placement__c = 'productImage')
                        FROM Content__c
                        WHERE Id =:contentId]; 
            }

            //Ingredients__c, Instructions__c,
            if(content.RecordType.DeveloperName == 'Brand'){
                content = [SELECT Id, RecordType.DeveloperName, Title__c, Description__c, URLRedirect__c,
                       (SELECT Id, MediaElement__c, Placement__c, MediaElement__r.FileURLDesktop__c FROM MediaElementAssignments__r WHERE Placement__c = 'BrandImageLogo') //'BrandLogoImage')
                        FROM Content__c
                        WHERE Id =:contentId]; 
            }
*/
        }catch(exception e){}

        return content;     
    }

/**
* search tags related with the Content__c with id = contentId
**/
    private static List<TagWrapper> getTags(Id contentId, String externalId){
        String link= getLinkTag(externalId);
        List<TagWrapper> tagsList = new List<TagWrapper>();
        try{
            for(TagAssignment__c tagAssig :[SELECT id, Tag__r.id, Tag__r.Name  from TagAssignment__c where Content__c =: contentId]){
                TagWrapper tag = new TagWrapper(tagAssig.Tag__r.Name, link+'?tag='+tagAssig.Tag__r.id);
                tagsList.add(tag);
            }
        }catch(exception e){} 
        return tagsList; 
    }   

/**
* search media elements and Brand Url for asset type recipe for recipe-detail page
**/
    private static Map<String, String> searchMediasRecipes(Id contentId, String externalId){
        Map<String, String> mediaMap = new Map<String, String>();
        try{
            Content__c content = [SELECT Id,
                                    (SELECT Id, MediaElement__c, Placement__c, MediaElement__r.FileURLDesktop__c FROM MediaElementAssignments__r WHERE Placement__c in ('RecipeImageList','RecipeImageDetail')) 
                                     FROM Content__c WHERE Id =: contentId Limit 1];
            
            for(MediaElementAssignment__c media : content.MediaElementAssignments__r){
                mediaMap.put(media.Placement__c, media.MediaElement__r.FileURLDesktop__c);
            }
            
            RecipeIngredient__c recipe = [SELECT id, BrandVariant__c, Recipe__c FROM RecipeIngredient__c WHERE Recipe__r.content__c =: contentId and RecordType.DeveloperName = 'BrandIngredient' ];
            Brand__c brand = [SELECT Id, Name, BrandContent__c, BrandContent__r.Description__c, BrandContent__r.Title__c, MasterBrand__c, RecordType.DeveloperName, Description__c FROM Brand__c WHERE Id = :recipe.BrandVariant__c];

            list<MediaElementAssignment__c> brandContent = [SELECT id, MediaElement__r.FileURLDesktop__c, Placement__c FROM MediaElementAssignment__c WHERE Content__c =: brand.BrandContent__c and Placement__c = 'BrandImageList' ];
            mediaMap.put('BrandImageList', brandContent[0].MediaElement__r.FileURLDesktop__c);
            mediaMap.put('brandTitle', brand.BrandContent__r.Title__c);
            String link = getLinkFeaturing(externalId);
           mediaMap.put('urlBrandLink', link+'?brand='+brand.Id);
    
        }catch(exception e){}
        return mediaMap;
    }

/**
* 
**/
    private static String getLinkTag(String externalId){ 
        if(externalId != null){
            try{
                Component__c comp = [SELECT id, NavigationMode__c FROM Component__c WHERE ExternalId__c = :externalId ];
                return comp.NavigationMode__c;
            }catch(exception e){}
        }
        return '';
    }

    private static String getLinkFeaturing(String externalId){
        if(externalId != null){
            try{
                Component__c comp = [SELECT id, LinkDetail__c FROM Component__c WHERE ExternalId__c = :externalId ];
                return comp.LinkDetail__c;
            }catch(exception e){}
        }
        return '';
    } 


    @AuraEnabled
    public static Map <String, String> downloadAllItems(String data){
        ContentWrapper contentWr = (ContentWrapper)JSON.deserialize(data, ContentWrapper.class);                
        Map <String, String> imageMap = new Map <String, String>();
        List<String> documentInternalIdList = new List<String>();
        List<String> documentExternalList = new List<String>();

        List<String> urlList = new List<String>();
        
        if(String.isNotEmpty(contentWr.mediaElementImageURL)){
           urlList.add(contentWr.mediaElementImageURL);
        }   
        if(String.isNotEmpty(contentWr.urlPrimaryImage)){
           urlList.add(contentWr.urlPrimaryImage);
        }  
        
        //GET SALESFORCE DOCUMENTID FOR INTERNAL IMAGE
        for(String mea : urlList){
            List<String> stringSplit = mea.split('/');
            String str = stringSplit[stringSplit.size() - 1];
            if (Pattern.compile( '[a-zA-Z0-9]{15}|[a-zA-Z0-9]{18}' ).matcher(str).matches()){
	            documentInternalIdList.add(str);
            } else {
            	documentExternalList.add(mea); 
            }
        }
        
        //GET BASE64 FOR EXTERNAL IMAGE
        for (String ext : documentExternalList){        
        	HttpRequest req = new HttpRequest();
            req.setEndpoint(ext);
            req.setMethod('GET');
            Http binding = new Http();
            HttpResponse res = binding.send(req);
            Blob image = res.getBodyAsBlob();
            String name = ext.substringAfterLast('/');
            if(String.isNotEmpty(name)){
                if(!name.contains('.')){
                    name=name+'.jpg';
                }
            }else{
                name=contentWr.detailTitle+'.jpg';
            }
            imageMap.put(name, EncodingUtil.base64Encode(image));
        }

        //GET BASE64 FOR IMAGE IN SALESFORCE
        List<ContentVersion> contentVersionList = [SELECT Id, Title, FileExtension, VersionData FROM ContentVersion WHERE ContentDocumentId in : documentInternalIdList AND IsLatest = true];
        for (ContentVersion contv : contentVersionList){
            imageMap.put(contv.Title + '.' + contv.FileExtension, EncodingUtil.base64Encode(contv.VersionData));
        }

        return imageMap;
    } 
}