src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>BrandContent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <recordTypes>
        <fullName>Brand</fullName>
        <active>true</active>
        <description>Represents the highest level of a Brand tree.</description>
        <label>Brand</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <description>The Category object lets you group the same or different types of object records so you can filter them by topic when searching or browsing</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Datasource__c</fullName>
        <label>Datasource</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ManualAssignment</fullName>
                    <label>Manual Assignment</label>
                </value>
                <value>
                    <fullName>Tags</fullName>
                </value>
                <value>
                    <fullName>Categories</fullName>
                </value>
                <value>
                    <fullName>TagsCategories</fullName>
                    <label>Tags + Categories</label>
                </value>
                <value>
                    <fullName>ParentComponentBehaviour</fullName>
                    <label>Parent Component Behaviour</label>
                </value>
                <value>
                    <fullName>ParentContentTags</fullName>
                    <label>Parent Content Tags</label>
                </value>
                <value>
                    <fullName>ParentContentCategories</fullName>
                    <label>Parent Content Categories</label>
                </value>
                <value>
                    <fullName>ParentContentTagsCategories</fullName>
                    <label>Parent Content Tags + Categories</label>
                </value>
                <value>
                    <fullName>All News</fullName>
                </value>
                <value>
                    <fullName>All Events</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LinkDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Link Detail</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <description>How will be showed the catalog component</description>
        <inlineHelpText>How will be showed the catalog component</inlineHelpText>
        <label>Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Mini</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderBy__c</fullName>
        <label>Order By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CreatedDate ASC</fullName>
                    <default>true</default>
                    <label>Creation Date ASC</label>
                </value>
                <value>
                    <fullName>CreatedDate DESC</fullName>
                    <label>Creation Date DESC</label>
                </value>
                <value>
                    <fullName>Name ASC</fullName>
                </value>
                <value>
                    <fullName>Name DESC</fullName>
                </value>
                <value>
                    <fullName>Category__r.Name ASC</fullName>
                    <label>Category ASC</label>
                </value>
                <value>
                    <fullName>Category__r.Name DESC</fullName>
                    <label>Category DESC</label>
                </value>
                <value>
                    <fullName>PublishStartDate__c ASC</fullName>
                    <label>Publish Start Date ASC</label>
                </value>
                <value>
                    <fullName>PublishStartDate__c DESC</fullName>
                    <label>Publish Start Date DESC</label>
                </value>
                <value>
                    <fullName>EventStartDate__c ASC</fullName>
                    <label>Event Start Date ASC</label>
                </value>
                <value>
                    <fullName>EventStartDate__c DESC</fullName>
                    <label>Event Start Date DESC</label>
                </value>
                <value>
                    <fullName>ListTitle__c ASC</fullName>
                    <label>List Title ASC</label>
                </value>
                <value>
                    <fullName>ListTitle__c DESC</fullName>
                    <label>List Title DESC</label>
                </value>
                <value>
                    <fullName>Custom Sorting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PageSize__c</fullName>
        <label>Page Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShowDisplayMode__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Show Display Mode on the catalog view</description>
        <inlineHelpText>Show Display Mode on the catalog view</inlineHelpText>
        <label>Show Display Mode</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowFilters__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Show Filters on the catalog view</description>
        <inlineHelpText>Show Filters on the catalog view</inlineHelpText>
        <label>Show Filters</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowOrder__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Show Order on the catalog view</description>
        <inlineHelpText>Show Order on the catalog view</inlineHelpText>
        <label>Show Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowSearch__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Show Search on the catalog view</description>
        <inlineHelpText>Show Search on the catalog view</inlineHelpText>
        <label>Show Search</label>
        <type>Checkbox</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LinkDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Link Detail</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>BrandDetail</fullName>
        <active>true</active>
        <description>Configure a new Brand Detail content. This content will display a a brand detail including all it related brands. The data this type of content allows are Media elements</description>
        <label>Brand Detail</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MediaElement__c.object
<CustomObject>
    <description>Represents the repository of media elements that can be assigned to multiple contents.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Media Element</label>
    <nameField>
        <label>Media Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media elements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MediaElementAssignment__c.object
<CustomObject>
    <description>Holds the relationship between each media element and the Contents it is beeing used on. This relationship can also be categorized</description>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>MediaElementAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Media Element Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Media Element Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Element Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tag__c.object
<CustomObject>
    <description>Short phrase or word to be used as a search criteria or joint criteria between different objects (Ex. Joint between Content and Components)</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TagAssignment__c.object
<CustomObject>
    <description>The way to assign tags to Content or to Components</description>
    <fields>
        <fullName>Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tag_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Tag Assignment</label>
    <nameField>
        <displayFormat>TAS-{000000000}</displayFormat>
        <label>Tag Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tag Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CG_ContentCatalogController.cls
public with sharing class CG_ContentCatalogController {
	
	//WRAPPERS
    public class CatalogWrapper{
        @auraEnabled public Component__c component;
        @auraEnabled public Boolean isMini;
        @auraEnabled public Boolean withFilters;
		@auraEnabled public List<ContentSearchWrapper> allContentSearchWrapper;
		@auraEnabled public List<ContentWrapper> contentWrapper;
        @auraEnabled public List<String> brands;
		@auraEnabled public List<String> tags;
		@auraEnabled public List<String> categories;
	}

    public class ContentSearchWrapper{
        @auraEnabled public String contentId;
        @auraEnabled public String searchWords;
        @auraEnabled public String brand;
        @auraEnabled public String tags;
        @auraEnabled public String category;
    }

    public class ContentWrapper{
        @auraEnabled public Content__c content;
        @auraEnabled public String documentId;
        @auraEnabled public String mediaElementImageURL;
        @auraEnabled public Brand__c brand;
        @auraEnabled public String brandURL;
        @auraEnabled public String behavior;
    }

    public class QueryContentWrapper {
    	private ContentSearchWrapper csw;
    	private ContentWrapper cw;
    	private QueryContentWrapper(){
    		this.csw = new ContentSearchWrapper();
    	}
    }

    //CatalogWrapper
    @auraEnabled
	public static CatalogWrapper getCatalogWrapper(String componentExternalId, String asset, String search, String brand, String tag, String category, String orderBy){
		//Query Component
		Component__c component = [SELECT Id, Mode__c, PageSize__c, OrderBy__c, LinkDetail__c, Datasource__c, ShowFilters__c, ShowDisplayMode__c, ShowOrder__c, ShowSearch__c, CatalogContentType__c, RecordType.DeveloperName
									 FROM Component__c
									 WHERE ExternalId__c =: componentExternalId];

		//Armo el wrapper de retorno
		CatalogWrapper catalogWrapper = new CatalogWrapper();
		catalogWrapper.component = new Component__c(
			
			Id = component.Id,
			PageSize__c = component.PageSize__c, 
			ShowFilters__c = component.ShowFilters__c,
			ShowDisplayMode__c = component.ShowDisplayMode__c,
			ShowOrder__c = component.ShowOrder__c,
			ShowSearch__c = component.ShowSearch__c,
			LinkDetail__c = component.LinkDetail__c,
			Datasource__c = component.Datasource__c,
			CatalogContentType__c = component.CatalogContentType__c,
			OrderBy__c = component.OrderBy__c
		);

		catalogWrapper.isMini = component.Mode__c == 'Mini';
		catalogWrapper.withFilters = component.ShowFilters__c && component.ShowDisplayMode__c && component.ShowOrder__c && component.ShowSearch__c;
		catalogWrapper.allContentSearchWrapper = new List<ContentSearchWrapper>();
		catalogWrapper.contentWrapper = new List<ContentWrapper>();
		catalogWrapper.brands = new List<String>();
		catalogWrapper.categories = new List<String>();
		catalogWrapper.tags = new List<String>();
		
		//Order By
		if(component.OrderBy__c != null){
			orderBy = component.OrderBy__c;
		}

		//Filtro Asset type
		String cTypes = component.CatalogContentType__c;
		set<String> typesToSearch = new set<String>();
		if(cTypes != null){
			if(cTypes.contains('Logo')){typesToSearch.add('Logo');}
			if(cTypes.contains('Social Media')){typesToSearch.add('Social Media');}
			if(cTypes.contains('Videos')){typesToSearch.add('Videos');}
			if(cTypes.contains('Occasion')){typesToSearch.add('Occasion');}
		}

		set<Id> setContentIds = new set<Id>();
		if(component.Datasource__c == 'Brands' || component.Datasource__c == 'Brand Variants'){
            
			//Filtro : Brands
			List<Brand__c> brandobj = [SELECT BrandContent__c, BrandContent__r.ListTitle__c FROM Brand__c WHERE BrandContent__c != NULL];
			set<String> setBrands = new set<String>();
			for(Brand__c c2 : brandobj){
				setContentIds.add(c2.BrandContent__c);
				if(!setBrands.contains(c2.BrandContent__c)){
					setBrands.add(c2.BrandContent__c);
					catalogWrapper.brands.add(c2.BrandContent__r.ListTitle__c);
				}	
			}

			//Filtro: content
			List<Content__c> contentForCategories = [SELECT Id, Category__c, Category__r.Name FROM Content__c WHERE RecordType.DeveloperName = 'BrandDetail' AND Category__c != NULL];
			set<String> setCategories = new set<String>();
			for(Content__c c: contentForCategories){
				setContentIds.add(c.Id);
				if(!setCategories.contains(c.Category__c)){
					setCategories.add(c.Category__c);
					catalogWrapper.categories.add(c.Category__r.Name);
				}
			}

			//Filtro: tags
			List<TagAssignment__c> contentTags = [SELECT Id, Tag__r.Name FROM TagAssignment__c WHERE Content__r.RecordType.DeveloperName  = 'BrandDetail'];
			set<String> setTags = new set<String>();
			for(TagAssignment__c c : contentTags){
				setTags.add(c.Tag__r.Name);
				catalogWrapper.tags.add(c.Tag__r.Name);
			}

		}

		Integer brandTotal = CatalogWrapper.brands.size();
		//Query Content
		if(component.Mode__c == 'Mini'){
			for(QueryContentWrapper qcw: getContentWrapper(setContentIds, orderBy, Integer.valueOf(component.PageSize__c), true, Integer.valueOf(component.PageSize__c))){
				
				//Data used for search(Filter side panel)
				catalogWrapper.allContentSearchWrapper.add(qcw.csw);	
				
				//Elements shown as cards/Lines
				if(qcw.cw != null){catalogWrapper.contentWrapper.add(qcw.cw);}
			}
		}
		if(component.Mode__c == 'Full'){
			for(QueryContentWrapper qcw: getContentWrapper(setContentIds, orderBy, Integer.valueOf(component.PageSize__c), true, brandTotal)){
			
				catalogWrapper.allContentSearchWrapper.add(qcw.csw);	
	
				if(qcw.cw != null){catalogWrapper.contentWrapper.add(qcw.cw);}
			}	
		}
	
		return catalogWrapper;
	}

	@auraEnabled
	public static List<ContentWrapper> getNextContent(List<String> contentIds, String orderBy){
		List<ContentWrapper> wrapper = new List<ContentWrapper>();
		
		set<Id> setContentIds = new set<Id>();
		for(String i: contentIds){
			setContentIds.add(i);
		}

		for(QueryContentWrapper qcw: getContentWrapper(setContentIds, orderBy, contentIds.size(), false, setContentIds.size())){
			wrapper.add(qcw.cw);
		}		
		return wrapper;
	}
    
	public static List<QueryContentWrapper> getContentWrapper(set<Id> setContentIds, String orderBy, Integer contentWrapperQuantity, Boolean getSearchWrapper, Integer queryLimit){
		List<QueryContentWrapper> wrapper = new List<QueryContentWrapper>();

		//Display Brands
		String queryContent = '';
		queryContent += 'SELECT Id, Name, ListTitle__c, Category__r.Name, Category__c, RecordType.DeveloperName, Description__c, LinkDetail__r.URL__c ';
		queryContent += 'FROM Content__c ';
		queryContent += 'WHERE Id IN: setContentIds AND ListTitle__c != \'' + '' + '\' ';
		queryContent += 'ORDER BY ' + orderBy ;
		queryContent += '\' '+ queryLimit != null ? (' LIMIT ' + String.ValueOf(queryLimit)) : ''; 	

		//Search Properties	
		for(Content__c content: Database.query(queryContent)){
			QueryContentWrapper qcw = new QueryContentWrapper();
			if(getSearchWrapper){
				qcw.csw = new ContentSearchWrapper();
				qcw.csw.contentId = content.Id;
		        qcw.csw.searchWords = content.ListTitle__c;
		        qcw.csw.brand = content.ListTitle__c;
		        qcw.csw.category = content.Category__r.Name;
		        qcw.csw.tags = '';
		        for(TagAssignment__c c : [SELECT Tag__r.Name FROM TagAssignment__c WHERE Content__r.RecordType.DeveloperName  = 'BrandDetail' AND Content__r.Name =: content.Name]){
		        	qcw.csw.tags += c.Tag__r.Name + ';';
		        }
	    	}

	    	//Content
			if(contentWrapperQuantity > 0){
				qcw.cw = new ContentWrapper(); 
                List<Brand__c> brandsOnly = [SELECT Id, RecordTypeId, Name, BrandContent__c, Description__c FROM Brand__c WHERE BrandContent__c =: content.Id];	
                for(Brand__c b : brandsOnly){
            		qcw.cw.brand = new Brand__c(Id = b.Id, Name = b.Name, BrandContent__c = b.BrandContent__c, RecordTypeId = b.RecordTypeId);	
            		qcw.cw.content = new Content__c(Id = content.Id, Description__c = content.Description__c, ListTitle__c = content.ListTitle__c);
                    qcw.cw.brandURL = content.LinkDetail__r.URL__c;
                }
                // Load mediaElement images 
                List<MediaElementAssignment__c> med = [SELECT Id, MediaElement__r.FileURLDesktop__c, MediaElement__r.ExternalId__c FROM MediaElementAssignment__c WHERE Content__c =: content.Id];
                if(!med.isEmpty()){
                    qcw.cw.mediaElementImageURL = med[0].MediaElement__r.FileURLDesktop__c;
                    qcw.cw.documentId = med[0].MediaElement__r.ExternalId__c;
                }  
			}
			wrapper.add(qcw);
		}
		return wrapper;
	}
}