src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>BrandContent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MasterBrand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>BrandVariants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <recordTypes>
        <fullName>Brand</fullName>
        <active>true</active>
        <description>Represents the highest level of a Brand tree.</description>
        <label>Brand</label>
    </recordTypes>
    <recordTypes>
        <fullName>BrandVariant</fullName>
        <active>true</active>
        <description>Represents a grouping brand of other grouping brands or brand leafs.</description>
        <label>Brand Variant</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MediaElement__c.object
<CustomObject>
    <description>Represents the repository of media elements that can be assigned to multiple contents.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Describes the media element stating things such as what can you see in a photograph (Ex. Child feeding a dog)</description>
        <label>Description</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FileURLDesktop__c</fullName>
        <description>Stores the URL of the desktop file related to the media element.</description>
        <inlineHelpText>Stores the URL of the desktop file related to the media element.</inlineHelpText>
        <label>File URL Desktop</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Media Element</label>
    <nameField>
        <label>Media Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media elements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MediaElementAssignment__c.object
<CustomObject>
    <description>Holds the relationship between each media element and the Contents it is beeing used on. This relationship can also be categorized</description>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>MediaElementAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MediaElement__c</fullName>
        <label>Media Element</label>
        <referenceTo>MediaElement__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <label>Placement</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Media Element Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Media Element Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Element Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CG_BrandDetailControllerTest.cls
@isTest
public class CG_BrandDetailControllerTest {

	@testSetup
	static void testSetup(){
		MockupFactory.generateAcceleratorSetting();
		Cluster__c cluster = MockupFactory.createCluster('ClusterTest', null, 1, 'ClusterRoot', 'CRT')[0];
		Brand__c brandMaster = MockupFactory.createBrand('TestBrandMaster', 1, cluster.Id)[0];
		Brand__c brandVariant = MockupFactory.createBrand('TestBrandVariant', 1, cluster.Id)[0];
		Component__c component = MockupFactory.createComponent('Brand Detail', 1)[0];
		Content__c content = MockupFactory.createContent('Brand Detail', cluster, 1)[0];
        MediaElement__c mediaElement = MockupFactory.createMediaElement(1)[0];
        MediaElementAssignment__c mediaElementAssignment = MockupFactory.createMediaElementAssignment(new List<Content__c>{content}, new List<MediaElement__c>{mediaElement})[0]; 

        RecordType rt1 = [SELECT Id FROM RecordType WHERE Name = 'Brand'];
        brandMaster.RecordTypeId = rt1.Id;
        brandMaster.BrandContent__c = content.Id;
        update brandMaster;        
        RecordType rt2 = [SELECT Id FROM RecordType WHERE Name = 'Brand Variant'];
        brandVariant.RecordTypeId = rt2.Id;
        brandVariant.MasterBrand__c = brandMaster.Id;
        brandVariant.BrandContent__c = content.Id;
        update brandVariant;
        content.Description__c = 'DescriptionTest';
        content.Title__c = 'TitleTest';
        update content;
		mediaElement.FileURLDesktop__c = 'FileURLDesktopTest';
		update mediaElement;
		mediaElementAssignment.Placement__c = 'BrandImageBanner';
		update mediaElementAssignment;
	}

	@isTest
	static void getBrandWrapperBrand(){

		// Given
		Brand__c brand = [SELECT Id FROM Brand__c WHERE RecordType.Name = 'Brand' LIMIT 1];
		Brand__c variant = [SELECT Id FROM Brand__c WHERE RecordType.Name = 'Brand Variant' LIMIT 1];
        Component__c component = [SELECT Id, ExternalId__c FROM Component__c LIMIT 1];
        
        // When
        Test.startTest();
		CG_BrandDetailController.BrandDetailWrapper wrapper = CG_BrandDetailController.getBrandWrapper(brand.Id, component.ExternalId__c);
        Test.stopTest();

		// Then
		System.assertEquals('DescriptionTest', wrapper.description);
		System.assertEquals(null, wrapper.title);
		System.assertEquals('FileURLDesktopTest', wrapper.imageBannerURL);
		System.assertEquals(null, wrapper.imageLogoURL);
		System.assertEquals(false, wrapper.isVariant);
		System.assertEquals('TitleTest', wrapper.variants[0].title);
		System.assertEquals('FileURLDesktopTest', wrapper.variants[0].imageURL);
		System.assertEquals(variant.Id, wrapper.variants[0].Id);
	}

	@isTest
	static void getBrandWrapperBrandVariant(){

		// Given
		Brand__c brand = [SELECT Id FROM Brand__c WHERE RecordType.Name = 'Brand Variant' LIMIT 1];
        Component__c component = [SELECT Id, ExternalId__c FROM Component__c LIMIT 1];
        
        // When
        Test.startTest();
		CG_BrandDetailController.BrandDetailWrapper wrapper = CG_BrandDetailController.getBrandWrapper(brand.Id, component.ExternalId__c);
        Test.stopTest();

		// Then
		System.assertEquals('DescriptionTest', wrapper.description);
		System.assertEquals('TitleTest', wrapper.title);
		System.assertEquals(true, wrapper.isVariant);
	}

}