src/objects/Category__c.object
<CustomObject>
    <description>The Category object lets you group the same or different types of object records so you can filter them by topic when searching or browsing</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Determine which cluster is associated with the category.</description>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Manage the status of the record.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                    <label>Initial</label>
                </value>
                <value>
                    <fullName>Set Format</fullName>
                </value>
                <value>
                    <fullName>Set Content</fullName>
                </value>
                <value>
                    <fullName>Final Check</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Set Community</fullName>
                    <isActive>false</isActive>
                    <label>Set Community</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner component. Each banner component has a given aspect ratio and orientation for its presentation. It also has a given behavior for presenting its content such as carousel or appear-disappear effect.</description>
        <label>Banner</label>
    </recordTypes>
    <recordTypes>
        <fullName>News</fullName>
        <active>true</active>
        <description>Configure a new News component. Each News component acts as a placeholder for one or more News</description>
        <label>News</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Manage the status of the record.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner content. This content will scroll or appear-fade inside a Banner. The data this type of content allows are Media elements</description>
        <label>Banner</label>
    </recordTypes>
    <recordTypes>
        <fullName>News</fullName>
        <active>true</active>
        <description>Configure a new News content. This content will be shown inside a News. The data this type of content allows are Media elements and News metadata such as title, news description, etc.</description>
        <label>News</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tag__c.object
<CustomObject>
    <description>Short phrase or word to be used as a search criteria or joint criteria between different objects (Ex. Joint between Content and Components)</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Tags</relationshipLabel>
        <relationshipName>Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TagAssignment__c.object
<CustomObject>
    <description>The way to assign tags to Content or to Components</description>
    <fields>
        <fullName>Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tag_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tag</label>
        <referenceTo>Tag__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>TagAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tag Assignment</label>
    <nameField>
        <displayFormat>TAS-{000000000}</displayFormat>
        <label>Tag Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tag Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Inactive</fullName>
        <default>true</default>
        <label>Inactive</label>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <description>Manage the status of the record.</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

src/classes/ContentLandingRecordListControllerTest.cls
@isTest
public class ContentLandingRecordListControllerTest {

	@isTest
	public static void testDefaultCondition(){
		
		//Given
		MockupFactory.generateAcceleratorSetting();
		Cluster__c clusterTest = MockupFactory.createCluster('ClusterTest', null, 1, 'ClusterRoot')[0];
		Content__c bannerTest = MockupFactory.createContent('Banner', clusterTest, 1)[0];
		Content__c newsTest = MockupFactory.createContent('News', clusterTest, 1)[0];

		//When
		ContentLandingRecordListController.TableWrapper tableWrapperTest = ContentLandingRecordListController.buildTableWrapper(null, null, null, null, null, null);

		//Then
		System.assertEquals(2, tableWrapperTest.contentWrappers.size());
	}

	@isTest
	public static void testCustomCondition(){
		
		//Given
		MockupFactory.generateAcceleratorSetting();
		Cluster__c clusterTest = MockupFactory.createCluster('ClusterTest', null, 1, 'ClusterRoot')[0];
		List<Content__c> contents = MockupFactory.createContent('Banner', clusterTest, 2);
		Content__c bannerTest1 = contents[0];
		Content__c bannerTest2 = contents[1];
        String bannerRecordTypeId = bannerTest1.RecordTypeId;
		Category__c categoryTest = MockupFactory.createCategory('CategoryTest', 1, clusterTest.Id)[0];
		Tag__c TagTest1 = MockupFactory.createTag('TagTest1', 'DescriptionTest', 1, clusterTest.Id)[0];
		Tag__c TagTest2 = MockupFactory.createTag('TagTest2', 'DescriptionTest', 1, clusterTest.Id)[0];
		Component__c componentTest = MockupFactory.createComponent('Banner', 1)[0];
		bannerTest1.Category__c = categoryTest.Id; bannerTest1.Status__c = 'Draft'; update bannerTest1;
		bannerTest2.Category__c = categoryTest.Id; bannerTest1.Status__c = 'Draft'; update bannerTest2;
		insert new TagAssignment__c(Component__c = componentTest.Id, Content__c = bannerTest1.Id, Tag__c = TagTest1.Id);
		insert new TagAssignment__c(Component__c = componentTest.Id, Content__c = bannerTest1.Id, Tag__c = TagTest2.Id);
		insert new TagAssignment__c(Component__c = componentTest.Id, Content__c = bannerTest2.Id, Tag__c = TagTest2.Id);

		//When
		ContentLandingRecordListController.TableWrapper tableWrapperTest = ContentLandingRecordListController.buildTableWrapper(bannerRecordTypeId, clusterTest.Id, categoryTest.Id, new List<String>{TagTest1.Id, TagTest2.Id}, 'Draft', null);

		//Then
		System.assertEquals(1, tableWrapperTest.contentWrappers.size());
		System.assertEquals('Banner 0', tableWrapperTest.contentWrappers[0].fieldWrappers[1].value);
	}

	@isTest
	public static void testSearch(){

		//Given
		MockupFactory.generateAcceleratorSetting();
		Cluster__c clusterTest = MockupFactory.createCluster('ClusterTest', null, 1, 'ClusterRoot')[0];
		Content__c bannerTest = MockupFactory.createContent('Banner', clusterTest, 1)[0]; bannerTest.Status__c = 'Draft'; 
		Content__c newsTest = MockupFactory.createContent('News', clusterTest, 1)[0]; newsTest.Status__c = 'Draft';

		//When
		ContentLandingRecordListController.TableWrapper tableWrapperTest = ContentLandingRecordListController.buildTableWrapper(null, null, null, null, null, 'Banner');
		
		//Then
		System.assertEquals(1, tableWrapperTest.contentWrappers.size());		
		System.assertEquals('Banner 0', tableWrapperTest.contentWrappers[0].fieldWrappers[1].value);
	}

	@isTest
	public static void testEmpty(){

		//Given
		MockupFactory.generateAcceleratorSetting();
		Cluster__c clusterTest = MockupFactory.createCluster('ClusterTest', null, 1, 'ClusterRoot')[0];
		Content__c bannerTest = MockupFactory.createContent('Banner', clusterTest, 1)[0]; bannerTest.Status__c = 'Draft'; 
		Content__c newsTest = MockupFactory.createContent('News', clusterTest, 1)[0]; newsTest.Status__c = 'Draft';

		//When
		ContentLandingRecordListController.TableWrapper tableWrapperTest = ContentLandingRecordListController.buildTableWrapper(null, null, null, null, null, 'String Inexistente');
		
		//Then	
		System.assertEquals(True, tableWrapperTest.title.contains('No records'));
	}

	@isTest
	public static void testJSON(){

		//Given
		MockupFactory.generateAcceleratorSetting();
		Cluster__c clusterTest = MockupFactory.createCluster('ClusterTest', null, 1, 'ClusterRoot')[0];
		Content__c bannerTest = MockupFactory.createContent('Banner', clusterTest, 1)[0]; bannerTest.Status__c = 'Draft'; 
		Content__c newsTest = MockupFactory.createContent('News', clusterTest, 1)[0]; newsTest.Status__c = 'Draft';

		//When
		ContentLandingRecordListController.TableWrapper tableWrapperTest1 = ContentLandingRecordListController.buildTableWrapper(null, null, null, null, null, null);
		String tableWrapperJSON = ContentLandingRecordListController.getTableWrapper(null, null, null, null, null, null);
		ContentLandingRecordListController.TableWrapper tableWrapperTest2 = (ContentLandingRecordListController.TableWrapper) JSON.deserialize(tableWrapperJSON, ContentLandingRecordListController.TableWrapper.class);

		//Then
		System.debug(tableWrapperTest1.contentWrappers +' '+ tableWrapperTest2.contentWrappers);
		System.assertEquals(True, tableWrapperTest1.title == tableWrapperTest2.title);
		System.assertEquals(True, tableWrapperTest1.columnSet == tableWrapperTest2.columnSet);
	}
}