src/objects/Category__c.object
<CustomObject>
    <description>The Category object lets you group the same or different types of object records so you can filter them by topic when searching or browsing</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Determine which cluster is associated with the category.</description>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Child Categories</relationshipLabel>
        <relationshipName>ChildCategories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TreePreviewControllerTest.cls
@isTest(seeAllData = false)
public with sharing class TreePreviewControllerTest {
	
	@isTest
	static void getTreeTest() {
		/* Comment: Comprueba el arbol de categorias devuelve como root la categoría sin ParentCategory__c. */

		//Given
		MockupFactory.generateAcceleratorSetting();

		String name = 'Argentina';
        String nameGroup = 'Buenos Aires';
        List<Cluster__c> clusterRootList = MockupFactory.createCluster(name, null, 1, 'ClusterRoot', 'CRT');
        Cluster__c cg = clusterRootList[0];
        List<Category__c> catList = MockupFactory.createCategory(nameGroup, 8, cg.Id);
        Category__c rootCat = catList[0];
        catList[1].ParentCategory__c = catList[0].Id;
        catList[2].ParentCategory__c = catList[1].Id;
        catList[3].ParentCategory__c = catList[2].Id;
        catList[4].ParentCategory__c = catList[3].Id;
        catList[5].ParentCategory__c = catList[4].Id;
        catList[6].ParentCategory__c = catList[5].Id;
        catList[7].ParentCategory__c = catList[5].Id;

        update catList;

		//When
		Test.startTest();
			TreePreviewController.ItemWrapper wrap = TreePreviewController.getTree(catList[5].Id, 'Category__c', 'ParentCategory__c');
		Test.stopTest();

		//Then
	
		System.assertEquals(wrap.Id, rootCat.Id);		
	}
}