src/objects/Category__c.object
<CustomObject>
    <description>The Category object lets you group the same or different types of object records so you can filter them by topic when searching or browsing</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Determine which cluster is associated with the category.</description>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CategoryAssignment__c.object
<CustomObject>
    <description>Handles the relationship between each Category and different object records (Community Components at this moment)</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Category Assignments</relationshipLabel>
        <relationshipName>CategoryAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Category Assignments</relationshipLabel>
        <relationshipName>CategoryAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Category Assignment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Category Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Datasource__c</fullName>
        <label>Datasource</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ManualAssignment</fullName>
                    <label>Manual Assignment</label>
                </value>
                <value>
                    <fullName>Tags</fullName>
                </value>
                <value>
                    <fullName>Categories</fullName>
                </value>
                <value>
                    <fullName>TagsCategories</fullName>
                    <label>Tags + Categories</label>
                </value>
                <value>
                    <fullName>ParentComponentBehaviour</fullName>
                    <label>Parent Component Behaviour</label>
                </value>
                <value>
                    <fullName>ParentContentTags</fullName>
                    <label>Parent Content Tags</label>
                </value>
                <value>
                    <fullName>ParentContentCategories</fullName>
                    <label>Parent Content Categories</label>
                </value>
                <value>
                    <fullName>ParentContentTagsCategories</fullName>
                    <label>Parent Content Tags + Categories</label>
                </value>
                <value>
                    <fullName>All News</fullName>
                </value>
                <value>
                    <fullName>All Events</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExcludePastEvents__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude Past Events</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>AdvanceContent</fullName>
        <active>true</active>
        <description>Configure a new Advance Content component. Each Advance Content component act as a rich text who give you freedom to work for example with HTML code.</description>
        <label>Advance Content</label>
    </recordTypes>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Configure a new Event component. Each event will have related information such as event date, event place, event maximum allowance, etc.</description>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>EventDetail</fullName>
        <active>true</active>
        <description>Configure a new Event Detail component. This component show event information such as event date, event place, event maximum allowance, etc.</description>
        <label>Events Detail</label>
    </recordTypes>
    <recordTypes>
        <fullName>News</fullName>
        <active>true</active>
        <description>Configure a new News component. Each News component acts as a placeholder for one or more News</description>
        <label>News</label>
    </recordTypes>
    <recordTypes>
        <fullName>NewsDetail</fullName>
        <active>true</active>
        <description>Configure a new News Detail component. This component show News information such as Main image, Title, Description, etc.</description>
        <label>News Detail</label>
    </recordTypes>
    <recordTypes>
        <fullName>RelatedEvents</fullName>
        <active>true</active>
        <description>Configure a new Related Events component. Each Related Events component acts as a placeholder for one or more Related Events</description>
        <label>Related Events</label>
    </recordTypes>
    <recordTypes>
        <fullName>RelatedNews</fullName>
        <active>true</active>
        <description>Configure a new Related News component. Each Related News component acts as a placeholder for one or more Related News</description>
        <label>Related News</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventEndDate__c</fullName>
        <label>Event End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>AdvanceContent</fullName>
        <active>true</active>
        <description>Configure a new Advance Content.</description>
        <label>Advance Content</label>
    </recordTypes>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Configure a new Event content. This content will be shown inside an Event. The data this type of content allows are Media elements and Event metadata such as event date, event capacity, etc.</description>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>News</fullName>
        <active>true</active>
        <description>Configure a new News content. This content will be shown inside a News. The data this type of content allows are Media elements and News metadata such as title, news description, etc.</description>
        <label>News</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContentAssignment__c.object
<CustomObject>
    <description>Manages the direct assignment of Content to Components</description>
    <fields>
        <fullName>Component__c</fullName>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipName>ComponentContentAssignment</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipName>ComponentContentAssignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content Assignment</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Content Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MediaElement__c.object
<CustomObject>
    <description>Represents the repository of media elements that can be assigned to multiple contents.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Media Element</label>
    <nameField>
        <label>Media Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media elements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MediaElementAssignment__c.object
<CustomObject>
    <description>Holds the relationship between each media element and the Contents it is beeing used on. This relationship can also be categorized</description>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>MediaElementAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MediaElement__c</fullName>
        <label>Media Element</label>
        <referenceTo>MediaElement__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Media Element Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Media Element Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Element Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tag__c.object
<CustomObject>
    <description>Short phrase or word to be used as a search criteria or joint criteria between different objects (Ex. Joint between Content and Components)</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Tags</relationshipLabel>
        <relationshipName>Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TagAssignment__c.object
<CustomObject>
    <description>The way to assign tags to Content or to Components</description>
    <fields>
        <fullName>Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tag_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Tag Assignment</label>
    <nameField>
        <displayFormat>TAS-{000000000}</displayFormat>
        <label>Tag Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tag Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ContentUtils.cls
public without sharing virtual class ContentUtils {

	public class ContentWrapper{
        public set<String> setAllContentIds;
        public Integer totalPages;
        public List<ContentDataWrapper> contentDataPage;
    }
    
    public class ContentDataWrapper{
        public Content__c content;
        public List<MediaElement__c> mediaElements;
    }

    public static ContentWrapper getContentFromComponent(Component__c component, set<String> fieldSet, set<String> setContentDirect, set<String> setContentToExclude, set<String> setClusterIds, String device){
        system.debug('ContentUtils: component: ' + component);
        system.debug('ContentUtils: fieldSet: ' + fieldSet);
        system.debug('ContentUtils: setContentDirect: ' + setContentDirect);
        system.debug('ContentUtils: setContentToExclude: ' + setContentToExclude);
        system.debug('ContentUtils: setClusterIds: ' + setClusterIds);
        system.debug('ContentUtils: device: ' + device);

        set<Id> setContentIds = new set<Id>();
        set<Id> setCategoriesIds = new set<Id>();

        if(setContentToExclude == null){setContentToExclude = new set<String>();}

        //Armado del query principal a objeto Content
        String query = '';

        //SELECT
        query += 'SELECT ' + GeneralUtils.joinFields(fieldSet) + ', (SELECT Id, MediaElement__c FROM MediaElementAssignments__r) ';

        //FROM
        query += 'FROM Content__c ';

        //WHERE
        String contentTypeToSearch = getRecordTypeContentFromRTComponent(component.RecordType.DeveloperName);

        if(setContentDirect != null){
            //Busqueda de contenido por parametro
            query += 'WHERE (Id IN: setContentDirect OR ExternalId__c IN: setContentDirect) AND Recordtype.DeveloperName =: contentTypeToSearch ';
        }else{
            if(component.Datasource__c != null){
                //Busqueda de contenido por Datasource
                if(component.Datasource__c.contains('ParentContent')){
                    if(!setContentToExclude.isEmpty()){
                        Content__c parentContent = [SELECT Id, Category__c FROM Content__c WHERE (Id IN: setContentToExclude OR ExternalId__c IN: setContentToExclude) LIMIT 1];
                        if(component.Datasource__c.contains('Categories') && parentContent.Category__c != null){
                            setCategoriesIds.add(parentContent.Category__c);
                        }
                        if(component.Datasource__c.contains('Tags')){
                            setContentIds.addAll(getContentIdsByTags(parentContent.Id, contentTypeToSearch));
                        }
                    }
                }else{
                    if(component.Datasource__c.contains('ManualAssignment')){
                        setContentIds.addAll(getContentIdsByAssignment(component.Id));
                    }
                    if(component.Datasource__c.contains('Categories')){
                        setCategoriesIds.addAll(getContentIdsByCategories(component.Id));
                    }
                    if(component.Datasource__c.contains('Tags')){
                        setContentIds.addAll(getContentIdsByTags(component.Id, contentTypeToSearch));
                    }
                }
            }

            if(component.Datasource__c != null && (component.Datasource__c == 'All News' || component.Datasource__c == 'All Events') ){
                query += 'WHERE Id NOT IN: setContentToExclude AND ExternalId__c NOT IN: setContentToExclude AND Cluster__c IN: setClusterIds AND Recordtype.DeveloperName =: contentTypeToSearch ';
            }else{
                query += 'WHERE (Id IN: setContentIds OR Category__c IN: setCategoriesIds) AND (Id NOT IN: setContentToExclude) AND (ExternalId__c NOT IN: setContentToExclude) AND Cluster__c IN: setClusterIds AND Recordtype.DeveloperName =: contentTypeToSearch ';
            }

            if(component.Recordtype.Developername == 'Event' || component.Recordtype.DeveloperName == 'RelatedEvent'){
                if (component.ExcludePastEvents__c){
                    Datetime dateAndTime = System.today();
                    query += 'AND (EventEndDate__c >: dateAndTime) ';
                }
            }
        }

        //ORDER
        if((component.OrderBy__c != null && component.OrderBy__c != 'Custom Sorting') || (component.OrderBy__c != null && component.OrderBy__c == 'Custom Sorting' && component.OrderByAdvance__c != null) ){
            query += 'ORDER BY ' + (component.OrderBy__c == 'Custom Sorting' ? component.OrderByAdvance__c : component.OrderBy__c);
        }
        query = query.replace('ORDER BY', 'ORDER BY Cluster__r.ClusterLevel__c ASC, ');
        
        ContentWrapper cw = new ContentWrapper();
        map<Id, Content__c> mapContent = new map<Id, Content__c>((List<Content__c>)Database.query(query));
        
        if(!mapContent.isEmpty()){
        	//TODO: Aca tenemos que aplicar segmentacion y se tiene que cambiar como manejamos las paginas y el total de las paginas
            
            //Si despues de aplicar segmentacion tenemos algun registro evaluamos las paginas
            if(!mapContent.isEmpty()){

                //Seteo todos los Ids posibles para despues hacer el query de paginas
                cw.setAllContentIds = (Set<String>)JSON.deserialize(JSON.serialize(mapContent.keySet()), Set<String>.class);

                //Calculo el total de paginas
                cw.totalPages = component.PageSize__c != null ? Integer.valueOf((mapContent.size() / component.PageSize__c).round(RoundingMode.UP)) : 1;
	            //Content Data Wrapper
	            List<Content__c> firstPage = new List<Content__c>();
	            if(component.PageSize__c == null){
	            	firstPage = mapContent.values();
	            }else{
                    Decimal limitSize = component.PageSize__c < mapContent.values().size() ? component.PageSize__c : mapContent.values().size();
	            	for(Integer i = 0; i < limitSize; i++){
	            		firstPage.add(mapContent.values()[i]);
		            }
	            }
                //Translate content records
                TranslationUtils.getTranslated(firstPage, UserInfo.getLanguage(), 'Content__c');

                //Replace User information on Advance Content
                if(component.Recordtype.DeveloperName == 'AdvanceContent'){
                    replaceDynamicFieldsOnContent(firstPage);
                }

	            cw.contentDataPage = createContentDataWrappers(firstPage);
            }
        }

        return cw;
    }

    public static List<ContentDataWrapper> getContentPage(set<String> setAllContentIds, set<String> fieldSet, Integer page, Integer pageSize, String orderBy, String device){
        String query = '';
        query += 'SELECT ' + GeneralUtils.joinFields(fieldSet) + ', (SELECT Id, MediaElement__c FROM MediaElementAssignments__r) ';
        query += 'FROM Content__c ';
        query += 'WHERE Id IN: setAllContentIds ';
        query += 'ORDER BY ' + orderBy + ' ';
        query = query.replace('ORDER BY', 'ORDER BY Cluster__r.ClusterLevel__c ASC, ');
        query += 'LIMIT ' + pageSize + ' ';

        Decimal offSet = (page-1) * pageSize;

        query += 'OFFSET ' + offSet;
        
        List<Content__c> listContentPage = Database.query(query);

        //Translate content records
        TranslationUtils.getTranslated(listContentPage, UserInfo.getLanguage(), 'Content__c');

        List<ContentDataWrapper> contentDataPage = createContentDataWrappers(listContentPage);
        return contentDataPage;
    }
    
    private static set<Id> getContentIdsByAssignment(Id componentId){
        set<Id> setContentIds = new set<Id>();
        for(ContentAssignment__c ca: [SELECT Id, Content__c FROM ContentAssignment__c WHERE Component__c =: componentId]){
            setContentIds.add(ca.Content__c);
        }
        return setContentIds;
    }

    private static set<Id> getContentIdsByCategories(Id parentId){
        set<Id> setCategoriesIds = new set<Id>();
        for(CategoryAssignment__c ca: [SELECT Id, Category__c FROM CategoryAssignment__c WHERE Component__c =: parentId]){
            setCategoriesIds.add(ca.Category__c);
        }
        return setCategoriesIds;
    }

    private static set<Id> getContentIdsByTags(Id parentId, String contentTypeToSearch){
        set<Id> setTagIds = new set<Id>();
        for(TagAssignment__c ta: [SELECT Id, Tag__c FROM TagAssignment__c WHERE Component__c =: parentId OR Content__c =: parentId]){
            setTagIds.add(ta.Tag__c);
        }

        set<Id> setContentIds = new set<Id>();
        for(TagAssignment__c ta: [SELECT Id, Content__c FROM TagAssignment__c WHERE Tag__c IN: setTagIds AND Content__r.RecordType.Developername =: contentTypeToSearch]){
            setContentIds.add(ta.Content__c);
        }

        return setContentIds;
    }

    private static List<ContentDataWrapper> createContentDataWrappers(List<Content__c> contents){
        List<ContentDataWrapper> listCDW = new List<ContentDataWrapper>();

        set<Id> setMediaElementIds = new set<Id>();
        for(Content__c c: contents){
            for(MediaElementAssignment__c m: c.MediaElementAssignments__r){
                setMediaElementIds.add(m.MediaElement__c);
            }
        }

        map<Id, MediaElement__c> mapMediaElements;
        if(!setMediaElementIds.isEmpty()){
            mapMediaElements = new map<Id, MediaElement__c>([SELECT Id, Name, FileURLDesktop__c FROM MediaElement__c WHERE Id IN: setMediaElementIds]);
        }

        for(Content__c c: contents){
            ContentDataWrapper cdw = new ContentDataWrapper();
            cdw.content = c;
            cdw.mediaElements = new List<MediaElement__c>();
            for(MediaElementAssignment__c m: c.MediaElementAssignments__r){
                if(mapMediaElements != null && mapMediaElements.containsKey(m.MediaElement__c)){
                    cdw.mediaElements.add(mapMediaElements.get(m.MediaElement__c));
                }
            }
            listCDW.add(cdw);
        }

        return listCDW;
    }

    private static String getRecordTypeContentFromRTComponent(String componentRT){
        String contentTypeToSearch;
        if (componentRT == 'RelatedNews' || componentRT == 'NewsDetail') {
            contentTypeToSearch = 'News';
        }else if (componentRT == 'RelatedEvents' || componentRT == 'EventDetail') {
            contentTypeToSearch = 'Event';
        }else{
            contentTypeToSearch = componentRT;
        }
        return contentTypeToSearch;
    }

    private static void replaceDynamicFieldsOnContent(List<Content__c> contentList){
        for(Content__c con: contentList){
            con.HTMLContent__c = GeneralUtils.replaceDynamicFields(con.HTMLContent__c, 'User', UserInfo.getUserId(), false);
        }
    }
    
}