src/objects/Category__c.object
<CustomObject>
    <description>The Category object lets you group the same or different types of object records so you can filter them by topic when searching or browsing</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>RelatedNews</fullName>
        <active>true</active>
        <description>Configure a new Related News component. Each Related News component acts as a placeholder for one or more Related News</description>
        <label>Related News</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CG_BaseComponentControllerTest.cls
@isTest(seeAllData = false)
public with sharing class CG_BaseComponentControllerTest {
	@isTest 
	static void getComponentWrapperTest(){
		/* Comment: Comprueba que dado un String correspondiente al ExternalId__c de un Component__c el método getComponentWrapper
		de la clase CG_BaseComponentController retorne el Component__c correspondiente. */

		/*
		//Given
		MockupFactory.createRecords();

		//When
		Test.startTest();
			CG_BaseComponentController.ComponentWrapper cwTest= CG_BaseComponentController.getComponentWrapper('BannerComponent_1', 'RelatedNews', null, null, 'Desktop');
		Test.stopTest();

		//Then
		
		System.assertEquals(cwTest.component.ExternalId__c, 'BannerComponent_1');
		*/
	}

	@isTest 
	static void getPageTest(){
		/* Comment: Comprueba que al crear un Category__c se inserta
			con el correspondiente ExternalId__c */

		//Given
		//MockupFactory.createRecords();
		Category__c categoryTest = new Category__c(Name='Category Test 01');
		List<String> stringIDList= new List<String>();
		for(Content__c content : [select Id from Content__c where ExternalId__c like'BannerContent%']){
			stringIDList.add(content.Id);
		} 

		//When
		Test.startTest();
			List<CG_BaseComponentController.ContentWrapper> cwTest= CG_BaseComponentController.getPage(stringIDList, 'RelatedNews', '1', '1', 'Name', 'Desktop');
		Test.stopTest();

		//Then
		
		System.assertNotEquals(cwTest, null);
	}	
}