src/objects/Category__c.object
<CustomObject>
    <description>The Category object lets you group the same or different types of object records so you can filter them by topic when searching or browsing</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CategoryAssignment__c.object
<CustomObject>
    <description>Handles the relationship between each Category and different object records (Community Components at this moment)</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Category Assignments</relationshipLabel>
        <relationshipName>CategoryAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Category Assignments</relationshipLabel>
        <relationshipName>CategoryAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Category Assignment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Category Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Datasource__c</fullName>
        <label>Datasource</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ManualAssignment</fullName>
                    <label>Manual Assignment</label>
                </value>
                <value>
                    <fullName>Tags</fullName>
                </value>
                <value>
                    <fullName>Categories</fullName>
                </value>
                <value>
                    <fullName>TagsCategories</fullName>
                    <label>Tags + Categories</label>
                </value>
                <value>
                    <fullName>ParentComponentBehaviour</fullName>
                    <label>Parent Component Behaviour</label>
                </value>
                <value>
                    <fullName>ParentContentTags</fullName>
                    <label>Parent Content Tags</label>
                </value>
                <value>
                    <fullName>ParentContentCategories</fullName>
                    <label>Parent Content Categories</label>
                </value>
                <value>
                    <fullName>ParentContentTagsCategories</fullName>
                    <label>Parent Content Tags + Categories</label>
                </value>
                <value>
                    <fullName>All News</fullName>
                </value>
                <value>
                    <fullName>All Events</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tag__c.object
<CustomObject>
    <description>Short phrase or word to be used as a search criteria or joint criteria between different objects (Ex. Joint between Content and Components)</description>
    <label>Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TagAssignment__c.object
<CustomObject>
    <description>The way to assign tags to Content or to Components</description>
    <fields>
        <fullName>Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tag_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tag</label>
        <referenceTo>Tag__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>TagAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tag Assignment</label>
    <nameField>
        <displayFormat>TAS-{000000000}</displayFormat>
        <label>Tag Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tag Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ComponentBehaviourController.cls
public class ComponentBehaviourController {

    @auraEnabled
    public static String getComponentBehaviour(String contentId){
        Content__c content = [SELECT Id, RecordTypeId, StructureComponent__c FROM Content__c WHERE Id =: contentId];
        String componentId = content.StructureComponent__c;
        return componentId != null ? getBehaviourMessage(componentId) : null;  
    }

    private static String getBehaviourMessage(String componentId){
        //Get DataSource
        Component__c component = [SELECT Id, dataSource__c, TagCriteria__c FROM Component__c WHERE Id =: componentId];
        String dataSource = component.dataSource__c;
        //Get records related to DataSource
        String behaviourMessage;
        if(dataSource == 'ManualAssignment'){
            behaviourMessage = Label.ComponentBehaviourManualAssignment;
        }
        if(dataSource == 'Tags'){
            behaviourMessage = getTagsMessage(component);
        }
        if(dataSource == 'Categories'){
            behaviourMessage = getCategoriesMessage(component);
        }
        if(dataSource == 'TagsCategories'){            
            behaviourMessage = getTagsMessage(component) + '\n\n';
            behaviourMessage += getCategoriesMessage(component);
        }
        // Build Message
        return behaviourMessage;
    }

    private static String getTagsMessage(Component__c component){
        String behaviourMessage;
        behaviourMessage = Label.ComponentBehaviourTags + '\n';
        List<TagAssignment__c> tagAssignments = [SELECT Id, Tag__c, Tag__r.Name, Order__c FROM TagAssignment__c WHERE Component__c =: component.Id ORDER BY Order__c ASC];
        for(TagAssignment__c tagAssignment : tagAssignments){
            behaviourMessage += '\n' + tagAssignment.Order__c + '. ' + tagAssignment.Tag__r.Name;
        }
        behaviourMessage += '\n\n Tag criteria: ' + component.TagCriteria__c;
        return behaviourMessage;
    }

    private static String getCategoriesMessage(Component__c component){
        String behaviourMessage;
        behaviourMessage = Label.ComponentBehaviourCategories + '\n';
        List<CategoryAssignment__c> categoryAssignments = [SELECT Id, Category__c, Category__r.Name FROM CategoryAssignment__c WHERE Component__c =: component.Id];
        for(CategoryAssignment__c categoryAssignment : categoryAssignments){
            behaviourMessage += '\n - ' + categoryAssignment.Category__r.Name;
        }
        return behaviourMessage;
    }

}