src/objects/Category__c.object
<CustomObject>
    <description>The Category object lets you group the same or different types of object records so you can filter them by topic when searching or browsing</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CategoryAssignment__c.object
<CustomObject>
    <description>Handles the relationship between each Category and different object records (Community Components at this moment)</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Category Assignments</relationshipLabel>
        <relationshipName>CategoryAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Category Assignments</relationshipLabel>
        <relationshipName>CategoryAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Category Assignment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Category Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CategoryAssignmentTriggersTest.cls
@isTest(seeAllData = false)
public class CategoryAssignmentTriggersTest {
	
	@isTest 
	static void insertCategoryAssignmentTest(){
		/* Comment: Comprueba que al crear un CategoryAssignment__c se inserta
			con el correspondiente ExternalId__c */

		//Given
		//MockupFactory.createRecords();
		Category__c categoryTest = new Category__c(Name='Test');
		insert categoryTest;

		Component__c compTest = [select id, Name, ExternalId__c from Component__c limit 1];

		CategoryAssignment__c catAssigmentTest = new CategoryAssignment__c(Component__c = compTest.id, Category__c=categoryTest.id );

		//When
		Test.startTest();
			insert(catAssigmentTest);
		Test.stopTest();

		//Then
		CategoryAssignment__c catAssigmentTestResult =[select id, ExternalId__c from CategoryAssignment__c where id =: catAssigmentTest.id];
		System.assertNotEquals(catAssigmentTestResult.ExternalId__c, null);

	}

	@isTest 
	static void updateCategoryAssignmentTest(){
		/* Comment: Comprueba que al actualizar un CategoryAssignment__c se inserta
			con el correspondiente ExternalId__c */

		//Given
		//MockupFactory.createRecords();
		Category__c categoryTest = new Category__c(Name='Test');
		insert categoryTest;

		Component__c compTest = [select id, Name, ExternalId__c from Component__c limit 1];

		CategoryAssignment__c catAssigmentTest = new CategoryAssignment__c(Component__c = compTest.id, Category__c=categoryTest.id );
		insert(catAssigmentTest);
		catAssigmentTest.ExternalId__c = null;

		//When
		Test.startTest();
			update(catAssigmentTest);
		Test.stopTest();

		//Then
		CategoryAssignment__c catTestResult2 =[select id, ExternalId__c from CategoryAssignment__c where id =: catAssigmentTest.id];
		System.assertNotEquals(catTestResult2.ExternalId__c, null);
	}
}