src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>CommunityName__c</fullName>
        <label>Community Name</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterGroup</fullName>
        <active>true</active>
        <description>Represents a grouping cluster of other grouping clusters or cluster leafs. (Ex.: EMEA, Africa, Latam).</description>
        <label>Cluster Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterLeaf</fullName>
        <active>true</active>
        <description>Represents the lowest level of the clustering tree. Community users will be related to this cluster level. (Ex.: Argentina Consumers)</description>
        <label>Cluster Leaf</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ClusterUser__c.object
<CustomObject>
    <description>Determines which users have access to the cluster, the access type (Read Only or Read/Write), it&apos;s child clusters and the configuration below the cluster (ex.: Content, Components, Tags, etc.).</description>
    <fields>
        <fullName>AccessLevel__c</fullName>
        <label>Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read Only Down</fullName>
                </value>
                <value>
                    <fullName>Read/Write</fullName>
                </value>
                <value>
                    <fullName>Read All ORG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipName>ClusterGovernance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ClusterUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cluster User</label>
    <nameField>
        <displayFormat>CU-{00000}</displayFormat>
        <label>Cluster User #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Menu__c.object
<CustomObject>
    <description>Represents menu options than can be related to other menu options.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Menus</relationshipLabel>
        <relationshipName>Menus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Navigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Navigation</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Cluster__c</field>
                <operation>equals</operation>
                <valueField>Navigation__c.Cluster__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Menus</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentMenu__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Menu</label>
        <referenceTo>Menu__c</referenceTo>
        <relationshipLabel>ParentMenus</relationshipLabel>
        <relationshipName>SubMenus</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Menu</label>
    <nameField>
        <label>Menu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menus</pluralLabel>
    <recordTypes>
        <fullName>Menu</fullName>
        <active>true</active>
        <description>Represents the highest level of a Menu tree. It can be asociated to a component. (Ex. File)</description>
        <label>Menu</label>
    </recordTypes>
    <recordTypes>
        <fullName>SubMenu</fullName>
        <active>true</active>
        <description>Represents a grouping menu of other grouping menus or menu leafs. (Ex. New, Open, Save)</description>
        <label>SubMenu</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ContentLandingStructureControllerTest.cls
@isTest
public class ContentLandingStructureControllerTest {

	@testSetup
    static void setup(){
    	Network net = [SELECT Id, Name FROM Network LIMIT 1];
        MockupFactory.generateAcceleratorSetting();
        List<Cluster__c> clusterRoot = MockupFactory.createCluster('CRootTest', null, 1, 'ClusterRoot', 'CRT');
        clusterRoot[0].CommunityName__c = net.Name;
        update clusterRoot;
        List<Cluster__c> clustersLevel2 = MockupFactory.createCluster('CL2Test', clusterRoot.get(0).Id, 2, 'ClusterGroup', 'CGT');
        Set<Id> level2Ids = (new Map<Id, SObject>(clustersLevel2)).keySet();
        List<Cluster__c> clustersLevel3 = MockupFactory.createCluster('CL3Test', new List<Id>(level2Ids), 2, 'ClusterGroup', 'es', '', 'CG2');
        Set<Id> level3Ids = (new Map<Id, SObject>(clustersLevel3)).keySet();
        List<Cluster__c> clustersLeaf = MockupFactory.createCluster('CLeafTest', new List<Id>(level3Ids), 2, 'ClusterLeaf', 'es', '', 'CLT');

        List<Navigation__c> navs = MockupFactory.createNavigation('testNav', 'testUrl', 3, clusterRoot.get(0).Id);
        for(Navigation__c n : navs)
        	n.Type__c = 'Internal';
        update navs;

        Menu__c mainMenu = MockupFactory.createMenu('mainMenu', 1, clusterRoot.get(0).Id)[0]; 
        mainMenu.RecordTypeId = Schema.SObjectType.Menu__c.getRecordTypeInfosByDeveloperName().get('Menu').getRecordTypeId();
    	mainMenu.Navigation__c = navs.get(0).Id;
    	update mainMenu;
       	
       	Menu__c subMenu1 = MockupFactory.createMenu('subMenu1', 1, clusterRoot.get(0).Id)[0]; 
        subMenu1.RecordTypeId = Schema.SObjectType.Menu__c.getRecordTypeInfosByDeveloperName().get('SubMenu').getRecordTypeId();
        subMenu1.ParentMenu__c = mainMenu.Id; 
        subMenu1.Navigation__c = navs.get(1).Id;
        update subMenu1;

        Menu__c subMenu2 = MockupFactory.createMenu('subMenu2', 1, clusterRoot.get(0).Id)[0]; 
        subMenu2.RecordTypeId = Schema.SObjectType.Menu__c.getRecordTypeInfosByDeveloperName().get('SubMenu').getRecordTypeId();
        subMenu2.ParentMenu__c = mainMenu.Id;
        subMenu2.Navigation__c = navs.get(2).Id;
        update subMenu2;

        List<user> userForTesting = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        ClusterUser__c cu = new ClusterUser__c(Cluster__c=clusterRoot.get(0).Id, AccessLevel__c = 'Read/Write', User__c = userForTesting.get(0).Id);
        insert cu;
    }

    @isTest
    public static void getMenus(){
    	ContentLandingStructureController.getMenus();
    }

    @isTest
    public static void getGeneralData(){
        List<user> userForTesting = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
    	system.runAs(userForTesting[0]) {
            try{
                ContentLandingStructureController.getGeneralData();
            } catch (AuraException e){
                System.assert(e.getMessage() == 'The site does not exist' || e.getMessage() == 'The community does not exist', 'error');
            }
    	}
    }

    @isTest
    public static void getSiteId(){
    	List<Cluster__c> clRoot = [SELECT Id FROM Cluster__c WHERE RecordType.DeveloperName = 'ClusterRoot'];
        try{
            ContentLandingStructureController.getSiteId(clRoot.get(0).Id);
        } catch (AuraException e){
            System.assertEquals('The site does not exist', e.getMessage(), 'error');
        }
    }

}