src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LookupInputControllerTest.cls
@isTest
public class LookupInputControllerTest {

    @testSetup
    static void setupTest(){
		MockupFactory.generateAcceleratorSetting();
        List<Cluster__c> clusterRoot = MockupFactory.createCluster('Cluster Root', '', 1, 'ClusterRoot', 'CRT');
        MockupFactory.createNavigation('testNav', 'testUrl', 2, clusterRoot.get(0).Id);
    }

    @isTest 
	static void fetchLookUpValuesTest() {
		//When
        String searchKeyword = 'testNav';
        String objectApiName = 'Navigation__c';
		//Given
		List<sObject> listObject = LookupInputController.fetchLookUpValues(searchKeyword, objectApiName);
		//Then
		System.assertEquals(listObject.size(), 2);
	}
    @isTest 
	static void getInitialValueTest() {
		//When
        Navigation__c nav = [SELECT id FROM Navigation__c LIMIT 1];
        String recordId = nav.id;
        String objectApiName = 'Navigation__c';
		//Given
		sObject obj = LookupInputController.getInitialValue(recordId, objectApiName);
		//Then
		system.assertEquals(((Navigation__c)obj).name, 'testNav0');
	}

    

}