src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ClusterLandingUrl__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>URL to redirect</description>
        <label>Landing URL</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CommunityName__c</fullName>
        <label>Community Name</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MappingClusterField__c</fullName>
        <defaultValue>&quot;DefaultLanguage__c&quot;</defaultValue>
        <description>Represents the field in the Cluster that will be use to match with the &quot;Mapping Object Field&quot;. By default is the Default Language field.</description>
        <inlineHelpText>Represents the field in the Cluster that will be use to match with the &quot;Mapping Object Field&quot;. By default is the Default Language field.</inlineHelpText>
        <label>Mapping Cluster Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MappingObjectField__c</fullName>
        <defaultValue>&quot;LanguageLocaleKey&quot;</defaultValue>
        <description>Represents the field within the object defined in &quot;Mapping Object&quot; that will be use to match with the &quot;Mapping Cluster Field&quot;. By default is the Language field in the User object.</description>
        <inlineHelpText>Represents the field within the object defined in &quot;Mapping Object&quot; that will be use to match with the Cluster &quot;Mapping Value&quot;. By default is the Language field in the User object.</inlineHelpText>
        <label>Mapping Object Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MappingObject__c</fullName>
        <description>Represents the object that will determine the cluster leaf to be used in the community. By default is the User object but it can be extended to other objects.</description>
        <inlineHelpText>Represents the object that will determine the cluster leaf to be used in the community. By default is the User object but it can be extended to other objects.</inlineHelpText>
        <label>Mapping Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                    <default>true</default>
                    <label>User</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ParentCluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Cluster</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>- Parent Cluster record can only be of Group or Root type.
- Cluster Root cannot have a Parent Cluster.</errorMessage>
            <filterItems>
                <field>Cluster__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Cluster Group, Cluster Root</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Cluster Root</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Related Clusters</relationshipLabel>
        <relationshipName>RelatedClusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterLeaf</fullName>
        <active>true</active>
        <description>Represents the lowest level of the clustering tree. Community users will be related to this cluster level. (Ex.: Argentina Consumers)</description>
        <label>Cluster Leaf</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ClusterUtils.cls
public with sharing class ClusterUtils {

	public class ClusterWrapper {
		public Cluster__c cluster;
		public List<ClusterWrapper> relatedClusters;
		public ClusterWrapper(Cluster__c p_cluster){
			this.cluster = p_cluster;
			this.relatedClusters = new List<ClusterWrapper>();
		}
		//Esto es una modificacion para probar una historia
	}

	public static map<String, set<String>> mapClustersParents;
	public static set<String> getClustersParents(String clusterId) {
		if(mapClustersParents == null){
			mapClustersParents = new map<String, set<String>>();
		}

		if(!mapClustersParents.containsKey(clusterId)){
			mapClustersParents.put(clusterId, new set<String>{clusterId});
			
			List<Cluster__c> queryResult = [SELECT Id, ParentCluster__c, ParentCluster__r.ParentCluster__c, ParentCluster__r.ParentCluster__r.ParentCluster__c FROM Cluster__c WHERE Id =: clusterId];
			if(!queryResult.isEmpty()){
				Cluster__c cluster = queryResult[0];
				//The accelerator allows only 4 levels of depth of Clusters
				if(cluster.ParentCluster__c != null){
					mapClustersParents.get(clusterId).add(cluster.ParentCluster__c);
					if(cluster.ParentCluster__r.ParentCluster__c != null){
						mapClustersParents.get(clusterId).add(cluster.ParentCluster__r.ParentCluster__c);
						if(cluster.ParentCluster__r.ParentCluster__r.ParentCluster__c != null){
							mapClustersParents.get(clusterId).add(cluster.ParentCluster__r.ParentCluster__r.ParentCluster__c);
						}
					}
				}
			}
		}

		return mapClustersParents.get(clusterId);
	}
	
	public static map<String, ClusterWrapper> mapClustersBelow;
	public static ClusterWrapper getClustersBelow(String clusterId) {
		if(mapClustersBelow == null){
			mapClustersBelow = new map<String, ClusterWrapper>();
		}

		if(!mapClustersBelow.containsKey(clusterId)){
			Cluster__c cluster = [SELECT Id, Name, ParentCluster__c, ClusterLandingUrl__c, RecordType.DeveloperName FROM Cluster__c WHERE Id =: clusterId];
			
			mapClustersBelow.put(cluster.Id, new ClusterWrapper(cluster));
			
			//The accelerator allows only 4 levels of depth of Clusters
			set<Id> setClusterRelated = new set<Id>{cluster.Id};
			while(!setClusterRelated.isEmpty()){
				List<Cluster__c> clustersRelated = [SELECT Id, Name, ParentCluster__c, ClusterLandingUrl__c, RecordType.DeveloperName FROM Cluster__c WHERE ParentCluster__c IN: setClusterRelated];
				setClusterRelated.clear();
				for(Cluster__c rc: clustersRelated){
					setClusterRelated.add(rc.Id);
					ClusterWrapper crr = new ClusterWrapper(rc);
					mapClustersBelow.put(rc.Id, crr);
					mapClustersBelow.get(rc.ParentCluster__c).relatedClusters.add(crr);
				}
			}
		}

		return mapClustersBelow.get(clusterId);
	}

	public static map<String, String> mapMappingKeyCluster;
	public static String getClusterIdFromMappingObject(String recordId, String networkId){
		if(mapMappingKeyCluster == null){
			mapMappingKeyCluster = new map<String, String>();
		}
		
		String mappingKey = recordId + '-' + networkId;
		if(!mapMappingKeyCluster.containsKey(mappingKey)){
			try{
				List<Cluster__c> clusterRoot = [SELECT Id, MappingObject__c, MappingObjectField__c, MappingClusterField__c FROM Cluster__c WHERE RecordType.DeveloperName = 'ClusterRoot' AND CommunityName__c =: GeneralUtils.getNetwork(networkId).Name];
				if(!clusterRoot.isEmpty()){
					List<SObject> rec = Database.query('SELECT Id, ' + clusterRoot[0].MappingObjectField__c + ' FROM ' + clusterRoot[0].MappingObject__c + ' WHERE Id =: recordId');
					if(!rec.isEmpty()){
						List<Cluster__c> clusterRet = Database.query('SELECT Id FROM Cluster__c WHERE RecordType.DeveloperName = \'ClusterLeaf\' AND ' + clusterRoot[0].MappingClusterField__c + ' = \'' + GeneralUtils.getFieldValue(rec[0], clusterRoot[0].MappingObjectField__c) + '\' LIMIT 1');
						if(!clusterRet.isEmpty()){
							mapMappingKeyCluster.put(mappingKey, clusterRet[0].Id);
						}
					}
				}
			}catch(Exception e){}
		}

		return mapMappingKeyCluster.get(mappingKey);
	}

	public static Cluster__c getClusterRootFromNetwork(){
		Cluster__c clusterRoot;
		if (Network.getNetworkId() != null ){
			List<Cluster__c> queryResult = [SELECT Id, MappingObject__c, MappingObjectField__c, MappingClusterField__c, ClusterLandingUrl__c, RecordType.DeveloperName FROM Cluster__c WHERE RecordType.DeveloperName = 'ClusterRoot' AND CommunityName__c =: GeneralUtils.getNetwork(Network.getNetworkId()).Name];
			if(!queryResult.isEmpty()){
				clusterRoot = queryResult[0];
			}
			return clusterRoot;
		}
		return null;
	}
}