src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Configure a new Event content. This content will be shown inside an Event. The data this type of content allows are Media elements and Event metadata such as event date, event capacity, etc.</description>
        <label>Event</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MediaElement__c.object
<CustomObject>
    <description>Represents the repository of media elements that can be assigned to multiple contents.</description>
    <fields>
        <fullName>FileURLDesktop__c</fullName>
        <description>Stores the URL of the desktop file related to the media element.</description>
        <inlineHelpText>Stores the URL of the desktop file related to the media element.</inlineHelpText>
        <label>File URL Desktop</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Media Element</label>
    <nameField>
        <label>Media Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media elements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MediaElementAssignment__c.object
<CustomObject>
    <description>Holds the relationship between each media element and the Contents it is beeing used on. This relationship can also be categorized</description>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>MediaElementAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MediaElement__c</fullName>
        <label>Media Element</label>
        <referenceTo>MediaElement__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <label>Placement</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Media Element Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Media Element Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Element Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MediaElementsManagerControllerTest.cls
@isTest
public class MediaElementsManagerControllerTest {
	@testSetup 
	static void setup(){
		// Given in all cases
		MockupFactory.generateAcceleratorSetting();
		MockupFactory.createCluster('global', null, 1, 'ClusterRoot', 'CRT');
	}
	@isTest 
	static void PA181_CASE_1(){
		// Comment: Se busca mediante un string, con una lista de places separados por coma, los media elements asignados al contenido que esten en el string

		// Given
		Cluster__c cluster = [SELECT id FROM Cluster__c LIMIT 1];
		List<Content__c> content = MockupFactory.createContent('Event', cluster, 1);
		List<MediaElement__c> medElement = MockupFactory.createMediaElement(1);

		insert new MediaElementAssignment__c (MediaElement__c = medElement[0].id, Content__c = content[0].id , Placement__c = 'icon');
		insert new MediaElementAssignment__c (MediaElement__c = medElement[0].id, Content__c = content[0].id , Placement__c = 'small');
		insert new MediaElementAssignment__c (MediaElement__c = medElement[0].id, Content__c = content[0].id , Placement__c = 'big');
		// When
		Test.startTest();
		list<MediaElementsManagerController.RecordsWrapper> rw = MediaElementsManagerController.getRecord(content[0].id, 'icon, big', 'Content__c', 'MediaElementAssignment__c');
		Test.stopTest();
		// Then
		System.assertEquals(2 ,rw.size());

	}
	@isTest 
	static void PA181_CASE_2(){
		// Comment:Se buscan todos los media elements sin filtro ni paginado

		// Given
		List<MediaElement__c> medElement = MockupFactory.createMediaElement(3);
		// When
		Test.startTest();
		list<MediaElementsManagerController.ContentWrapper> searchedList = MediaElementsManagerController.getData('0', '', '5', 'false');
		Test.stopTest();
		// Then
		System.assertEquals(searchedList.size(), medElement.size());
	}	
	@isTest 
	static void PA181_CASE_3(){
		// Comment: Se buscan todos los media elements que cumplan con un filtro, sin paginado

		// Given
		List<MediaElement__c> medElement = MockupFactory.createMediaElement(11);
		// When
		Test.startTest();
		list<MediaElementsManagerController.ContentWrapper> searchedList = MediaElementsManagerController.getData('0', '0', '15', 'false');
		Test.stopTest();
		// Then
		System.assertEquals( 2, searchedList.size());
	}
	@isTest 
	static void PA181_CASE_4(){
		// Comment: Search media element with pagging, without filter

		// Given
		List<ContentDocument> contentDocument = MockupFactory.createContentDocument('TestCD', 1);
		List<MediaElement__c> medElement = MockupFactory.createMediaElement(11);
		for(Integer i = 0; i < medElement.size(); i++){
			medElement[i].FileURLDesktop__c = 'https://test/' + contentDocument[0].id;
		}
		medElement[0].FileURLDesktop__c = 'https://test/dsdsd.jpg';
		update medElement;

		// When
		Test.startTest();
		list<MediaElementsManagerController.ContentWrapper> searchedList = MediaElementsManagerController.getData('0', '', '6', 'false');
		list<MediaElementsManagerController.ContentWrapper> searchedList2 = MediaElementsManagerController.getData('6', '', '6', 'true');
		Test.stopTest();
		// Then
		System.assertEquals(6, searchedList.size());
		System.assertEquals(2, searchedList2.size());
	}
	@isTest 
	static void PA181_CASE_5(){
		// Comment: Se relaciona un registro de mediaElement con un Content mediante un Junction Object, en este caso MediaElementAssignment

		// Given
		Cluster__c cluster = [SELECT id FROM Cluster__c LIMIT 1];
		List<Content__c> content = MockupFactory.createContent('Event', cluster, 1);
		List<MediaElement__c> medElement = MockupFactory.createMediaElement(1);
		// When
		Test.startTest();
		MediaElementsManagerController.assignMediaElementToId (content[0].Id, 'icon', 'Content__c','MediaElementAssignment__c', medElement[0].Id);
		Test.stopTest();

		List<MediaElementAssignment__c> junctionObjectRecord = [SELECT id, Placement__c FROM MediaElementAssignment__c WHERE Content__c = :content[0].Id AND MediaElement__c = :medElement[0].Id];
		// Then
		System.assertEquals( 1, junctionObjectRecord.size());
		System.assertEquals( 'icon', junctionObjectRecord[0].Placement__c);
	}
	@isTest 
	static void PA181_CASE_6(){
		// Comment: se elimina un registro de un Junction Object mediante un Id y el api name del objeto

		// Given
		Cluster__c cluster = [SELECT id FROM Cluster__c LIMIT 1];
		List<Content__c> content = MockupFactory.createContent('Event', cluster, 1);
		List<MediaElement__c> medElement = MockupFactory.createMediaElement(1);
		MediaElementAssignment__c junctionObjectRecord = new MediaElementAssignment__c (MediaElement__c = medElement[0].id, Content__c = content[0].id , Placement__c = 'icon');
		insert junctionObjectRecord;
		// When
		Test.startTest();
		MediaElementsManagerController.deleteJunctionObject(junctionObjectRecord.Id, 'MediaElementAssignment__c');
		Test.stopTest();
		// Then
		System.assertEquals( 0, [SELECT id FROM MediaElementAssignment__c].size()); 
	}
}