src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterGroup</fullName>
        <active>true</active>
        <description>Represents a grouping cluster of other grouping clusters or cluster leafs. (Ex.: EMEA, Africa, Latam).</description>
        <label>Cluster Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterLeaf</fullName>
        <active>true</active>
        <description>Represents the lowest level of the clustering tree. Community users will be related to this cluster level. (Ex.: Argentina Consumers)</description>
        <label>Cluster Leaf</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner component. Each banner component has a given aspect ratio and orientation for its presentation. It also has a given behavior for presenting its content such as carousel or appear-disappear effect.</description>
        <label>Banner</label>
    </recordTypes>
    <recordTypes>
        <fullName>FAQ</fullName>
        <active>true</active>
        <description>Configure a new FAQ component. A FAQ has one or more related pairs of question-answer which are listed in the order defined by the Content Admin</description>
        <label>FAQ</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner content. This content will scroll or appear-fade inside a Banner. The data this type of content allows are Media elements</description>
        <label>Banner</label>
    </recordTypes>
    <recordTypes>
        <fullName>FAQ</fullName>
        <active>true</active>
        <description>Configure a new FAQ content. This content will be shown inside a FAQ list. The data this type of content allows are Texts for questions and answers</description>
        <label>FAQ</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CreateNewContentModalControllerTest.cls
@isTest
public class CreateNewContentModalControllerTest {

    @testSetup
	static void generateCustomSettings(){
		MockupFactory.generateAcceleratorSetting();
		List<Cluster__c> clusterRoot = MockupFactory.createCluster('Cluster Root', '', 1, 'ClusterRoot', 'CRT');
        List<Cluster__c> clusterGroup = MockupFactory.createCluster('Cluster Group', clusterRoot.get(0).id, 1, 'ClusterGroup', 'CGT');
        List<Cluster__c> clusterLeaf = MockupFactory.createCluster('Cluster Leaf', clusterGroup.get(0).id, 2, 'ClusterLeaf', 'CLT');
        MockupFactory.createComponent('FAQ', 1, clusterRoot.get(0));
    }

    @isTest
    static void getRecordTypeName(){

    	//Given
    	RecordType rt = [SELECT Id FROM RecordType WHERE SobjectType = 'Content__c' AND DeveloperName = 'Banner'];
    	String recordTypeLabel = Schema.SObjectType.Content__c.getRecordTypeInfosById().get(rt.Id).getName();

    	//When
    	String responseLabel = CreateNewContentModalController.getRecordTypeName(rt.Id);

    	//Then
    	system.assertEquals(recordTypeLabel, responseLabel);

    }

    @isTest
    static void createNewContent(){

    	//Given
    	Component__c component = [SELECT id FROM Component__c LIMIT 1];
    	RecordType rt = [SELECT Id FROM RecordType WHERE SobjectType = 'Content__c' AND DeveloperName = 'FAQ'];

    	//When
    	CreateNewContentModalController.SaveResponseWrapper response = CreateNewContentModalController.createNewContent((String) rt.Id, false, (String) component.Id, null, 'Test FAQ');

    	//Then
    	system.assert(response.isSuccess);
    	List<Content__c> content = [SELECT Id, Name FROM Content__c WHERE Name = 'Test FAQ' LIMIT 1];
    	system.assert(!content.isEmpty());

    }

    @isTest
    static void createNewContentFail(){

    	//Given
    	RecordType rt = [SELECT Id FROM RecordType WHERE SobjectType = 'Content__c' AND DeveloperName = 'FAQ'];

    	//When
    	CreateNewContentModalController.SaveResponseWrapper response = CreateNewContentModalController.createNewContent(rt.Id, true, rt.Id, null, 'Test FAQ');

    	//Then
    	system.assert(!response.isSuccess);

    }
    
}