src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Datatable__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipName>ListViews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Datatable</label>
    <nameField>
        <label>Datatable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datatables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DatatableAction__c.object
<CustomObject>
    <fields>
        <fullName>Datatable__c</fullName>
        <label>Datatable</label>
        <referenceTo>Datatable__c</referenceTo>
        <relationshipLabel>Datatable Actions</relationshipLabel>
        <relationshipName>DatatableActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Datatable Action</label>
    <nameField>
        <label>Datatable Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datatable Actions</pluralLabel>
    <recordTypes>
        <fullName>GlobalAction</fullName>
        <active>true</active>
        <label>Global Action</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DatatableActionTriggersTest.cls
@isTest
private class DatatableActionTriggersTest {
    
    @testSetup
    static void generateAcceleratorSetting(){
        MockupFactory.generateAcceleratorSetting();
    }
    
    @isTest
    static void createDatabaseActionWithExternalId() {
        Test.startTest();
        
        List<Cluster__c> clustersRoot = MockUpFactory.createCluster('DummyRootCluster', null, 1, 'ClusterRoot', 'CRT');
        
        Id clusterId = clustersRoot.get(0).Id;
        RecordType rt = [SELECT Id FROM RecordType WHERE SobjectType = 'DatatableAction__c' AND DeveloperName = 'GlobalAction'];
        
        List<Datatable__c> datatables = MockupFactory.createDatatables('DummyDatatable', 'DummyDatatable', 'Account', 1, clusterId);
        
        List<DatatableAction__c> datatableActions = MockupFactory.createDatatableActions('DummyDatatableAction', 'DummyDatatableAction', 2, datatables.get(0).Id, rt.Id);
        
        Test.stopTest();
    }
    
    @isTest
    static void createDatabaseActionWithoutExternalId() {
        Test.startTest();
        
        List<Cluster__c> clustersRoot = MockUpFactory.createCluster('DummyRootCluster', null, 1, 'ClusterRoot', 'CRT');
        
        Id clusterId = clustersRoot.get(0).Id;
        RecordType rt = [SELECT Id FROM RecordType WHERE SobjectType = 'DatatableAction__c' AND DeveloperName = 'GlobalAction'];
        
        List<Datatable__c> datatables = MockupFactory.createDatatables('DummyDatatable', null, 'Account', 1, clusterId);
        
        List<DatatableAction__c> datatableActions = MockupFactory.createDatatableActions('DummyDatatableAction', null, 2, datatables.get(0).Id, rt.Id);
        
        Test.stopTest();      
    }
    
    @isTest
    static void updateDatabaseElementWithExternalId() {
        Test.startTest();
        
        List<Cluster__c> clustersRoot = MockUpFactory.createCluster('DummyRootCluster', null, 1, 'ClusterRoot', 'CRT');
        
        Id clusterId = clustersRoot.get(0).Id;
        RecordType rt = [SELECT Id FROM RecordType WHERE SobjectType = 'DatatableAction__c' AND DeveloperName = 'GlobalAction'];
        
        List<Datatable__c> datatables = MockupFactory.createDatatables('DummyDatatable', 'DummyDatatable', 'Account', 1, clusterId);
        
        List<DatatableAction__c> datatableActions = MockupFactory.createDatatableActions('DummyDatatableAction', 'DummyDatatableAction', 2, datatables.get(0).Id, rt.Id);
        
        DatatableAction__c de = datatableActions.get(0);
        de.Name = 'AnotherDataActionName';
        
        update de;
        
        Test.stopTest();
    }
    
    @isTest
    static void updateDatabaseElementWithoutExternalId() {
        Test.startTest();
        
        List<Cluster__c> clustersRoot = MockUpFactory.createCluster('DummyRootCluster', null, 1, 'ClusterRoot', 'CRT');
        
        Id clusterId = clustersRoot[0].Id;
        RecordType rt = [SELECT Id FROM RecordType WHERE SobjectType = 'DatatableAction__c' AND DeveloperName = 'GlobalAction'];
        
        List<Datatable__c> datatables = MockupFactory.createDatatables('DummyDatatable', null, 'Account', 1, clusterId);
        
        List<DatatableAction__c> datatableActions = MockupFactory.createDatatableActions('DummyDatatableAction', 'DummyDatatableAction', 2, datatables.get(0).Id, rt.Id);
        
        DatatableAction__c de = datatableActions.get(0);
        de.Name = 'AnotherDataActionName';
        
        update de;
        
        Test.stopTest();        
    }
}