src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterLeaf</fullName>
        <active>true</active>
        <description>Represents the lowest level of the clustering tree. Community users will be related to this cluster level. (Ex.: Argentina Consumers)</description>
        <label>Cluster Leaf</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Datatable__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipName>ListViews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ObjectApiName__c</fullName>
        <label>Object Api Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Datatable</label>
    <nameField>
        <label>Datatable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datatables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DatatableTriggersTest.cls
@isTest
private class DatatableTriggersTest {
    
	@testSetup
	static void generateCustomSettings(){
		MockupFactory.generateAcceleratorSetting();
	}
	
    @isTest
    static void createValidDatatable() {
        
        Test.startTest();
        List<Cluster__c> clusters = MockUpFactory.createCluster('DummyCluster', null, 1, 'ClusterRoot');
        
        List<Datatable__c> datatables = MockupFactory.createDatatables('DummyDatatable', 'DummyDatatable', 'Account', 2, clusters.get(0).Id);
        
        System.assert(datatables.size() > 0);
        
        Test.stopTest();
    }
    
    @isTest
    static void updateValidDatatable() {
        
        Test.startTest();
        List<Cluster__c> clustersRoot = MockUpFactory.createCluster('DummyRootCluster', null, 1, 'ClusterRoot');
        List<Cluster__c> clustersLeaf = MockUpFactory.createCluster('DummyLeafCluster', clustersRoot.get(0).Id, 1, 'ClusterLeaf');
        
        Cluster__c leaf = clustersLeaf.get(0);
        
        List<Datatable__c> datatables = MockupFactory.createDatatables('DummyDatatable', 'DummyDatatable', 'Account', 2, leaf.Id);
        
        System.assert(datatables.size() > 0);
        
        Datatable__c a = datatables.get(0);
        a.Name = 'DummyDatatable2';
        a.Cluster__c = clustersRoot.get(0).Id;
        
        update a;
        
        a = datatables.get(0);
        a.Name = 'DummyDatatable2';
        a.Cluster__c = null;
        
        update a;
        
        Test.stopTest();
    }
    
    @isTest
    static void createInvalidDatatable() {
        
        Test.startTest();
        List<Cluster__c> clusters = MockUpFactory.createCluster('DummyCluster', null, 1, 'ClusterRoot');
        List<Datatable__c> datatables = new List<Datatable__c>();
        
        String name = 'DummyDatatable';
        
        Datatable__c datatable = new Datatable__c();
        datatable.Name = name;
        datatable.Cluster__c = clusters.get(0).Id;
        datatable.ExternalId__c = name;
        datatable.ObjectApiName__c = 'DummyObject';
        
        datatables.add(datatable);
        
        List<Database.SaveResult> results = Database.insert(datatables, false);
        
        Boolean hasError = false;
        
        System.assert(!results[0].isSuccess());
        
        Test.stopTest();
    }
}