src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Datatable__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipName>ListViews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Datatable</label>
    <nameField>
        <label>Datatable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datatables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DatatableElement__c.object
<CustomObject>
    <fields>
        <fullName>Datatable__c</fullName>
        <label>Datatable</label>
        <referenceTo>Datatable__c</referenceTo>
        <relationshipLabel>Datatable Elements</relationshipLabel>
        <relationshipName>DatatableElements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Datatable Element</label>
    <nameField>
        <label>Datatable Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datatable Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DatatableElementTriggersTest.cls
@isTest
private class DatatableElementTriggersTest {
    
    @testSetup
    static void generateAcceleratorSetting(){
        MockupFactory.generateAcceleratorSetting();
    }
    
    @isTest
    static void createDatabaseElementWithExternalId() {
        Test.startTest();
        
        List<Cluster__c> clustersRoot = MockUpFactory.createCluster('DummyRootCluster', null, 1, 'ClusterRoot', 'CRT');
        
        Id clusterId = clustersRoot.get(0).Id;
        
        List<Datatable__c> datatables = MockupFactory.createDatatables('DummyDatatable', 'DummyDatatable', 'Account', 1, clusterId);
        
        List<DatatableElement__c> datatableElements = MockupFactory.createDatatableElements('DummyDatatableElement', 'DummyDatatableElement', 2, datatables[0].Id);
        
        Test.stopTest();
    }
    
    @isTest
    static void createDatabaseElementWithoutExternalId() {
        Test.startTest();
        
        List<Cluster__c> clustersRoot = MockUpFactory.createCluster('DummyRootCluster', null, 1, 'ClusterRoot', 'CRT');
        
        Id clusterId = clustersRoot.get(0).Id;
        
        List<Datatable__c> datatables = MockupFactory.createDatatables('DummyDatatable', null, 'Account', 1, clusterId);
        
        List<DatatableElement__c> datatableElements = MockupFactory.createDatatableElements('DummyDatatableElement', null, 2, datatables.get(0).Id);
        
        Test.stopTest();      
    }
    
    @isTest
    static void updateDatabaseElementWithExternalId() {
        Test.startTest();
        
        List<Cluster__c> clustersRoot = MockUpFactory.createCluster('DummyRootCluster', null, 1, 'ClusterRoot', 'CRT');
        
        Id clusterId = clustersRoot.get(0).Id;
        
        List<Datatable__c> datatables = MockupFactory.createDatatables('DummyDatatable', 'DummyDatatable', 'Account', 1, clusterId);
        
        List<DatatableElement__c> datatableElements = MockupFactory.createDatatableElements('DummyDatatableElement', 'DummyDatatableElement', 2, datatables.get(0).Id);
        
        DatatableElement__c de = datatableElements.get(0);
        de.Name = 'AnotherDataElementName';
        
        update de;
        
        Test.stopTest();
    }
    
    @isTest
    static void updateDatabaseElementWithoutExternalId() {
        Test.startTest();
        
        List<Cluster__c> clustersRoot = MockUpFactory.createCluster('DummyRootCluster', null, 1, 'ClusterRoot', 'CRT');
        
        Id clusterId = clustersRoot.get(0).Id;
        
        List<Datatable__c> datatables = MockupFactory.createDatatables('DummyDatatable', null, 'Account', 1, clusterId);
        
        List<DatatableElement__c> datatableElements = MockupFactory.createDatatableElements('DummyDatatableElement', null, 2, datatables.get(0).Id);
        
        DatatableElement__c de = datatableElements.get(0);
        de.Name = 'AnotherDataElementName';
        
        update de;
        
        Test.stopTest();        
    }
}