src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>Recipe</fullName>
        <active>true</active>
        <description>Configure a new Recipe content. This content will be shown inside a Recipe</description>
        <label>Recipe</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Recipe__c.object
<CustomObject>
    <description>Represents the recipes and contains the elements related to them as ingredients, instructions and the relationship with the corresponding brand</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Determine which cluster is associated with the recipe.</description>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Recipes</relationshipLabel>
        <relationshipName>Recipes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Recipes</relationshipLabel>
        <relationshipName>Recipes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Recipe</label>
    <nameField>
        <label>Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RecipeStep__c.object
<CustomObject>
    <description>steps to make in the recipe</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Recipe__c</fullName>
        <description>Represent the recipe</description>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Recipes Steps</relationshipLabel>
        <relationshipName>RecipesSteps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Recipe Step</label>
    <nameField>
        <label>Recipe Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RecipeStepTriggersTest.cls
@isTest
private class RecipeStepTriggersTest {

@testSetup
    static void setupTest(){
    	MockupFactory.generateAcceleratorSetting();
    	String name = 'Argentina';
    	List<Cluster__c> clusterRootList = MockupFactory.createCluster(name, null, 1, 'ClusterRoot', 'CRT');
    	List<Content__c> contentList = MockupFactory.createContent('Recipe', clusterRootList[0], 1);    	
    	List<Recipe__c> recipesList = MockupFactory.createRecipes('RecipeTest',1, contentList[0].id,clusterRootList[0].id); 
    }

	@isTest 
	static void ExternalIdTest() {
		//When
		List<Recipe__c> recipesList = [SELECT id from Recipe__c];
		//Given
		Test.startTest();
		List<RecipeStep__c> stepList = MockupFactory.createRecipeStep('TestStep', 1, recipesList[0].id);
		Test.stopTest();

		//Then
		RecipeStep__c recipeStepTest = [SELECT id, ExternalID__c from RecipeStep__c where id =: stepList[0].Id Limit 1];
		System.assertNotEquals(recipeStepTest.ExternalID__c, null);
	}

	@isTest 
	static void ExternalIdUpdateTest() {
		//When
		List<Recipe__c> recipesList = [SELECT id from Recipe__c];
		List<RecipeStep__c> stepsList = MockupFactory.createRecipeStep('TestStep', 1, recipesList[0].id);

		RecipeStep__c recipeStep = [SELECT id, Name, ExternalID__c from RecipeStep__c where id =: stepsList[0].Id Limit 1];
		recipeStep.ExternalID__c='';
		//Given
		Test.startTest();
		update recipeStep;
		Test.stopTest();

		//Then
		RecipeStep__c recipeStepTest = [SELECT id, Name, ExternalID__c from RecipeStep__c where id =: recipeStep.Id Limit 1];
		System.assertEquals(recipeStepTest.ExternalID__c, recipeStepTest.Name);
	}
}