src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterGroup</fullName>
        <active>true</active>
        <description>Represents a grouping cluster of other grouping clusters or cluster leafs. (Ex.: EMEA, Africa, Latam).</description>
        <label>Cluster Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner content. This content will scroll or appear-fade inside a Banner. The data this type of content allows are Media elements</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContentCartItem__c.object
<CustomObject>
    <description>Represent the content item on the content cart.</description>
    <fields>
        <fullName>Content__c</fullName>
        <description>Master detail to content record</description>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Content Cart Items</relationshipLabel>
        <relationshipName>Content_Cart_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship with the user that add the content to the cart.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Content_Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Content Cart Item</label>
    <nameField>
        <label>Content Cart Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContentCartItemTriggersTest.cls
@isTest
private class ContentCartItemTriggersTest {
	@testSetup
    static void setupTest(){
    	String nameRecordType = 'Banner';
    	Integer quantity = 3;
    	MockupFactory.generateAcceleratorSetting();
        
        String name = 'Argentina';
        List<Cluster__c> clusterRootList = MockupFactory.createCluster(name, null, 1, 'ClusterRoot', 'CRT');
        Cluster__c cg = clusterRootList[0];
        List<Cluster__c> clusterList = MockupFactory.createCluster('Buenos Aires', cg.Id, 1, 'ClusterGroup', 'CGT');
    	List<Content__c> contentList = MockupFactory.createContent(nameRecordType, clusterList[0], quantity);
       
    }

	@isTest 
	static void ExternalIdTest() {
		//When
		

		Content__c content = [SELECT id from Content__c Limit 1];

		ContentCartItem__c item = new ContentCartItem__c(Content__c = content.Id, User__c = UserInfo.getUserId(), Name='Test');

		//Given
		Test.startTest();
		insert item;
		Test.stopTest();

		//Then
		ContentCartItem__c itemTest = [SELECT id, ExternalID__c from ContentCartItem__c Limit 1];
		System.assertNotEquals(itemTest.ExternalID__c, null);
	}

	@isTest 
	static void ExternalIdUpdateTest() {
		//When
		

		Content__c content = [SELECT id from Content__c Limit 1];

		ContentCartItem__c item = new ContentCartItem__c(Content__c = content.Id, User__c = UserInfo.getUserId(), Name='Test');
		insert item;
		item = [SELECT id, ExternalID__c, Name from ContentCartItem__c where Content__c =: content.Id and User__c =: UserInfo.getUserId()  Limit 1];
		item.Name = 'TestUpdate';
		item.ExternalID__c = '';
		//Given
		Test.startTest();
		update item;
		Test.stopTest();

		//Then
		ContentCartItem__c itemTest = [SELECT id, ExternalID__c from ContentCartItem__c where Content__c =: content.Id and User__c =: UserInfo.getUserId()  Limit 1];
		System.assertEquals(itemTest.ExternalID__c, 'TestUpdate');
	}
}