src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ClusterLandingUrl__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>URL to redirect</description>
        <label>Landing URL</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FirstCluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>First Cluster to make a cluster Tree in cluster selector component</description>
        <label>First Cluster to show</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterGroup</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components (First Cluster)</relationshipLabel>
        <relationshipName>Components1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OnlyClusterLeaf__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if checked, the user can only select clusters leaf</description>
        <inlineHelpText>if checked, the user can only select clusters leaf</inlineHelpText>
        <label>Only Leaf clusters are selectable</label>
        <type>Checkbox</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CG_ClusterSelectorControllerTest.cls
@isTest
public with sharing class CG_ClusterSelectorControllerTest {
	
	@isTest 
	static void clusterSelectTest(){
		/* Comment: Comprueba que dado un ExternalId__c trae el cluster correspondiente*/

		//Given

		//MockupFactory.createRecords();

		Cluster__c cluster = [SELECT Id, ExternalId__c, Name FROM Cluster__c WHERE RecordType.DeveloperName='ClusterRoot' and Name like 'Argentina%' LIMIT 1];
		
		Component__c component = [SELECT Id, ExternalId__c, FirstCluster__c, OnlyClusterLeaf__c From Component__c Limit 1];
		component.FirstCluster__c= cluster.Id;
		update component;
		//When
		Test.startTest();
			CG_ClusterSelectorController.TreeWrapper tree =CG_ClusterSelectorController.getClusterRoot(component.ExternalId__c);
		Test.stopTest();
		//Then
		System.assertEquals(tree.label, cluster.Name);
	}

	@isTest 
	static void clusterLandingTest(){
		
		/* Comment: Comprueba que dado un cluster devuelve el url correspondiente*/

		//Given

		//MockupFactory.createRecords();

		Cluster__c cluster = [SELECT Id, ExternalId__c, Name, ClusterLandingUrl__c FROM Cluster__c WHERE RecordType.DeveloperName='ClusterRoot' and Name like 'Argentina%' LIMIT 1];
		
		Component__c component = [SELECT Id, ExternalId__c, FirstCluster__c, OnlyClusterLeaf__c From Component__c Limit 1];
		component.FirstCluster__c= cluster.Id;
		update component;

		Navigation__c nav = new Navigation__c();
		nav.Name = 'test';
		nav.URL__c = 'www.google.com';
		insert nav;

		cluster.ClusterLandingUrl__c = nav.Id;
		
		update cluster; 
		//When
		Test.startTest();
			string url = CG_ClusterSelectorController.getClusterRedirect(cluster.ClusterLandingUrl__c);
		Test.stopTest();
		//Then
		System.assertEquals(url, nav.URL__c);
		
		
	}

	@isTest 
	static void clusterSelectExternalIdNullTest(){
		/* Comment: Comprueba que sin un ExternalId devuelve null*/

		//Given

		//MockupFactory.createRecords();

		Cluster__c cluster = [SELECT Id, ExternalId__c, Name FROM Cluster__c WHERE RecordType.DeveloperName='ClusterRoot' and Name like 'Argentina%' LIMIT 1];
		
		Component__c component = [SELECT Id, ExternalId__c, FirstCluster__c, OnlyClusterLeaf__c From Component__c Limit 1];
		component.FirstCluster__c= cluster.Id;
		update component;
		//When
		Test.startTest();
			CG_ClusterSelectorController.TreeWrapper tree =CG_ClusterSelectorController.getClusterRoot(null);
		Test.stopTest();
		//Then
		System.assertEquals(tree, null);
	}

}