src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>DefaultLanguage__c</fullName>
        <label>Default Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AvailableLanguages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OtherLanguages__c</fullName>
        <description>Languages that Content Admins will be able to translate and community users can select in the community. For Cluster Groups, you need to select all languages defined below the hierarchy.</description>
        <inlineHelpText>Languages that Content Admins will be able to translate and community users can select in the community. For Cluster Groups, you need to select all languages defined below the hierarchy.</inlineHelpText>
        <label>Other Languages</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AvailableLanguages</valueSetName>
        </valueSet>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Translation__c.object
<CustomObject>
    <description>Translates Content or Media elements into a given language</description>
    <fields>
        <fullName>LanguageCode__c</fullName>
        <label>Language Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AvailableLanguages</valueSetName>
        </valueSet>
    </fields>
    <label>Translation</label>
    <nameField>
        <label>Translation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Translations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CG_LanguageSelectorController.cls
public with sharing class CG_LanguageSelectorController {

	//WRAPPER
	public class LanguageWrapper {
		@auraEnabled public String name;
		@auraEnabled public String value;

		public LanguageWrapper(String nam, String val){
			this.name = nam;
			this.value = val;
		}	
	}
	public class MenuWrapper {
		@auraEnabled public Boolean isGuestUser;
        @auraEnabled public LanguageWrapper userLanguage;
        @auraEnabled public List<LanguageWrapper> languages;

        public MenuWrapper(){
			this.languages = new List<LanguageWrapper>();
		}
	}

	@AuraEnabled
    public static MenuWrapper getLanguageMenu(String clusterId){
    	System.debug('getLanguageMenu clusterId: ' + clusterId);
    	Cluster__c cluster = [SELECT Id, DefaultLanguage__c, OtherLanguages__c FROM Cluster__c where Id =: clusterId];

    	Set<String>langs = new Set<String>();
    	langs.add(cluster.DefaultLanguage__c);

    	String[] tmpString = cluster.OtherLanguages__c.split(';');
    	langs.addAll(tmpString);

    	String userLanguage = UserInfo.getLanguage();

    	MenuWrapper wrapper = new MenuWrapper();

		Schema.DescribeSObjectResult sobjectDescribe = Schema.getGlobalDescribe().get('Translation__c').getDescribe();
		for (Schema.PicklistEntry entry : sobjectDescribe.fields.getMap().get('LanguageCode__c').getDescribe().getPickListValues()){
			if(langs.contains(entry.getValue()) && entry.isActive()){	
				LanguageWrapper lang= new LanguageWrapper(entry.getLabel(), entry.getValue());
				wrapper.languages.add(lang);
				if( entry.getValue().equalsIgnoreCase(userLanguage)){
					wrapper.userLanguage=lang;
				}	
				
			}
			
		}
		
		Profile profile =  [SELECT id, Name FROM Profile WHERE id = : UserInfo.getProfileId()];

		wrapper.isGuestUser = (profile.Name == 'Guest');

		return wrapper;
    }

	@AuraEnabled
	public static void setLanguage(String language){
		
		User u = [SELECT id ,LanguageLocaleKey FROM User WHERE id =: UserInfo.getUserId()];

		u.LanguageLocaleKey = language;

		update u;
	}
}