src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SearchDetail__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Search Details</relationshipLabel>
        <relationshipName>Search_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FieldsToSearch__c</fullName>
        <description>Fields in which will be searched the inserted text</description>
        <inlineHelpText>The fields api names separeted by comma</inlineHelpText>
        <label>Fields To Search</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FieldsToShow__c</fullName>
        <description>Fields that will be shown</description>
        <inlineHelpText>Insert the fields api names separeted by comma</inlineHelpText>
        <label>Fields To Show</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ObjectAPIName__c</fullName>
        <description>API name of the Sobject</description>
        <inlineHelpText>Insert the API name of the Salesforce Object</inlineHelpText>
        <label>Object API Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordTypeDevName__c</fullName>
        <inlineHelpText>Insert the record type developer name</inlineHelpText>
        <label>Record Type Dev Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URLParameterField__c</fullName>
        <defaultValue>&apos;Id&apos;</defaultValue>
        <label>URL Parameter Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Search Detail</label>
    <nameField>
        <label>Search Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SearchDetailTriggers.cls
public with sharing class SearchDetailTriggers extends TriggersHandler{
    private Boolean hasError = false;

    public SearchDetailTriggers (List<SObject> p_triggerNew, List<SObject> p_triggerOld){
        super(p_triggerNew, p_triggerOld);

        allow_masterLoop_BeforeInsert = true;
        allow_masterLoop_BeforeUpdate = true; 
    }


    //Master loops
    public override void masterLoop_BeforeInsert(SObject recNew) {
        setExternalId((SearchDetail__c)recNew);
        checkSobjectAPIName((SearchDetail__c)recNew);
        checkFieldsAPIName((SearchDetail__c)recNew);
        checkURLParameterField((SearchDetail__c)recNew);
        checkRecordTypeDevName((SearchDetail__c)recNew);
    }
    public override void masterLoop_BeforeUpdate(SObject recNew, SObject recOld) {
        setExternalId((SearchDetail__c)recNew);
        checkSobjectAPIName((SearchDetail__c)recNew);
        checkFieldsAPIName((SearchDetail__c)recNew);
        checkURLParameterField((SearchDetail__c)recNew);
        checkRecordTypeDevName((SearchDetail__c)recNew);
    }

    private void checkSobjectAPIName(SearchDetail__c recNew){
        Boolean exist = false;
        for (Schema.SObjectType sObjectType : Schema.getGlobalDescribe().values() ) {
            String sobjName = String.valueOf(sObjectType);
            if (sobjName.equalsIgnoreCase(recNew.ObjectAPIName__c) ) {
                exist = true;
            }
        }
        if(!exist){
            hasError = true;
            recNew.addError(Label.GlobalSearchWrongSobject);
        }
    }

    private void checkFieldsAPIName(SearchDetail__c recNew){
        if(!hasError){

            List<String>                        fieldsToShow    = recNew.FieldsToShow__c.split(',');
            List<String>                        fieldsToSearch  = recNew.FieldsToSearch__c.split(',');
            Map<String, Schema.SObjectType>     schemaMap       = Schema.getGlobalDescribe();
            Schema.SObjectType                  objectSchema    = schemaMap.get(recNew.ObjectAPIName__c);
            Map<String, Schema.SObjectField>    objectFieldsMap = objectSchema.getDescribe().fields.getMap();
            Set<String>                         objectFields    = objectFieldsMap.keySet();

            for(String field : fieldsToShow){
                if(!objectFields.contains(field.toLowerCase())) {
                    recNew.addError(String.format(Label.GlobalSearchWrongField, new List<String> {field, recNew.ObjectAPIName__c}));
                    hasError = true;
                    return;
                }
            }
            for(String field : fieldsToSearch){
                if(!objectFields.contains(field.toLowerCase())) {
                    recNew.addError(String.format(Label.GlobalSearchWrongField, new List<String> {field, recNew.ObjectAPIName__c}));
                    hasError = true;
                    return;
                }
                if(!objectFieldsMap.get(field).getDescribe().isFilterable()){
                    recNew.addError(String.format(Label.GlobalSearchFieldNotFilterable, new List<String> {field, recNew.ObjectAPIName__c}));
                    hasError = true;
                    return;
                }
            }
        }
    }

    private void checkURLParameterField(SearchDetail__c recNew){
        if(!hasError){

            String                              urlParameterField   = recNew.URLParameterField__c;
            Map<String, Schema.SObjectType>     schemaMap           = Schema.getGlobalDescribe();
            Schema.SObjectType                  objectSchema        = schemaMap.get(recNew.ObjectAPIName__c);
            Map<String, Schema.SObjectField>    objectFieldsMap     = objectSchema.getDescribe().fields.getMap();
            Set<String>                         objectFields        = objectFieldsMap.keySet();

            if(!objectFields.contains(urlParameterField.toLowerCase())) {
                recNew.addError(String.format(Label.GlobalSearchWrongField, new List<String> {urlParameterField, recNew.ObjectAPIName__c}));
                hasError = true;
                return;
            }
        }
    }

    private void checkRecordTypeDevName(SearchDetail__c recNew){
        if(!String.isBlank(recNew.RecordTypeDevName__c) && !hasError){
            Map<String, Schema.SObjectType>     schemaMap   = Schema.getGlobalDescribe();
            Map<String,Schema.RecordTypeInfo>   recordTypes = schemaMap.get(recNew.ObjectAPIName__c).getDescribe().getRecordTypeInfosByDeveloperName();
            if(!recordTypes.containsKey(recNew.RecordTypeDevName__c)){
                    recNew.addError(String.format(Label.GlobalSearchWrongRT, new List<String> {recNew.RecordTypeDevName__c, recNew.ObjectAPIName__c}));
            }
        }
    }

    private void setExternalId(SearchDetail__c recNew){
        if(!canMethod('setExternalId')){return;}

        if(recNew.ExternalID__c == null){
            recNew.ExternalID__c = GeneralUtils.generateExternalId(recNew.Name, recNew.Cluster__c, recNew.getSObjectType().getDescribe().getName());
        }
    }
}