src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ParentCluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Cluster</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>- Parent Cluster record can only be of Group or Root type.
- Cluster Root cannot have a Parent Cluster.</errorMessage>
            <filterItems>
                <field>Cluster__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Cluster Group, Cluster Root</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Cluster Root</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Related Clusters</relationshipLabel>
        <relationshipName>RelatedClusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterGroup</fullName>
        <active>true</active>
        <description>Represents a grouping cluster of other grouping clusters or cluster leafs. (Ex.: EMEA, Africa, Latam).</description>
        <label>Cluster Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>TriggersByPass__c</fullName>
        <label>Triggers By Pass</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TriggersDebugs__c</fullName>
        <label>Triggers Debugs</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/classes/TriggersHandlerManagerTest.cls
@isTest
public class TriggersHandlerManagerTest {
    
    @testSetup
    static void setup(){
        MockupFactory.generateAcceleratorSetting();

        User u = MockupFactory.createUser('test__user@test.com', 'test__user@test.com');
        u.TriggersDebugs__c = 'triggerCanDebug';
        u.TriggersDebugs__c = 'triggerCanDebugButBypassed';
        u.TriggersByPass__c = 'triggerBypassedInUser';
        update u;

        List<Cluster__c> clusters = MockupFactory.createCluster('TestCluster', null, 10, 'ClusterRoot', 'CRT');
        Id clusterId = clusters[0].Id;
        MockupFactory.createCluster('ClusterLevel2', clusterId, 10, 'ClusterGroup', 'CGT');

    }

    @isTest
    static void bypassTriggerTest(){
        //Comment: Add Trigger to bypass

        //When
        TriggersHandlerManager.byPassTrigger('testTrigger');

        //Then
        system.assert(TriggersHandlerManager.isByPassTrigger('testTrigger'));

        //Remove the trigger from bypass
        //When
        TriggersHandlerManager.removeByPassTrigger('testTrigger');
        //Then
        system.assert(!TriggersHandlerManager.isByPassTrigger('testTrigger'));
    }

    @isTest
    static void canAutoDebugTest(){
        //Comment: 

        //Given
        User u = [SELECT Id, TriggersDebugs__c FROM User WHERE username = 'test__user@test.com'];

        //When
        Boolean canDebug;
        system.runAs(u){
            canDebug = TriggersHandlerManager.canAutoDebug('triggerCanDebug');
        }

        //Then
        system.assert(canDebug);
    }

    @isTest
    static void cannotAutoDebugTest(){
        //Comment: 

        //Given
        User u = [SELECT Id, TriggersDebugs__c FROM User WHERE username = 'test__user@test.com'];
        TriggersHandlerManager.byPassTrigger('triggerCanDebugButBypassed');

        //When
        Boolean canDebug;
        system.runAs(u){
            canDebug = TriggersHandlerManager.canAutoDebug('triggerCanDebugButBypassed');
        }

        //Then
        system.assert(!canDebug);
    }

    @isTest
    static void canTriggerTest(){
        //Comment: 

        //Given
        User u = [SELECT Id, TriggersDebugs__c FROM User WHERE username = 'test__user@test.com'];
        TriggersHandlerManager.byPassTrigger('triggerBypassed');

        //When
        Boolean canRun1;
        Boolean canRun2;
        Boolean canRun3;
        system.runAs(u){
            canRun1 = TriggersHandlerManager.canTrigger('triggerBypassed');
            canRun2 = TriggersHandlerManager.canTrigger('triggerBypassedInUser');
            canRun3 = TriggersHandlerManager.canTrigger('triggerCanRun');   
        }

        //Then
        system.assert(!canRun1);
        system.assert(!canRun2);
        system.assert(canRun3);
    }

    @isTest
    static void getTriggerListFilteredTest(){
        //Comment: 
        
        //Given
        TriggersHandlerManager.triggerOld = Database.query('SELECT Id, ParentCluster__c, name FROM Cluster__c WHERE name LIKE \'%Cluster%\'');

        TriggersHandlerManager.triggerNew = Database.query('SELECT Id, ParentCluster__c, name FROM Cluster__c WHERE name LIKE \'%Cluster%\'');

        //When
        TriggersHandlerManager.TriggerFiltered filteredResultName = TriggersHandlerManager.getTriggerListFiltered('name');
        TriggersHandlerManager.TriggerFiltered filteredResultParentCluster = TriggersHandlerManager.getTriggerListFiltered('ParentCluster__c');
        TriggersHandlerManager.TriggerFiltered filteredResultNull = TriggersHandlerManager.getTriggerListFiltered(null);

        //Then
        system.assertEquals(20,filteredResultName.triggerNewFiltered.keySet().size());
        system.assertEquals(20,filteredResultName.triggerOldFiltered.keySet().size());
        system.assertEquals(2,filteredResultParentCluster.triggerNewFiltered.keySet().size());
        system.assertEquals(2,filteredResultParentCluster.triggerOldFiltered.keySet().size());
        system.assert(filteredResultNull.triggerNewFiltered.keySet().isEmpty());
        system.assert(filteredResultNull.triggerOldFiltered.keySet().isEmpty());
    }

}