src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>DefaultLanguage__c</fullName>
        <label>Default Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AvailableLanguages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OtherLanguages__c</fullName>
        <description>Languages that Content Admins will be able to translate and community users can select in the community. For Cluster Groups, you need to select all languages defined below the hierarchy.</description>
        <inlineHelpText>Languages that Content Admins will be able to translate and community users can select in the community. For Cluster Groups, you need to select all languages defined below the hierarchy.</inlineHelpText>
        <label>Other Languages</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AvailableLanguages</valueSetName>
        </valueSet>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CG_LanguageSelectorControllerTest.cls
@isTest(seeAllData = false)
public with sharing class CG_LanguageSelectorControllerTest {

	@testSetup
	static void generateCustomSettings(){
		MockupFactory.generateAcceleratorSetting();
	}

	@isTest 
	static void insertCategoryTest(){
		/* Comment: Comprueba que dado un Cluster__c retorna un wrapper con los idiomas 
			correspondientes*/

		//Given
		List<Cluster__c> clusterRootList = MockupFactory.createCluster('ClusterRootTest', null, 1, 'ClusterRoot', 'CRT');
		List<Cluster__c> clusterList = [SELECT Id, Name FROM Cluster__c WHERE Name LIKE 'ClusterRootTest%' LIMIT 1 ];
		Cluster__c cluster = clusterList[0];
		cluster.DefaultLanguage__c='es';
		cluster.OtherLanguages__c='en_US';
		update cluster;

		//When
		Test.startTest();

		CG_LanguageSelectorController.MenuWrapper wrap = CG_LanguageSelectorController.getLanguageMenu(cluster.Id);
		
		Test.stopTest();
		//Then
		System.assertNotEquals(wrap, null);
	}

		@isTest 
	static void setLanguageTest(){
		/* Comment: Comprueba que seleccionado un lenguaje se setea en el usuario*/

		//Given

		//When
		Test.startTest();

		CG_LanguageSelectorController.setLanguage('es');
		
		Test.stopTest();
		//Then
		User u = [SELECT id ,LanguageLocaleKey FROM User WHERE id =: UserInfo.getUserId()];
		System.assertEquals(u.LanguageLocaleKey, 'es');
	}
}