src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ClusterUser__c.object
<CustomObject>
    <description>Determines which users have access to the cluster, the access type (Read Only or Read/Write), it&apos;s child clusters and the configuration below the cluster (ex.: Content, Components, Tags, etc.).</description>
    <fields>
        <fullName>AccessLevel__c</fullName>
        <label>Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read Only Down</fullName>
                </value>
                <value>
                    <fullName>Read/Write</fullName>
                </value>
                <value>
                    <fullName>Read All ORG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipName>ClusterGovernance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ClusterUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cluster User</label>
    <nameField>
        <displayFormat>CU-{00000}</displayFormat>
        <label>Cluster User #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClusterUserTriggersTest.cls
@isTest
private class ClusterUserTriggersTest{
	
	@testSetup
	static void setup(){
		MockupFactory.generateAcceleratorSetting();
		List<Cluster__c> clusters = MockupFactory.createCluster('Test Cluster Root', null, 1, 'ClusterRoot');
		
		User userToInsert = MockupFactory.createFullUser('userToInsert@cg.com','test@user.com');
		User userRW = MockupFactory.createFullUser('userRW@cg.com','test@user.com');
		User userRO = MockupFactory.createFullUser('userRO@cg.com','test@user.com');
		
		MockupFactory.createClusterUser(clusters.get(0).Id, userRO.Id, 'Read Only', 1);
		MockupFactory.createClusterUser(clusters.get(0).Id, userRW.Id, 'Read/Write', 1);
	}

	@isTest
	static void insertClusterUserWithAccessLevelReadWrite(){
		// Given
		Map<Id, Group> groups = new Map<Id, Group> ([SELECT Id, developerName FROM Group WHERE developerName LIKE 'TestClusterRoot%']);
		Cluster__C cluster = [SELECT Id FROM Cluster__c WHERE Name = 'Test Cluster Root00' LIMIT 1];
		User testUser = [SELECT Id FROM User WHERE username = 'userToInsert@cg.com' LIMIT 1];
		ClusterUser__c clusterUser = new ClusterUser__c();
		clusterUser.Cluster__c = cluster.Id;
		clusterUser.User__c = testUser.Id;
		clusterUser.AccessLevel__c = 'Read/Write';

		// When
		Test.startTest();
		insert clusterUser;
		Test.stopTest();

		// Then
		List<GroupMember> groupMembers = [SELECT Id, GroupId, UserOrGroupId FROM GroupMember WHERE UserOrGroupId = :testUser.Id];
		for (GroupMember gm : groupMembers){
			Group g = groups.get(gm.GroupId);
			system.assert(g.developerName == 'TestClusterRoot00_RW' || g.developerName == 'TestClusterRoot00_ROViewUp');
		}
	}

	@isTest
	static void insertClusterUserWithAccessLevelReadOnly(){
		// Given
		Map<Id, Group> groups = new Map<Id, Group> ([SELECT Id, developerName FROM Group WHERE developerName LIKE 'TestClusterRoot%']);
		Cluster__C cluster = [SELECT Id FROM Cluster__c WHERE Name = 'Test Cluster Root00' LIMIT 1];
		User testUser = [SELECT Id FROM User WHERE username = 'userToInsert@cg.com' LIMIT 1];
		ClusterUser__c clusterUser = new ClusterUser__c();
		clusterUser.Cluster__c = cluster.Id;
		clusterUser.User__c = testUser.Id;
		clusterUser.AccessLevel__c = 'Read Only';

		// When
		Test.startTest();
		insert clusterUser;
		Test.stopTest();

		// Then
		List<GroupMember> groupMembers = [SELECT Id, GroupId, UserOrGroupId FROM GroupMember WHERE UserOrGroupId = :testUser.Id];
		for (GroupMember gm : groupMembers){
			Group g = groups.get(gm.GroupId);
			system.assert(g.developerName == 'TestClusterRoot00_ROViewDown' || g.developerName == 'TestClusterRoot00_ROViewUp');
		}
	}

	@isTest
	static void updateClusterUserAccessLevelRWToRO(){
		// Given
		Map<Id, Group> groups = new Map<Id, Group> ([SELECT Id, developerName FROM Group WHERE developerName LIKE 'TestClusterRoot%']);
		Cluster__C cluster = [SELECT Id FROM Cluster__c WHERE Name = 'Test Cluster Root00' LIMIT 1];
		User testUser = [SELECT Id FROM User WHERE username = 'userRW@cg.com' LIMIT 1];
		ClusterUser__c clusterUser = [SELECT Id FROM ClusterUser__c WHERE User__c = :testUser.Id LIMIT 1];

		// When
		Test.startTest();
		clusterUser.AccessLevel__c = 'Read Only';
		update clusterUser;
		Test.stopTest();

		// Then
		List<GroupMember> groupMembers = [SELECT Id, GroupId, UserOrGroupId FROM GroupMember WHERE UserOrGroupId = :testUser.Id];
		for (GroupMember gm : groupMembers){
			Group g = groups.get(gm.GroupId);
			system.assert(g.developerName == 'TestClusterRoot00_ROViewDown' || g.developerName == 'TestClusterRoot00_ROViewUp');
		}
	}

	@isTest
	static void updateClusterUserAccessLevelROToRW(){
		// Given
		Map<Id, Group> groups = new Map<Id, Group> ([SELECT Id, developerName FROM Group WHERE developerName LIKE 'TestClusterRoot%']);
		User testUser = [SELECT Id FROM User WHERE username = 'userRO@cg.com' LIMIT 1];
		ClusterUser__c clusterUser = [SELECT Id FROM ClusterUser__c WHERE User__c = :testUser.Id LIMIT 1];

		// When
		Test.startTest();
		clusterUser.AccessLevel__c = 'Read/Write';
		update clusterUser;
		Test.stopTest();

		// Then
		List<GroupMember> groupMembers = [SELECT Id, GroupId, UserOrGroupId FROM GroupMember WHERE UserOrGroupId = :testUser.Id];
		for (GroupMember gm : groupMembers){
			Group g = groups.get(gm.GroupId);
			system.assert(g.developerName == 'TestClusterRoot00_RW' || g.developerName == 'TestClusterRoot00_ROViewUp');
		}
	}

	@isTest
	static void deleteClusterUserAccessLevelReadWrite(){
		// Given
		Map<Id, Group> groups = new Map<Id, Group> ([SELECT Id, developerName FROM Group WHERE developerName LIKE 'TestClusterRoot%']);
		User testUser = [SELECT Id FROM User WHERE username = 'userRW@cg.com' LIMIT 1];
		ClusterUser__c clusterUser = [SELECT Id FROM ClusterUser__c WHERE User__c = :testUser.Id LIMIT 1];

		// When
		Test.startTest();
		delete clusterUser;
		Test.stopTest();

		// Then
		List<GroupMember> groupMembers = new List<GroupMember>();
		try{
			groupMembers = [SELECT Id, GroupId, UserOrGroupId FROM GroupMember WHERE UserOrGroupId = :testUser.Id];
		}catch(Exception e){
			system.assert(groupMembers.isEmpty());
		}
	}

	@isTest
	static void deleteClusterUserAccessLevelReadOnly(){
		// Given
		Map<Id, Group> groups = new Map<Id, Group> ([SELECT Id, developerName FROM Group WHERE developerName LIKE 'TestClusterRoot%']);
		User testUser = [SELECT Id FROM User WHERE username = 'userRO@cg.com' LIMIT 1];
		ClusterUser__c clusterUser = [SELECT Id FROM ClusterUser__c WHERE User__c = :testUser.Id LIMIT 1];

		// When
		Test.startTest();
		delete clusterUser;
		Test.stopTest();

		// Then
		List<GroupMember> groupMembers = new List<GroupMember>();
		try{
			groupMembers = [SELECT Id, GroupId, UserOrGroupId FROM GroupMember WHERE UserOrGroupId = :testUser.Id];
		}catch(Exception e){
			system.assert(groupMembers.isEmpty());
		}
	}
}