src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ClusterLandingUrl__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>URL to redirect</description>
        <label>Landing URL</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MappingClusterField__c</fullName>
        <defaultValue>&quot;DefaultLanguage__c&quot;</defaultValue>
        <description>Represents the field in the Cluster that will be use to match with the &quot;Mapping Object Field&quot;. By default is the Default Language field.</description>
        <inlineHelpText>Represents the field in the Cluster that will be use to match with the &quot;Mapping Object Field&quot;. By default is the Default Language field.</inlineHelpText>
        <label>Mapping Cluster Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MappingObjectField__c</fullName>
        <defaultValue>&quot;LanguageLocaleKey&quot;</defaultValue>
        <description>Represents the field within the object defined in &quot;Mapping Object&quot; that will be use to match with the &quot;Mapping Cluster Field&quot;. By default is the Language field in the User object.</description>
        <inlineHelpText>Represents the field within the object defined in &quot;Mapping Object&quot; that will be use to match with the Cluster &quot;Mapping Value&quot;. By default is the Language field in the User object.</inlineHelpText>
        <label>Mapping Object Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MappingObject__c</fullName>
        <description>Represents the object that will determine the cluster leaf to be used in the community. By default is the User object but it can be extended to other objects.</description>
        <inlineHelpText>Represents the object that will determine the cluster leaf to be used in the community. By default is the User object but it can be extended to other objects.</inlineHelpText>
        <label>Mapping Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                    <default>true</default>
                    <label>User</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterGroup</fullName>
        <active>true</active>
        <description>Represents a grouping cluster of other grouping clusters or cluster leafs. (Ex.: EMEA, Africa, Latam).</description>
        <label>Cluster Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterLeaf</fullName>
        <active>true</active>
        <description>Represents the lowest level of the clustering tree. Community users will be related to this cluster level. (Ex.: Argentina Consumers)</description>
        <label>Cluster Leaf</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>ClusterExternalId__c</fullName>
        <formula>Cluster__r.ExternalId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cluster External Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Datasource__c</fullName>
        <label>Datasource</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ManualAssignment</fullName>
                    <label>Manual Assignment</label>
                </value>
                <value>
                    <fullName>Tags</fullName>
                </value>
                <value>
                    <fullName>Categories</fullName>
                </value>
                <value>
                    <fullName>TagsCategories</fullName>
                    <label>Tags + Categories</label>
                </value>
                <value>
                    <fullName>ParentComponentBehaviour</fullName>
                    <label>Parent Component Behaviour</label>
                </value>
                <value>
                    <fullName>ParentContentTags</fullName>
                    <label>Parent Content Tags</label>
                </value>
                <value>
                    <fullName>ParentContentCategories</fullName>
                    <label>Parent Content Categories</label>
                </value>
                <value>
                    <fullName>ParentContentTagsCategories</fullName>
                    <label>Parent Content Tags + Categories</label>
                </value>
                <value>
                    <fullName>All News</fullName>
                </value>
                <value>
                    <fullName>All Events</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FirstCluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>First Cluster to make a cluster Tree in cluster selector component</description>
        <label>First Cluster to show</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterGroup</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components (First Cluster)</relationshipLabel>
        <relationshipName>Components1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OnlyClusterLeaf__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if checked, the user can only select clusters leaf</description>
        <inlineHelpText>if checked, the user can only select clusters leaf</inlineHelpText>
        <label>Only Leaf clusters are selectable</label>
        <type>Checkbox</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FE_ClusterSelectorController.cls
public with sharing class FE_ClusterSelectorController extends FE_ComponentManager{
    
    //WRAPPER
    public class TreeWrapper extends FE_ComponentManager.DataWrapper{
        @auraEnabled public String label;
        @auraEnabled public String name;
        @auraEnabled public Boolean expanded;
        @auraEnabled public String clusterLanding;
        @auraEnabled public String clustertype;
        @auraEnabled public List<TreeWrapper> items;
        @auraEnabled public Boolean leafOnly;

        public TreeWrapper(ClusterUtils.ClusterWrapper p_clusterWrapper, Boolean leaf){
            leafOnly = leaf;

            if(p_clusterWrapper != null && p_clusterWrapper.cluster != null){
                this.label = p_clusterWrapper.cluster.Name;
                this.name = p_clusterWrapper.cluster.Id;
                this.expanded = (p_clusterWrapper.relatedClusters != null && p_clusterWrapper.relatedClusters.size() > 0);
                this.clusterLanding = p_clusterWrapper.cluster.ClusterLandingUrl__c;
                this.clustertype = p_clusterWrapper.cluster.RecordType.DeveloperName;
                items = new List<TreeWrapper>();
            }
        }
    }


    @auraEnabled
    public static ComponentWrapper getComponentWrapper(String componentExternalId, String componentId, String device){
        FE_ClusterSelectorController ctrl = new FE_ClusterSelectorController();
        ctrl.customPermissionEdit = 'Cluster Selector Edit Frame';
        ctrl.customPermissionView = 'Cluster Selector View Frame';        
        ctrl.componentFieldSet = new Set<String>{
            'Datasource__c'
        };
        ctrl.componentExternalId = componentExternalId;
        ctrl.componentId = componentId;
        ctrl.device = device;
        return ctrl.getCW();
    }

    public override DataWrapper getData() {
    	TreeWrapper tw;
    	
    	if(String.isBlank(this.componentExternalId)){
    		tw = getClusterRootForComponent(this.componentId);
    	} else {
    		tw = getClusterRootByExternalId(this.componentExternalId);
    	}

        return tw;
    }    
    
    @AuraEnabled
    public static String getClusterRedirect (String clusterLandingUrl){
        String retURL = '';
        List<Navigation__c> navigationList = [SELECT Id, URL__c FROM Navigation__c WHERE Id =: clusterLandingUrl];
        
        if(!navigationList.isEmpty()){
            retURL = navigationList[0].URL__c;
        }    
        return retURL;
    }    
    
    @AuraEnabled
    public static TreeWrapper getClusterRootByExternalId(String externalId){
        Boolean leafOnly = false;
        Cluster__c clusterRoot;
        Component__c component = FE_ClusterSelectorController.getComponent(externalId);
        List<Cluster__c> clusterList = new List<Cluster__c>();

        if(component != null ){
            leafOnly = component.OnlyClusterLeaf__c;
            clusterList = [SELECT Id, MappingObject__c, MappingObjectField__c, MappingClusterField__c, ClusterLandingUrl__c, RecordType.DeveloperName 
                            FROM Cluster__c 
                            WHERE RecordType.DeveloperName IN ('ClusterRoot','ClusterGroup') 
                                AND Id =: component.FirstCluster__c ];
        }
      
        if(!clusterList.isEmpty()){
            clusterRoot = clusterList[0];
	        ClusterUtils.ClusterWrapper clusterWrappper = ClusterUtils.getClustersBelow(clusterRoot.Id);
	        TreeWrapper tree = FE_ClusterSelectorController.getTree(clusterWrappper, leafOnly);       
	        return tree;
        }

        return null;      
    }

    @AuraEnabled
    public static TreeWrapper getClusterRootForComponent(String componentId){
        String clusterId = getComponentClusterId(componentId);
        Boolean leafOnly = false;

        ClusterUtils.ClusterWrapper clusterWrappper = ClusterUtils.getClustersBelow(clusterId);
        TreeWrapper tree = FE_ClusterSelectorController.getTree(clusterWrappper, leafOnly);     
        
        return tree;
    }
    
    public static String getComponentClusterId(String componentId){
        Boolean leafOnly = false;
        
        List<Component__c> component = [SELECT Id, Cluster__c, ClusterExternalId__c FROM Component__c WHERE Id =: componentId];
        if(component.size() > 0){
        	return component[0].Cluster__c;	
        }
        return '';
    }
       
    private static TreeWrapper getTree(ClusterUtils.ClusterWrapper clusterWrapper, Boolean leafOnly){
        if(clusterWrapper == null){
            return null;
        }

        TreeWrapper item = new TreeWrapper(clusterWrapper, (clusterWrapper.cluster.RecordType.DeveloperName.equalsIgnoreCase('ClusterLeaf'))?false:leafOnly);
        List<TreeWrapper> itemList = new List<TreeWrapper>();

        for (ClusterUtils.ClusterWrapper clusterW : clusterWrapper.relatedClusters) {
            itemList.add(FE_ClusterSelectorController.getTree(clusterW, leafOnly));
        }
        item.items.addAll(itemList); 
        
        return item;
    } 

    private static Component__c getComponent(String externalId){
        List<Component__c> component = [SELECT FirstCluster__c, OnlyClusterLeaf__c 
                                        FROM Component__c WHERE ExternalId__c =: externalId];
        if(component.size() > 0){
        	return component[0];
        }
        return null;
    }

}