src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterGroup</fullName>
        <active>true</active>
        <description>Represents a grouping cluster of other grouping clusters or cluster leafs. (Ex.: EMEA, Africa, Latam).</description>
        <label>Cluster Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterLeaf</fullName>
        <active>true</active>
        <description>Represents the lowest level of the clustering tree. Community users will be related to this cluster level. (Ex.: Argentina Consumers)</description>
        <label>Cluster Leaf</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Datasource__c</fullName>
        <label>Datasource</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ManualAssignment</fullName>
                    <label>Manual Assignment</label>
                </value>
                <value>
                    <fullName>Tags</fullName>
                </value>
                <value>
                    <fullName>Categories</fullName>
                </value>
                <value>
                    <fullName>TagsCategories</fullName>
                    <label>Tags + Categories</label>
                </value>
                <value>
                    <fullName>ParentComponentBehaviour</fullName>
                    <label>Parent Component Behaviour</label>
                </value>
                <value>
                    <fullName>ParentContentTags</fullName>
                    <label>Parent Content Tags</label>
                </value>
                <value>
                    <fullName>ParentContentCategories</fullName>
                    <label>Parent Content Categories</label>
                </value>
                <value>
                    <fullName>ParentContentTagsCategories</fullName>
                    <label>Parent Content Tags + Categories</label>
                </value>
                <value>
                    <fullName>All News</fullName>
                </value>
                <value>
                    <fullName>All Events</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HierarchicalOrderBy__c</fullName>
        <label>Cluster Hierarchy Order By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASC</fullName>
                    <label>Root to Leaf</label>
                </value>
                <value>
                    <fullName>DESC</fullName>
                    <label>Leaf to Root</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderByAdvance__c</fullName>
        <label>Order by Advance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderBy__c</fullName>
        <label>Order By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CreatedDate ASC</fullName>
                    <default>true</default>
                    <label>Creation Date ASC</label>
                </value>
                <value>
                    <fullName>CreatedDate DESC</fullName>
                    <label>Creation Date DESC</label>
                </value>
                <value>
                    <fullName>Name ASC</fullName>
                </value>
                <value>
                    <fullName>Name DESC</fullName>
                </value>
                <value>
                    <fullName>Category__r.Name ASC</fullName>
                    <label>Category ASC</label>
                </value>
                <value>
                    <fullName>Category__r.Name DESC</fullName>
                    <label>Category DESC</label>
                </value>
                <value>
                    <fullName>PublishStartDate__c ASC</fullName>
                    <label>Publish Start Date ASC</label>
                </value>
                <value>
                    <fullName>PublishStartDate__c DESC</fullName>
                    <label>Publish Start Date DESC</label>
                </value>
                <value>
                    <fullName>EventStartDate__c ASC</fullName>
                    <label>Event Start Date ASC</label>
                </value>
                <value>
                    <fullName>EventStartDate__c DESC</fullName>
                    <label>Event Start Date DESC</label>
                </value>
                <value>
                    <fullName>ListTitle__c ASC</fullName>
                    <label>List Title ASC</label>
                </value>
                <value>
                    <fullName>ListTitle__c DESC</fullName>
                    <label>List Title DESC</label>
                </value>
                <value>
                    <fullName>Custom Sorting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PageSize__c</fullName>
        <label>Page Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HTMLContent__c</fullName>
        <inlineHelpText>If html content wants to be uploaded use this field instead of the Long Description one.</inlineHelpText>
        <label>HTML Content</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FE_ContentManagerTest.cls
@isTest
private class FE_ContentManagerTest {
	
	@testSetup
	static void generateCustomSettings(){
		MockupFactory.generateAcceleratorSetting();
		List<Cluster__c> clusterRoot = MockupFactory.createCluster('Cluster Root', '', 1, 'ClusterRoot', 'CRT');
        List<Cluster__c> clusterGroup = MockupFactory.createCluster('Cluster Group', clusterRoot.get(0).id, 1, 'ClusterGroup', 'CGT');
        List<Cluster__c> clusterLeaf = MockupFactory.createCluster('Cluster Leaf', clusterGroup.get(0).id, 2, 'ClusterLeaf', 'CLT');
        List<Component__c> componentList = MockupFactory.createComponent('Advance Content', 1, clusterRoot[0]);
		List<Content__c> contentList = MockupFactory.createContent('Advance Content', clusterRoot[0], 1);
		MockupFactory.createContentAssignment(contentList, componentList);
	}

	@isTest 
	static void getCWTest() {
		//Given
		String device = 'Desktop';
		List<Component__c> componentList = [SELECT Id, ExternalId__c, Cluster__c, Recordtype.DeveloperName, Recordtype.Id, Datasource__c, OrderBy__c, OrderByAdvance__c, HierarchicalOrderBy__c, TagCriteria__c, PageSize__c  FROM Component__c LIMIT 1];

		Set<String> contentSetFields = new Set<String>{
            'HTMLContent__c'
        };
		
		//When
		Test.startTest();
		FE_ComponentManager.DataWrapper data = FE_ContentManager.getCMSContent(componentList[0].Cluster__c, componentList[0], contentSetFields, device);
		Test.stopTest();

		//Then
		System.assertNotEquals(data, null);
	}
}