src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tag__c.object
<CustomObject>
    <description>Short phrase or word to be used as a search criteria or joint criteria between different objects (Ex. Joint between Content and Components)</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Tags</relationshipLabel>
        <relationshipName>Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ObjectSharingUtilTest.cls
@isTest
private class ObjectSharingUtilTest
{

	@testSetup
	static void generateCustomSettings(){
		MockupFactory.generateAcceleratorSetting();
	}

	@isTest
	static void insertTagSharing()
	{
		// Given
		List<Cluster__c> clusterRootList = MockupFactory.createCluster('ClusterRootTest', null, 1, 'ClusterRoot', 'CRT');
		List<Cluster__c> clusterList = [SELECT Id, Name FROM Cluster__c WHERE Name LIKE 'ClusterRootTest%' LIMIT 1 ];
		System.debug('ClusterTriggersTest method clusterList: '+clusterList);

		List<Tag__c> tagList = MockupFactory.createTag('TagTest1', 'Test Tag', 1, clusterList[0].Id);

		System.debug('ClusterTriggersTest method tagList: '+tagList);
		// When
		//Test.startTest();//(List<SObject> records, String lookupField, String nameObjectShare, String sharingReason, Boolean isCluster){
			//'Cluster__c', 'Tag__Share', 'Clustering__c', false
		ObjectSharingUtil.SharingWrapper sharingWrapper = ObjectSharingUtil.generateSharingForRecordsOnCluster(tagList, 'Cluster__c', 'Tag__Share', 'Clustering__c', false);
		//Test.stopTest();
		System.assertEquals(0, sharingWrapper.objectIdToMessageErrosMap.size());
		System.assertEquals(3, sharingWrapper.listOfSharesToInsert.size());

	}

	@isTest
	static void insertClusterSharing()
	{
		// Given
		

		// When
		List<Cluster__c> clusterRootList = MockupFactory.createCluster('ClusterRootTest', null, 1, 'ClusterRoot', 'CRT');

		ObjectSharingUtil.SharingWrapper sharingWrapper = ObjectSharingUtil.generateSharingForCluster(clusterRootList, 'Cluster__c', 'Cluster__Share', 'Clustering__c', false);

		//Then
		System.assertEquals(0, sharingWrapper.objectIdToMessageErrosMap.size());
		System.assertEquals(3, sharingWrapper.listOfSharesToInsert.size());


		//Test.startTest();//(List<SObject> records, String lookupField, String nameObjectShare, String sharingReason, Boolean isCluster){
			//'Cluster__c', 'Tag__Share', 'Clustering__c', false
		
		//Test.stopTest();


	}

}