src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterGroup</fullName>
        <active>true</active>
        <description>Represents a grouping cluster of other grouping clusters or cluster leafs. (Ex.: EMEA, Africa, Latam).</description>
        <label>Cluster Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Recipe__c.object
<CustomObject>
    <description>Represents the recipes and contains the elements related to them as ingredients, instructions and the relationship with the corresponding brand</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Determine which cluster is associated with the recipe.</description>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Recipes</relationshipLabel>
        <relationshipName>Recipes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Recipe</label>
    <nameField>
        <label>Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RecipeTriggersTest.cls
@isTest
private class RecipeTriggersTest {	

@testSetup
    static void setupTest(){
    	MockupFactory.generateAcceleratorSetting();
        
        String name = 'Argentina';
        List<Cluster__c> clusterRootList = MockupFactory.createCluster(name, null, 1, 'ClusterRoot');
        Cluster__c cg = clusterRootList[0];
        List<Cluster__c> clusterList = MockupFactory.createCluster(cg.Name, cg.Id, 1, 'ClusterGroup');
       
    }

	@isTest 
	static void ExternalIdTest() {
		//When
		Cluster__c cluster = [Select id FROM Cluster__c Limit 1]; 

		//Given
		Test.startTest();
		List<Recipe__c> recipesList = MockupFactory.createRecipe('recipe test', 1, cluster.Id);
		Test.stopTest();

		//Then
		Recipe__c recipeTest = [SELECT id, ExternalID__c from Recipe__c where id =: recipesList[0].Id Limit 1];
		System.assertNotEquals(recipeTest.ExternalID__c, null);
	}

	@isTest 
	static void ExternalIdUpdateTest() {
		//When
		Cluster__c cluster = [Select id FROM Cluster__c Limit 1]; 
		List<Recipe__c> recipesList = MockupFactory.createRecipe('recipeTestUpdate', 1, cluster.Id);
		Recipe__c recipe = [SELECT id, ExternalID__c, Name from Recipe__c where id =: recipesList[0].Id Limit 1];
		recipe.ExternalID__c='';
		
		//Given
		Test.startTest();
		update recipe;
		Test.stopTest();

		//Then
		Recipe__c recipeTest = [SELECT id, ExternalID__c, Name from Recipe__c where Id =: recipe.Id   Limit 1];
		System.assertEquals(recipeTest.ExternalID__c, recipeTest.Name);
	}
	

	@isTest 
	static void insertRecipeSharing() {
		//When
		Cluster__c cluster = [Select id FROM Cluster__c Limit 1]; 
	
		//Given
		Test.startTest();
		List<Recipe__c> recipesList = MockupFactory.createRecipe('recipe test', 1, cluster.Id);
		Test.stopTest();

		//Then
		List<Recipe__Share> shareList = [SELECT Id, ParentId FROM Recipe__Share WHERE ParentId = :recipesList[0].Id AND RowCause = 'Clustering__c'];
		
		System.assertEquals(3, shareList.size());
	}

	@isTest 
	static void insertSharingWithoutClusterId() {
		//When

		//Given
		Test.startTest();
		List<Recipe__c> recipesList = MockupFactory.createRecipe('recipe test', 1, null);
		Test.stopTest();

		//Then
		List<Recipe__Share> shareList = [SELECT Id, ParentId FROM Recipe__Share WHERE ParentId = :recipesList[0].Id AND RowCause = 'Clustering__c'];
		
		System.assertEquals(0, shareList.size());
	}


	@isTest
	static void updateMenuSharing(){
		// Given
		List<Cluster__c> clusterRootList = MockupFactory.createCluster('ClusterRootTest', null, 2, 'ClusterRoot');
		List<Cluster__c> getClusterList = [SELECT Id, Name FROM Cluster__c WHERE Name LIKE 'ClusterRootTest%' LIMIT 2 ];
		System.debug('ClusterTriggersTest method getClusterList: '+getClusterList);
		
		List<Recipe__c> recipesList = MockupFactory.createRecipe('recipe test', 1, getClusterList[0].Id);
		Recipe__c recipe = [SELECT id, Name, ExternalID__c, Cluster__c from Recipe__c where id =: recipesList[0].Id Limit 1];
		recipe.Cluster__c = getClusterList[1].Id;
			
		// When
		Test.startTest();
		update recipe;
		Test.stopTest();

		// Then
		List<Recipe__Share> shareList = [SELECT Id, ParentId FROM Recipe__Share WHERE ParentId = :recipe.Id AND RowCause = 'Clustering__c'];	
		System.assertEquals(6, shareList.size());
	}

	@isTest
	static void updateMenuSharingWithoutClusterId(){
		// Given
		List<Cluster__c> clusterRootList = MockupFactory.createCluster('ClusterRootTest', null, 2, 'ClusterRoot');
		List<Cluster__c> getClusterList = [SELECT Id, Name FROM Cluster__c WHERE Name LIKE 'ClusterRootTest%' LIMIT 2 ];	

		List<Recipe__c> recipesList = MockupFactory.createRecipe('recipe test', 1, getClusterList[0].Id);
		Recipe__c recipe = [SELECT id, Name, ExternalID__c, Cluster__c from Recipe__c where id =: recipesList[0].Id Limit 1];
		recipe.Cluster__c = getClusterList[0].Id;

		// When
		Test.startTest();
		update recipe;
		Test.stopTest();

		// Then
		List<Recipe__Share> shareList = [SELECT Id, ParentId FROM Recipe__Share WHERE ParentId = :recipe.Id AND RowCause = 'Clustering__c'];

		System.assertEquals(3, shareList.size());

	}

}