src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>PublicGroupRODownName__c</fullName>
        <description>There is a one to one relationship between cluster and public group RO Down in order to manage cluster governance. This field stores the public group RO Down name related to the cluster.</description>
        <inlineHelpText>There is a one to one relationship between cluster and public group RO Down in order to manage cluster governance. This field stores the public group RO Down name related to the cluster.</inlineHelpText>
        <label>Public Group RO Down Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PublicGroupROUpName__c</fullName>
        <description>There is a one to one relationship between cluster and public group RO Up in order to manage cluster governance. This field stores the public group RO Up name related to the cluster.</description>
        <inlineHelpText>There is a one to one relationship between cluster and public group RO Up in order to manage cluster governance. This field stores the public group RO Up name related to the cluster.</inlineHelpText>
        <label>Public Group RO Up Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PublicGroupRWName__c</fullName>
        <description>There is a one to one relationship between cluster and public group RW in order to manage cluster governance. This field stores the public group RW name related to the cluster.</description>
        <inlineHelpText>There is a one to one relationship between cluster and public group RW in order to manage cluster governance. This field stores the public group RW name related to the cluster.</inlineHelpText>
        <label>Public Group RW Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tag__c.object
<CustomObject>
    <description>Short phrase or word to be used as a search criteria or joint criteria between different objects (Ex. Joint between Content and Components)</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Tags</relationshipLabel>
        <relationshipName>Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ObjectSharingUtil.cls
public with sharing class ObjectSharingUtil {
	


	public ObjectSharingUtil() {
		
	}


  	
  	
	public static SharingWrapper generateSharingForRecordsOnCluster(List<SObject> records, String lookupField, String nameObjectShare, String sharingReason, Boolean isCluster){

		Map<Id,String> objectIdToMessageErrosMap = new Map<Id,String>();
		Boolean excecuteTrigger = true;
		Map<String,Id> groupNameToGroupIdMap = new Map<String,Id>();
        Map<Id,List<Id>> mapRecordsByCluster = new Map<Id,List<Id>>();
        List<String> groupNameList = new List<String>();
        List<SObject> listOfSharesToInsert = new List<SObject>();
        System.debug('ObjectSharingUtil dataPreparing records: ' + records);
        for(SObject record: records){
            Id clusterId = (Id) record.get(lookupField);
            Id recordId = (Id) record.get('Id');
            if(!mapRecordsByCluster.containsKey(clusterId)){
            	mapRecordsByCluster.put(clusterId, new List<Id>{recordId});
        	}else{
                mapRecordsByCluster.get(clusterId).add(recordId);
        	}
        }

        System.debug('ObjectSharingUtil dataPreparing mapRecordsByCluster: ' + mapRecordsByCluster);

        Map<Id,Cluster__c> mapClusters = new Map<Id,Cluster__c>([SELECT Id, PublicGroupRWName__c, PublicGroupROUpName__c, PublicGroupRODownName__c  FROM Cluster__c WHERE Id IN: mapRecordsByCluster.keyset()]); 
        System.debug('ObjectSharingUtil dataPreparing mapClusters: ' + mapClusters);
        for(Id clusterId: mapClusters.keySet()){
        	Cluster__c cluster = mapClusters.get(clusterId);

            groupNameList.add(cluster.PublicGroupRWName__c);
            groupNameList.add(cluster.PublicGroupRODownName__c);
            groupNameList.add(cluster.PublicGroupROUpName__c);
        }
        System.debug('ObjectSharingUtil dataPreparing groupNameList: ' + groupNameList);

        List<Group> groupList = [SELECT Id, Name FROM Group WHERE Name IN :groupNameList];

        System.debug('ObjectSharingUtil dataPreparing groupList: ' + groupList);


        for(Group groupItem: groupList){

            if(!groupNameToGroupIdMap.containsKey(groupItem.Name)){
                 groupNameToGroupIdMap.put(groupItem.Name, groupItem.Id);
            }
        }

        Map<String,String> fieldNamesAndSecLevel = new Map<String,String>{'PublicGroupRWName__c' => 'Edit', 'PublicGroupROUpName__c' => 'Read', 'PublicGroupRODownName__c' => 'Read'};
        
        
        for(Id clusterId : mapRecordsByCluster.keySet()){
            if(mapClusters.containsKey(clusterId)){
                for(Id recordId: mapRecordsByCluster.get(clusterId)){
                	for(String fieldName: fieldNamesAndSecLevel.keySet()){
                		if(String.isNotBlank((String) mapClusters.get(clusterId).get(fieldName))){
		                	String objectName = recordId.getSobjectType().getDescribe().getName();

		                	String shareObjectName = nameObjectShare;
		                	Schema.SObjectType shareType = Schema.getGlobalDescribe().get(shareObjectName);
		                    SObject shareRecord = shareType.newSObject();
		                    shareRecord.put('ParentId', recordId);
		                    //shareRecord.put('UserOrGroupId', mapClusters.get(clusterId).get(fieldName));
		                    if(groupNameToGroupIdMap.containsKey((String) mapClusters.get(clusterId).get(fieldName))){
								shareRecord.put('UserOrGroupId', groupNameToGroupIdMap.get( (String) mapClusters.get(clusterId).get(fieldName)) );
			                    
			                    //pasar por parametro
			                    shareRecord.put('RowCause', sharingReason);
			                    shareRecord.put('AccessLevel', fieldNamesAndSecLevel.get(fieldName));
			                    listOfSharesToInsert.add(shareRecord);
							}else{
								objectIdToMessageErrosMap.put(recordId,'The selected Cluster doesnt have required groups2! ');
							}
		                    

	                    }else{
	                    	objectIdToMessageErrosMap.put(recordId,'The selected Cluster have one or mor groups blanks! ');
	                    }
                    }
                }
            }
        }

        SharingWrapper sharingWrapper = new SharingWrapper(objectIdToMessageErrosMap, listOfSharesToInsert);
        return sharingWrapper;
    }

	public static SharingWrapper generateSharingForCluster(List<SObject> records, String lookupField, String nameObjectShare, String sharingReason, Boolean isCluster){

		Map<Id,String> objectIdToMessageErrosMap = new Map<Id,String>();
		Boolean excecuteTrigger = true;
		Map<String,Id> groupNameToGroupIdMap = new Map<String,Id>();
        Map<Id,List<Id>> mapRecordsByCluster = new Map<Id,List<Id>>();
        List<String> groupNameList = new List<String>();
        List<SObject> listOfSharesToInsert = new List<SObject>();

        System.debug('TagTriggers dataPreparing records: ' + records);
        for(Sobject recordItem: records){
            groupNameList.add( ((Cluster__c) recordItem).PublicGroupRWName__c);
            groupNameList.add( ((Cluster__c) recordItem).PublicGroupRODownName__c);
            groupNameList.add( ((Cluster__c) recordItem).PublicGroupROUpName__c);
        }


        System.debug('TagTriggers dataPreparing groupNameList: ' + groupNameList);



        List<Group> groupList = [SELECT Id, Name FROM Group WHERE Name IN :groupNameList];



        for(Group groupItem: groupList){

            if(!groupNameToGroupIdMap.containsKey(groupItem.Name)){
                 groupNameToGroupIdMap.put(groupItem.Name, groupItem.Id);
            }
        }

	    Map<String,String> fieldNamesAndSecLevel = new Map<String,String>{'PublicGroupRWName__c' => 'Edit', 'PublicGroupROUpName__c' => 'Read', 'PublicGroupRODownName__c' => 'Read'};
	    
        System.debug('TagTriggers dataPreparing fieldNamesAndSecLevel: ' + fieldNamesAndSecLevel);
		                

        for(SObject record: records){
        	for(String fieldName: fieldNamesAndSecLevel.keySet()){
        		System.debug('record.get(fieldName)'+record.get(fieldName));
                	String shareObjectName = nameObjectShare;
                	Schema.SObjectType shareType = Schema.getGlobalDescribe().get(shareObjectName);
                    SObject shareRecord = shareType.newSObject();
                    shareRecord.put('ParentId', record.Id);
					shareRecord.put('UserOrGroupId', groupNameToGroupIdMap.get( (String) record.get(fieldName)) );
                    shareRecord.put('RowCause', sharingReason);
                    shareRecord.put('AccessLevel', fieldNamesAndSecLevel.get(fieldName));
                    listOfSharesToInsert.add(shareRecord);
            }
        }



        SharingWrapper sharingWrapper = new SharingWrapper(objectIdToMessageErrosMap, listOfSharesToInsert);
        return sharingWrapper;
    }


   /*public static sObject createManualShareGenericObject(Id recordId, Id userOrGroupId, String accessLevel, String sObjectType){
      
   	if(sObjectType == 'Tag__c'){
		Tag__Share tagShare  = new Tag__Share();
		tagShare.ParentId = recordId;
		tagShare.UserOrGroupId = userOrGroupId;
		tagShare.AccessLevel = accessLevel;
		tagShare.RowCause = Schema.Tag__Share.RowCause.Manual;
		return tagShare;
   	}

   	if(sObjectType == 'Content__c'){
		Content__Share contentShrare  = new Content__Share();
		contentShrare.ParentId = recordId;
		contentShrare.UserOrGroupId = userOrGroupId;
		contentShrare.AccessLevel = accessLevel;
		contentShrare.RowCause = Schema.Tag__Share.RowCause.Manual;
		return contentShrare;
   	}

   	if(sObjectType == 'Navigation__c'){
		Navigation__Share navigationShrare  = new Navigation__Share();
		navigationShrare.ParentId = recordId;
		navigationShrare.UserOrGroupId = userOrGroupId;
		navigationShrare.AccessLevel = accessLevel;
		navigationShrare.RowCause = Schema.Tag__Share.RowCause.Manual;
		return navigationShrare;
   	}

	return null;
  }*/

  public class SharingWrapper{

  	public Map<Id,String> objectIdToMessageErrosMap{get;set;}

  	public List<SObject> listOfSharesToInsert{get;set;}

  	public SharingWrapper(){

  	}

  	public SharingWrapper(Map<Id,String> objectIdToMessageErrosMap, List<SObject> listOfSharesToInsert){
  		this.objectIdToMessageErrosMap = objectIdToMessageErrosMap;
  		this.listOfSharesToInsert = listOfSharesToInsert;
  	}

  }

}