src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>Navigation</fullName>
        <active>true</active>
        <label>Navigation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Menu__c.object
<CustomObject>
    <description>Represents menu options than can be related to other menu options.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Menus</relationshipLabel>
        <relationshipName>Menus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ParentMenu__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Menu</label>
        <referenceTo>Menu__c</referenceTo>
        <relationshipLabel>ParentMenus</relationshipLabel>
        <relationshipName>SubMenus</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Menu</label>
    <nameField>
        <label>Menu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menus</pluralLabel>
    <recordTypes>
        <fullName>Menu</fullName>
        <active>true</active>
        <description>Represents the highest level of a Menu tree. It can be asociated to a component. (Ex. File)</description>
        <label>Menu</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MenuAssignment__c.object
<CustomObject>
    <fields>
        <fullName>Component__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Menu Assignments</relationshipLabel>
        <relationshipName>Menu_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Menu__c</fullName>
        <label>Menu</label>
        <referenceTo>Menu__c</referenceTo>
        <relationshipLabel>Menu Assignments</relationshipLabel>
        <relationshipName>Menu_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Menu Assignment</label>
    <nameField>
        <label>Menu Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menu Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CG_NavigationControllerTest.cls
@isTest
public class CG_NavigationControllerTest {
    @testSetup
    static void setup(){
        // Given in all cases
        MockupFactory.generateAcceleratorSetting();
        MockupFactory.createCluster('global', null, 1, 'ClusterRoot', 'CRT');
    }
    @isTest
    static void CASE_1(){
        //Comment: recuperar el ComponentWrapper de Navigation a partir de un ComponentExternalId, un ClasterId y un Device 
        //Given
        Cluster__c cluster = [SELECT id FROM Cluster__c LIMIT 1][0];
        List<Component__c> component = MockupFactory.createComponent('Menu',1,cluster);
        List<RecordType> menuRTs = [SELECT Id FROM RecordType WHERE SObjectType = 'Menu__c' ORDER BY Name ASC];
        Menu__c mainMenu = MockupFactory.createMenu('mainMenu', 1, cluster.Id)[0]; 
        mainMenu.RecordTypeId = menuRTs[0].Id; update mainMenu;
        Menu__c subMenu1 = MockupFactory.createMenu('subMenu1', 1, cluster.Id)[0]; 
        subMenu1.RecordTypeId = menuRTs.get(1).Id; subMenu1.ParentMenu__c = mainMenu.Id; update subMenu1;
        Menu__c subMenu2 = MockupFactory.createMenu('subMenu2', 1, cluster.Id)[0]; 
        subMenu2.RecordTypeId = menuRTs.get(1).Id; subMenu2.ParentMenu__c = mainMenu.Id; update subMenu2;
        MenuAssignment__c menuAssignment = new MenuAssignment__c(component__c = component[0].Id, Menu__c = mainMenu.Id); 
        insert menuAssignment;

        //When
        test.startTest();
        CG_NavigationController.ComponentWrapper componentWrapper = CG_NavigationController.getNavWrapper(component[0].ExternalId__c, cluster.id, 'DESKTOP');
        test.stopTest();
        //Then
        System.assertNotEquals(null, componentWrapper);
        System.assertEquals(component[0].ExternalId__c, componentWrapper.component.ExternalId__c);
        System.assertEquals(cluster.id, componentWrapper.clusterId);
        System.assertEquals('DESKTOP', componentWrapper.device);
    }
}