src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrderByAdvance__c</fullName>
        <label>Order by Advance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderBy__c</fullName>
        <label>Order By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CreatedDate ASC</fullName>
                    <default>true</default>
                    <label>Creation Date ASC</label>
                </value>
                <value>
                    <fullName>CreatedDate DESC</fullName>
                    <label>Creation Date DESC</label>
                </value>
                <value>
                    <fullName>Name ASC</fullName>
                </value>
                <value>
                    <fullName>Name DESC</fullName>
                </value>
                <value>
                    <fullName>Category__r.Name ASC</fullName>
                    <label>Category ASC</label>
                </value>
                <value>
                    <fullName>Category__r.Name DESC</fullName>
                    <label>Category DESC</label>
                </value>
                <value>
                    <fullName>PublishStartDate__c ASC</fullName>
                    <label>Publish Start Date ASC</label>
                </value>
                <value>
                    <fullName>PublishStartDate__c DESC</fullName>
                    <label>Publish Start Date DESC</label>
                </value>
                <value>
                    <fullName>EventStartDate__c ASC</fullName>
                    <label>Event Start Date ASC</label>
                </value>
                <value>
                    <fullName>EventStartDate__c DESC</fullName>
                    <label>Event Start Date DESC</label>
                </value>
                <value>
                    <fullName>ListTitle__c ASC</fullName>
                    <label>List Title ASC</label>
                </value>
                <value>
                    <fullName>ListTitle__c DESC</fullName>
                    <label>List Title DESC</label>
                </value>
                <value>
                    <fullName>Custom Sorting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner component. Each banner component has a given aspect ratio and orientation for its presentation. It also has a given behavior for presenting its content such as carousel or appear-disappear effect.</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner content. This content will scroll or appear-fade inside a Banner. The data this type of content allows are Media elements</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContentAssignment__c.object
<CustomObject>
    <description>Manages the direct assignment of Content to Components</description>
    <fields>
        <fullName>Component__c</fullName>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipName>ComponentContentAssignment</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipName>ComponentContentAssignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content Assignment</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Content Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ComponentTriggersTest.cls
@isTest(seeAllData = false)
public with sharing class ComponentTriggersTest {

	@isTest 
	static void insertComponentTest(){
		/* Comment: Comprueba que al crear un Component__c se inserta
			con el correspondiente ExternalId__c */

		//Given
		Component__c componentTest = new Component__c(Name='Component Test 01');

		//When
		Test.startTest();
			insert(componentTest);
		Test.stopTest();

		//Then
		Component__c componentTestResult =[select id, ExternalId__c from Component__c where id =: componentTest.id];
		System.assertNotEquals(componentTestResult.ExternalId__c, null);
	}

	@isTest
	static void updateComponentTest(){
		/* Comment: Comprueba que al actualizar un Component__c se actualiza
		con el correspondiente ExternalId__c */
		
		//Given
		Component__c componentTest = new Component__c(Name='Component Test 01', 
									OrderBy__c = 'Custom Sorting', 
									OrderByAdvance__c = 'CreatedDate');
		insert(componentTest);
		componentTest.ExternalId__c = null;
		componentTest.Name = 'Component Test 02';
		//When
		Test.startTest();
			update(componentTest);
		Test.stopTest();

		//Then
		Component__c componentTestResult2 =[select id, ExternalId__c from Component__c where id =: componentTest.id];
		System.assertNotEquals(componentTestResult2.ExternalId__c, null);
	}

	@isTest
	static void checkIfClusterWasChangedInComponent(){
		//PA-206 Governance de Componentes(Reparenting)
		/*Comment: Comprueba que al modificar el Cluster, el componente no tenga 
		Contenidos, Tags o Categorias relacionadas con el Componente*/
		
		//Given
		MockupFactory.generateAcceleratorSetting();
		String nameRecordType = 'Banner';
		Cluster__c clusterTest1 = new Cluster__c(Name = 'Cluster Test 1', ExternalId__c = 'ClusterTest1');
		insert (clusterTest1);
		Cluster__c clusterTest2 = new Cluster__c(Name = 'Cluster Test 2', ExternalId__c = 'ClusterTest2');
		insert (clusterTest2);
		List<Component__c> componentListTest = MockupFactory.createComponent(nameRecordType, 1);
		List<Content__c> contentListTest = MockupFactory.createContent(nameRecordType, clusterTest1, 1);
		List<ContentAssignment__c> contentAssignmentListTest = MockupFactory.createContentAssignment(contentListTest, componentListTest);

		//When
		Test.startTest();
		Component__c[] componentTest = [SELECT Id, Cluster__c FROM Component__c WHERE Name = 'Banner'];
		if(componentTest.size() > 0){
			componentTest[0].Cluster__c = clusterTest2.Id;	
		}
		update(componentTest);
		Test.stopTest();
		
		//Then
		Component__c componentTestResult3 = [SELECT Id, Cluster__c FROM Component__c WHERE Id =: componentListTest]; 
		System.assertNotEquals(componentTestResult3.Cluster__c,clusterTest2.Id);
	}

	@isTest
	static void insertComponentSharing()
	{
		// Given
		MockupFactory.generateAcceleratorSetting();
		List<Cluster__c> clusterRootList = MockupFactory.createCluster('ClusterRootTest', null, 1, 'ClusterRoot');
		List<Cluster__c> clusterList = [SELECT Id, Name FROM Cluster__c WHERE Name LIKE 'ClusterRootTest%' LIMIT 1 ];
		System.debug('ClusterTriggersTest method clusterList: '+clusterList);
		String nameRecordType = 'Banner';
		// When
		Test.startTest();
		List<Content__c> contentListTest = MockupFactory.createContent(nameRecordType, clusterList[0], 1);
		Test.stopTest();


		System.debug('ClusterTriggersTest method contentListTest: '+contentListTest);

		// Then
		List<Component__Share> shareList = [SELECT Id, ParentId FROM Component__Share WHERE ParentId = :contentListTest[0].Id AND RowCause = 'Clustering__c'];
		System.debug('ClusterTriggersTest method shareList: '+shareList);

		System.assertEquals(3, shareList.size());

	}
}