src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContentAssignment__c.object
<CustomObject>
    <description>Manages the direct assignment of Content to Components</description>
    <fields>
        <fullName>Component__c</fullName>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipName>ComponentContentAssignment</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipName>ComponentContentAssignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content Assignment</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Content Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContentAssignmentTriggersTest.cls
@isTest(seeAllData = false)
public class ContentAssignmentTriggersTest {
	
	@isTest 
	static void insertContentAssignmentTest(){
		/* Comment: Comprueba que al crear un ContentAssignment__c se inserta
			con el correspondiente ExternalId__c */

		//Given
		//MockupFactory.createRecords();
		Content__c contentTest = new Content__c(Name='Test');
		insert contentTest;

		Component__c compTest = [select id, Name, ExternalId__c from Component__c limit 1];
		Content__c contTest = [select id, Name, ExternalId__c from Content__c limit 1];								

		ContentAssignment__c contentAssigmentTest = new ContentAssignment__c(Component__c = compTest.id, Content__c=contTest.id );

		//When
		Test.startTest();
			insert(contentAssigmentTest);
		Test.stopTest();

		//Then
		ContentAssignment__c contentAssigmentTestResult =[select id, ExternalId__c from ContentAssignment__c where id =: contentAssigmentTest.id];
		System.assertNotEquals(contentAssigmentTestResult.ExternalId__c, null);

	}

	@isTest
	static void updateContentAssignment(){
		/*Comment: Comprueba que al actualizar un ContentAssignment__c se actualiza
		con correspondiente ExternalId__c */

		//Given
		//MockupFactory.createRecords();
		Component__c compTest = [select id, Name, ExternalId__c from Component__c limit 1];
		Content__c contTest = [select id, Name, ExternalId__c from Content__c limit 1];	
		ContentAssignment__c contentAssigmentTest = new ContentAssignment__c(Component__c = compTest.id, Content__c=contTest.id );
		insert contentAssigmentTest;
		ContentAssigmenttest.ExternalId__c = null;


		//When
		Test.startTest();
		update(contentAssigmenttest);
		Test.stopTest();

		//Then
		ContentAssignment__c contentAssigmentTestResult =[select id, ExternalId__c from ContentAssignment__c where id =: contentAssigmentTest.id];
		System.assertNotEquals(contentAssigmentTestResult.ExternalId__c, null);

	}
}