src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Datasource__c</fullName>
        <label>Datasource</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ManualAssignment</fullName>
                    <label>Manual Assignment</label>
                </value>
                <value>
                    <fullName>Tags</fullName>
                </value>
                <value>
                    <fullName>Categories</fullName>
                </value>
                <value>
                    <fullName>TagsCategories</fullName>
                    <label>Tags + Categories</label>
                </value>
                <value>
                    <fullName>ParentComponentBehaviour</fullName>
                    <label>Parent Component Behaviour</label>
                </value>
                <value>
                    <fullName>ParentContentTags</fullName>
                    <label>Parent Content Tags</label>
                </value>
                <value>
                    <fullName>ParentContentCategories</fullName>
                    <label>Parent Content Categories</label>
                </value>
                <value>
                    <fullName>ParentContentTagsCategories</fullName>
                    <label>Parent Content Tags + Categories</label>
                </value>
                <value>
                    <fullName>All News</fullName>
                </value>
                <value>
                    <fullName>All Events</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                    <label>Initial</label>
                </value>
                <value>
                    <fullName>Set Format</fullName>
                </value>
                <value>
                    <fullName>Set Content</fullName>
                </value>
                <value>
                    <fullName>Final Check</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Set Community</fullName>
                    <isActive>false</isActive>
                    <label>Set Community</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner component. Each banner component has a given aspect ratio and orientation for its presentation. It also has a given behavior for presenting its content such as carousel or appear-disappear effect.</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ComponentUtilsTest.cls
@isTest
public class ComponentUtilsTest {
	
	@isTest static void getComponentTest_Extid(){
		/* Comment: Comprueba que dado un String correspondiente a ExternalId de un componente, un fieldSet
		representado por un Set<String>, y un device, el método getComponent de la clase ComponentUtils, retorne el
		componente representado por dado External Id. */

		//Given
		String componentExternalId1 = 'BannerComponent_0';
        MockupFactory.createComponent('Banner', 1);
        
		set<String> bannerFieldSet = new set<String>();
        bannerFieldSet.add('Name');
        bannerFieldSet.add('ExternalId__c');
        bannerFieldSet.add('Datasource__c');
        bannerFieldSet.add('Status__c');
        bannerFieldSet.add('RecordTypeId');
		
		//When
		Test.startTest();
		String test1 = ComponentUtils.getComponent(componentExternalId1, bannerFieldSet, 'Desktop').ExternalId__c;
		Test.stopTest();

		//Then
		System.assertEquals(componentExternalId1, test1);
	
	}

	@isTest static void getComponentTestwithId(){
		/* Comment: Comprueba que dado un String correspondiente a el Id de un componente, un fieldSet
		representado por un Set<String>, y un device, el método getComponent de la clase ComponentUtils, retorne el
		componente representado por dado Id. */

		//Given
        MockupFactory.createComponent('Banner', 1);
		List<Component__c> component1 = [SELECT Id from Component__c LIMIT 1];
		Id componentId1 = component1[0].Id;
		set<String> bannerFieldSet = new set<String>();
        bannerFieldSet.add('Name');
        bannerFieldSet.add('ExternalId__c');
        bannerFieldSet.add('Datasource__c');
        bannerFieldSet.add('Status__c');
        bannerFieldSet.add('RecordTypeId');
		
		
		//When
		Test.startTest();
		String test1 = ComponentUtils.getComponent(componentId1, bannerFieldSet, 'Desktop').Id;
		Test.stopTest();

		//Then
		System.assertEquals(componentId1, test1);
	}
}