src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SearchComponentPicklist.cls
global class SearchComponentPicklist extends VisualEditor.DynamicPickList{
	List<Component__c> 	compList = [SELECT Id,Name,ExternalId__c FROM Component__c WHERE RecordType.DeveloperName = 'Search'];
    
    global override VisualEditor.DataRow getDefaultValue(){
    	VisualEditor.DataRow defaultValue;
    	if(compList.isEmpty())
        	defaultValue = null;
        else
        	defaultValue = new VisualEditor.DataRow(compList.get(0).Name, compList.get(0).ExternalId__c);
        return defaultValue;
    }

    global override VisualEditor.DynamicPickListRows getValues() {
        VisualEditor.DynamicPickListRows  	myValues = new VisualEditor.DynamicPickListRows();
    	
        
    	for(Component__c c : compList){
        	myValues.addRow(new VisualEditor.DataRow(c.Name, c.ExternalId__c));
    	}

        return myValues;
    }
}