src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LinkDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Link Detail</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>Navigation</fullName>
        <active>true</active>
        <label>Navigation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>URLMask__c</fullName>
        <label>URL Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SearchDetail__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Component__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Search</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Search Details</relationshipLabel>
        <relationshipName>Search_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FieldsToSearch__c</fullName>
        <description>Fields in which will be searched the inserted text</description>
        <inlineHelpText>The fields api names separeted by comma</inlineHelpText>
        <label>Fields To Search</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FieldsToShow__c</fullName>
        <description>Fields that will be shown</description>
        <inlineHelpText>Insert the fields api names separeted by comma</inlineHelpText>
        <label>Fields To Show</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Filter__c</fullName>
        <description>SOQL additional filter</description>
        <inlineHelpText>SOQL additional filter</inlineHelpText>
        <label>Filter</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IconName__c</fullName>
        <description>Name of the Lightning Icon to show next to the name</description>
        <inlineHelpText>Insert the name of a Lightning Icon. 
Ex: &quot;utility:user&quot;</inlineHelpText>
        <label>Icon Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Navigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Navigation</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Search Details</relationshipLabel>
        <relationshipName>Search_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ObjectAPIName__c</fullName>
        <description>API name of the Sobject</description>
        <inlineHelpText>Insert the API name of the Salesforce Object</inlineHelpText>
        <label>Object API Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PredictiveSearchRecordsNumber__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of records to show in the predictive search window</description>
        <inlineHelpText>Number of records to show in the predictive search window</inlineHelpText>
        <label>Predictive Search Records Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecordTypeDevName__c</fullName>
        <inlineHelpText>Insert the record type developer name</inlineHelpText>
        <label>Record Type Dev Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URLParameterField__c</fullName>
        <defaultValue>&apos;Id&apos;</defaultValue>
        <label>URL Parameter Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URLParameterName__c</fullName>
        <defaultValue>&apos;Id&apos;</defaultValue>
        <label>URL Parameter Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Search Detail</label>
    <nameField>
        <label>Search Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SearchController.cls
public with sharing class SearchController {

    //WRAPPER
    public class SearchResultWrapper {
        @AuraEnabled public List<Sobject>                   records;
        @AuraEnabled public String                          sectionName;
        @AuraEnabled public String                          sectionApiName;
        @AuraEnabled public String                          iconName;
        @AuraEnabled public String                          objectAPIName;
        @AuraEnabled public String                          sortedBy;
        @AuraEnabled public List<Map<String,String>>        fieldsToShow;
        @AuraEnabled public String                          urlParameterName;
        @AuraEnabled public String                          urlParameterField;
        @AuraEnabled public String                          navigation;

        public SearchResultWrapper(List<Sobject> records, String sectionName, String sectionApiName, String iconName, 
                                    String objectAPIName, List<Map<String,String>> fieldsToShow, String urlParameterName, 
                                    String urlParameterField, String navigation){
            this.records            = records;
            this.sectionName        = sectionName;
            this.sectionApiName     = sectionApiName;
            this.iconName           = iconName;
            this.objectAPIName      = objectAPIName;
            this.sortedBy           = fieldsToShow.get(0).get('fieldName');
            this.fieldsToShow       = fieldsToShow;
            this.urlParameterName   = urlParameterName;
            this.urlParameterField  = urlParameterField;
            this.navigation         = navigation;
        }
    }

    public class PredictiveResultWrapper {
        @AuraEnabled public List<Sobject>                   records;
        @AuraEnabled public String                          sectionName;
        @AuraEnabled public String                          iconName;
        @AuraEnabled public String                          urlParameterName;
        @AuraEnabled public String                          urlParameterField;
        @AuraEnabled public String                          navigation;

        public PredictiveResultWrapper(List<Sobject> records, String sectionName, String iconName, String urlParameterName, 
                                    String urlParameterField, String navigation){
            this.records            = records;
            this.sectionName        = sectionName;
            this.iconName           = iconName;
            this.urlParameterName   = urlParameterName;
            this.urlParameterField  = urlParameterField;
            this.navigation         = navigation;
        }
    }

    public class SearchDetailWrapper {
        @AuraEnabled public Component__c                    component;
        @AuraEnabled public List<SearchDetail__c>           searchDetails;

        public SearchDetailWrapper(Component__c component, List<SearchDetail__c> searchDetails){
            this.component          = component;
            this.searchDetails      = searchDetails;
        }
    }

    @AuraEnabled
    public static Component__c getComponent(String externalId){
        List<Component__c> component = [SELECT Name, ExternalId__c, SearchPlaceholder__c, LinkDetail__r.URL__c, LinkDetail__r.URLMask__c, PredictiveSearchEnabled__c
                                                    FROM Component__c WHERE ExternalId__c = :externalId];
        
        return (component.isEmpty()) ? null : component.get(0);
    }

    @AuraEnabled
    public static SearchDetailWrapper getSearchDetails(String externalId){
        List<Component__c> component = [SELECT Name, ExternalId__c, SearchPlaceholder__c, LinkDetail__r.URL__c, LinkDetail__r.URLMask__c, PredictiveSearchEnabled__c
                                                    FROM Component__c WHERE ExternalId__c = :externalId];

        List<SearchDetail__c> searchDetails = [SELECT Name, ExternalId__c, URLParameterName__c, URLParameterField__c, FieldsToSearch__c, FieldsToShow__c, IconName__c, ObjectAPIName__c, RecordTypeDevName__c, Filter__c, Navigation__r.URL__c, Navigation__r.URLMask__c, PredictiveSearchRecordsNumber__c 
                                                    FROM SearchDetail__c WHERE Active__c = true AND Component__r.ExternalId__c = :externalId];

        return new SearchDetailWrapper(((component.isEmpty()) ? null : component.get(0)), searchDetails);
    }

    @AuraEnabled
    public static List<SearchResultWrapper> getSearchResults(String searchedString, List<SearchDetail__c> searchDetails){
        List<SearchResultWrapper>   searchResults = new List<SearchResultWrapper>();

        for(SearchDetail__c rll : searchDetails){
            searchResults.add( new SearchResultWrapper( Database.query(buildQuery(rll, searchedString)),
                                                        rll.Name,
                                                        rll.ExternalId__c,
                                                        rll.IconName__c,
                                                        rll.ObjectAPIName__c,
                                                        getLabelsByFields(rll.FieldsToShow__c.split(','), rll.ObjectAPIName__c),
                                                        rll.URLParameterName__c,
                                                        rll.URLParameterField__c,
                                                        rll.Navigation__r.URL__c
                                                        ));
        }

        System.debug('[SearchController][getSearchResults] searchResults: ' + JSON.serialize(searchResults));
        return searchResults;
    }

    @AuraEnabled
    public static List<PredictiveResultWrapper> getPredictiveResults(String searchedString, List<SearchDetail__c> searchDetails){
        List<PredictiveResultWrapper>   predictiveResults = new List<PredictiveResultWrapper>();

        for(SearchDetail__c rll : searchDetails){
            predictiveResults.add( new PredictiveResultWrapper( Database.query(buildPredictiveQuery(rll, searchedString)),
                                                        rll.Name,
                                                        rll.IconName__c,
                                                        rll.URLParameterName__c,
                                                        rll.URLParameterField__c,
                                                        rll.Navigation__r.URL__c
                                                        ));
        }

        System.debug('[SearchController][getSearchResults] predictiveResults: ' + JSON.serialize(predictiveResults));
        return predictiveResults;
    }

    private static String buildQuery(SearchDetail__c rll, String searchedString){
        List<String>    fields  = rll.FieldsToSearch__c.split(',');
        String          query   = 'SELECT ' + rll.FieldsToShow__c + ((rll.FieldsToShow__c.split(',').contains(rll.URLParameterField__c)) ? '' : ',' + rll.URLParameterField__c) +
                                    ' FROM ' + rll.ObjectAPIName__c +
                                    ' WHERE ' + ((!String.isBlank(rll.RecordTypeDevName__c)) ? 
                                                    'RecordType.DeveloperName = \'' + rll.RecordTypeDevName__c + '\' AND (' : '');

        for(Integer i = 0; i < fields.size(); i++){
            String field = fields.get(i);
            query += (i == fields.size() - 1) ? 
                        field + ' LIKE \'%' + searchedString + '%\')' : field + ' LIKE \'%' + searchedString + '%\' OR ';
        }

        query += (!String.isBlank(rll.Filter__c)) ? rll.Filter__c : '';

        return query;
    }

    private static String buildPredictiveQuery(SearchDetail__c rll, String searchedString){
        List<String>    fields  = rll.FieldsToSearch__c.split(',');
        String          query   = 'SELECT Name,' + rll.URLParameterField__c +
                                    ' FROM ' + rll.ObjectAPIName__c +
                                    ' WHERE ' + ((!String.isBlank(rll.RecordTypeDevName__c)) ? 
                                                    'RecordType.DeveloperName = \'' + rll.RecordTypeDevName__c + '\' AND (' : '');

        for(Integer i = 0; i < fields.size(); i++){
            String field = fields.get(i);
            query += (i == fields.size() - 1) ? 
                        field + ' LIKE \'%' + searchedString + '%\')' : field + ' LIKE \'%' + searchedString + '%\' OR ';
        }

        query += (!String.isBlank(rll.Filter__c)) ? rll.Filter__c : '';
        query += ' LIMIT ' + rll.PredictiveSearchRecordsNumber__c;

        return query;
    }

    private static List<Map<String,String>> getLabelsByFields(List<String> fields, String sobjectName){
        List<Map<String,String>>            fieldsMaps  = new List<Map<String,String>>();
        Map<String, Schema.SObjectType>     schemaMap   = Schema.getGlobalDescribe();
        Schema.SObjectType                  leadSchema  = schemaMap.get(sobjectName);
        Map<String, Schema.SObjectField> fieldMap = leadSchema.getDescribe().fields.getMap();

        for(String fApiName : fields){
            Map<String,String> fieldMetaData = new Map<String,String>();
            fieldMetaData.put('label', fieldMap.get(fApiName).getDescribe().getLabel());
            fieldMetaData.put('fieldName',fApiName);
            fieldMetaData.put('type', (fieldMap.get(fApiName).getDescribe().getType() + '').toLowerCase());
            fieldMetaData.put('sortable', 'true');

            fieldsMaps.add(fieldMetaData);
        }

        return fieldsMaps;
    }
}