src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner component. Each banner component has a given aspect ratio and orientation for its presentation. It also has a given behavior for presenting its content such as carousel or appear-disappear effect.</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner content. This content will scroll or appear-fade inside a Banner. The data this type of content allows are Media elements</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContentAssignment__c.object
<CustomObject>
    <description>Manages the direct assignment of Content to Components</description>
    <fields>
        <fullName>Component__c</fullName>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipName>ComponentContentAssignment</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipName>ComponentContentAssignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content Assignment</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Content Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/JunctionObjectManagerControllerTest.cls
@isTest 
public with sharing class JunctionObjectManagerControllerTest {

	@isTest 
	static void TEST_CASE_1() {
		// Comment: Desde un componente Banner busco todos los registros de contenido, sin condiciones

		// Given
		//MockupFactory.createRecords();
		Component__c comp = [SELECT id FROM Component__c LIMIT 1];
		
		// When 
		Test.startTest();
		JunctionObjectManagerController.RecordsWrapper rw = JunctionObjectManagerController.getRecords(comp.id, 'ContentAssignment__c',  'Component__c', 'Content__c', null);
		Test.stopTest();

		// Then
		System.assertEquals(1, [SELECT Id FROM Content__c WHERE Id = :rw.recordsSelected[0].Id].size());
	}

	@isTest 
	static void TEST_CASE_2() {// TODO 
		// Comment: Desde un componente Banner busco todos los registros de contenido, con condiciones

		// Given
		//MockupFactory.createRecords();
		Component__c comp = [SELECT id, ExternalId__c FROM Component__c LIMIT 1];
		system.debug('Nahue :'+ comp.ExternalId__c);
		// When 
		Test.startTest();
		JunctionObjectManagerController.RecordsWrapper rw = JunctionObjectManagerController.getRecords(comp.id, 'ContentAssignment__c',  'Component__c', 'Content__c', 'WHERE ExternalId__c = \''+ comp.ExternalId__c + '\'');
		Test.stopTest();
   
		// Then 
		Content__c var = [SELECT Id, ExternalId__c FROM Content__c WHERE Id = :rw.recordsSelected[0].Id];

		System.assertnotEquals(var, null);
	}

	@isTest 
	static void TEST_CASE_3() {
		// Comment: Desde un componente Banner le relaciono dos registros de contenido.

		// Given
		//MockupFactory.createRecords();
		Component__c comp = [SELECT id FROM Component__c LIMIT 1];
		List<String> listSelectedIds = new List<String>(); 
		listSelectedIds.add([SELECT Id FROM Content__c LIMIT 1][0].Id);
		listSelectedIds.add([SELECT Id FROM Content__c LIMIT 1][0].Id);
		listSelectedIds.add(comp.id);
		
		// When 
		Test.startTest();
		String response = JunctionObjectManagerController.saveRelationships(comp.id, 'ContentAssignment__c', 'Component__c', 'Content__c', listSelectedIds);
		Test.stopTest();

		// Then
		System.assertEquals('OK', response);
	}

}