src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CG_DynamicPicklistEventsDetail.cls
global class CG_DynamicPicklistEventsDetail extends VisualEditor.DynamicPickList{
	// Default value -- The one that appears at the top
	global override VisualEditor.DataRow getDefaultValue(){
		VisualEditor.DataRow defaultValue = new VisualEditor.DataRow('--None--','');
		return defaultValue;
	}

	// getValues -- define values inside picklist / ('[Title]','[Value]')
	global override VisualEditor.DynamicPickListRows getValues(){
		VisualEditor.DynamicPicklistRows picklistValues = new VisualEditor.DynamicPicklistRows();
		VisualEditor.DataRow nullValue = new VisualEditor.DataRow('--None--','');
		picklistValues.addRow(nullValue); 

		List<Component__c> idsToDisplay = [SELECT Name, ExternalId__c, RecordType.Name FROM Component__c WHERE RecordType.Name = 'Events Detail'];
		for(Component__c cIds : idsToDisplay){
			picklistValues.addRow(new VisualEditor.DataRow(cIds.Name,cIds.ExternalId__c));
		}
		return picklistValues;
	}
}
// Note: The 2 methods present are REQUIRED