src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CommunityComponentPreviewControllerTest.cls
@isTest
public class CommunityComponentPreviewControllerTest {
	@isTest static void getRecordTest(){
		/* Comment: Comprueba que dado un String correspondiente a un recordId de un componente, el método getRecord de la clase CommunityComponentPreview, retorne el
		componente representado por dado record Id. */

		//Given
		//MockupFactory.createRecords();
		Component__c testRecord = [SELECT Id, Name, ExternalId__c, RecordTypeId FROM Component__c LIMIT 1]; 
		System.debug('testRecord: ' + testRecord);
		
		//When
		Test.startTest();
			Component__c testComponent = CommunityComponentPreviewController.getRecord(String.valueOf(testRecord.Id));
		Test.stopTest();

		//Then
		System.assertEquals(testRecord.Id, testComponent.Id);
	}

}