src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MediaElement__c.object
<CustomObject>
    <description>Represents the repository of media elements that can be assigned to multiple contents.</description>
    <fields>
        <fullName>FileURLDesktop__c</fullName>
        <description>Stores the URL of the desktop file related to the media element.</description>
        <inlineHelpText>Stores the URL of the desktop file related to the media element.</inlineHelpText>
        <label>File URL Desktop</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Media Element</label>
    <nameField>
        <label>Media Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media elements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MediaElementAssignment__c.object
<CustomObject>
    <description>Holds the relationship between each media element and the Contents it is beeing used on. This relationship can also be categorized</description>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>MediaElementAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MediaElement__c</fullName>
        <label>Media Element</label>
        <referenceTo>MediaElement__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Media Element Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Media Element Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Element Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CG_ContentToolsController.cls
public with sharing class CG_ContentToolsController {
    public class ContentWrapper{    
        @auraEnabled public String contentId;
        @auraEnabled public String urlPreview;
        @auraEnabled public String urlDownload;
        
        public ContentWrapper(){
        }
    }

    @auraEnabled
    public static ContentWrapper initData(String contentId){
        ContentWrapper contentWr = new ContentWrapper();
        String contentDocId;

        List<MediaElementAssignment__c> contentAssignmentList = [SELECT Content__c, MediaElement__r.FileURLDesktop__c FROM MediaElementAssignment__c WHERE Content__c =: contentId AND isDeleted = false];
        if(contentAssignmentList.size() > 0){
        	List<String> stringSplit = contentAssignmentList[0].MediaElement__r.FileURLDesktop__c.split('/');
            String str = stringSplit[stringSplit.size() - 1];
            if (Pattern.compile( '[a-zA-Z0-9]{15}|[a-zA-Z0-9]{18}' ).matcher(str).matches()){
            	contentDocId = str;
            }
        
	        if(!String.isBlank(contentDocId)){
	        	ContentDocument file = [SELECT id, Title FROM ContentDocument WHERE id =: contentDocId];
		        List<ContentDistribution> listContentDist = [SELECT id, DistributionPublicUrl, ContentDownloadUrl FROM ContentDistribution WHERE ContentDocumentId =: contentDocId];
		        
		        ContentDistribution contentDist;
		        if (listContentDist.size() > 0){
		        	contentDist = listContentDist[0];
		        } else {
		        	ContentVersion contentVers = [SELECT id FROM ContentVersion WHERE contentdocumentid =: contentDocId ORDER BY createdDate Desc LIMIT 1];
		        
		            contentDist = new ContentDistribution();
		            contentDist.Name = file.Title;
		            contentDist.ContentVersionId = contentVers.Id;
		            contentDist.PreferencesAllowOriginalDownload = true;
		            contentDist.PreferencesAllowPDFDownload = false;
		            contentDist.PreferencesAllowViewInBrowser = true;
		            contentDist.PreferencesExpires = false;
		            contentDist.PreferencesLinkLatestVersion = true;
		            insert contentDist;
		        }
		        contentDist = [SELECT id, DistributionPublicUrl, ContentDownloadUrl FROM ContentDistribution WHERE ContentDocumentId =: contentDocId];
		        contentWr.urlPreview = contentDist.DistributionPublicUrl.trim();
		        contentWr.urlDownload = contentDist.ContentDownloadUrl.trim();
	        } else {
	        	contentWr.urlPreview = contentAssignmentList[0].MediaElement__r.FileURLDesktop__c.trim();
		        contentWr.urlDownload = contentAssignmentList[0].MediaElement__r.FileURLDesktop__c.trim();
	        }
	        
	    }

        contentWr.contentId = contentId;
        return contentWr;
    }
    
    @auraEnabled
    public static ContentWrapper addToCarts(String data){
        
        ContentWrapper contentWr = (ContentWrapper)JSON.deserialize(data, ContentWrapper.class);
        Boolean isInserted = CG_ContentCartController.addContentToCart(contentWr.contentId);
        if (!isInserted){
        	throw new AuraHandledException(System.Label.DuplicateItem);
        }
        
        return contentWr;
    }

}