src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MediaElement__c.object
<CustomObject>
    <description>Represents the repository of media elements that can be assigned to multiple contents.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Media Element</label>
    <nameField>
        <label>Media Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media elements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MediaElementAssignment__c.object
<CustomObject>
    <description>Holds the relationship between each media element and the Contents it is beeing used on. This relationship can also be categorized</description>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>MediaElementAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MediaElement__c</fullName>
        <label>Media Element</label>
        <referenceTo>MediaElement__c</referenceTo>
        <relationshipLabel>Media Element Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Media Element Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Media Element Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Element Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MediaElementAssignmentTriggersTest.cls
@isTest(seeAllData = false)
public class MediaElementAssignmentTriggersTest {
	
	@isTest 
	static void insertMediaElementAssignmentTest(){
		/* Comment: Comprueba que al crear un MediaElementAssignment__c se inserta
			con el correspondiente ExternalId__c */

		//Given
		//MockupFactory.createRecords();
		MediaElement__c mediaElementTest = new MediaElement__c(Name='Test');
		insert mediaElementTest;

		Content__c contTest = [select id, Name, ExternalId__c from Content__c limit 1];								

		MediaElementAssignment__c MediaElementAssigmentTest = new MediaElementAssignment__c(Content__c=contTest.id );

		//When
		Test.startTest();
			insert(mediaElementAssigmentTest);
		Test.stopTest();

		//Then
		MediaElementAssignment__c mediaElementAssigmentTestResult =[select id, ExternalId__c from MediaElementAssignment__c where id =: mediaElementAssigmentTest.id];
		System.assertNotEquals(mediaElementAssigmentTestResult.ExternalId__c, null);

	}

	@isTest
	static void updateMediaElementAssignment(){
		/*Comment: Comprueba que al actualizar un MediaElementAssignment__c se actualiza
		con correspondiente ExternalId__c */

		//Given
		//MockupFactory.createRecords();
		Content__c contTest = [select id, Name, ExternalId__c from Content__c limit 1];	
		MediaElementAssignment__c mediaElementAssigmentTest = new MediaElementAssignment__c(Content__c=contTest.id );
		insert mediaElementAssigmentTest;
		mediaElementAssigmenttest.ExternalId__c = null;


		//When
		Test.startTest();
		update(mediaElementAssigmenttest);
		Test.stopTest();

		//Then
		MediaElementAssignment__c mediaElementAssigmentTestResult =[select id, ExternalId__c from MediaElementAssignment__c where id =: MediaElementAssigmentTest.id];
		System.assertNotEquals(mediaElementAssigmentTestResult.ExternalId__c, null);

	}
}