src/objects/ContentAssignment__c.object
<CustomObject>
    <description>Manages the direct assignment of Content to Components</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content Assignment</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Content Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContentAssignmentTriggers.cls
public with sharing class ContentAssignmentTriggers extends TriggersHandler {

    /*****************************************************************/
    /************************ CONSTRUCTOR ****************************/
    /*****************************************************************/
    public ContentAssignmentTriggers(List<SObject> p_triggerNew, List<SObject> p_triggerOld){
        super(p_triggerNew, p_triggerOld);

		allow_masterLoop_AfterInsert = true;
		allow_masterLoop_AfterUpdate = true;
    }
    
    /*****************************************************************/
    /*********************** TRIGGER METHODS *************************/
    /*****************************************************************/
    
    //Master loops
    public override void masterLoop_AfterInsert(SObject recNew) {
    	setExternalId((ContentAssignment__c)recNew);
    }
    public override void masterLoop_AfterUpdate(SObject recNew, SObject recOld) {
    	setExternalId((ContentAssignment__c)recNew);
    }
    
    /*****************************************************************/
    /********************** USE CASE METHODS *************************/
    /*****************************************************************/
	private void setExternalId(ContentAssignment__c recNew){
        if(!canMethod('setExternalId')){return;}
        
		if (recNew.ExternalID__c == null){
        	recordSelfUpdate(recNew.id, 'ExternalID__c', recNew.Name);
    	}
	}
}