src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CG_CommunityComponentFrameController.cls
public with sharing class CG_CommunityComponentFrameController {



    //WRAPPERS
    public class ContentRecordTypeWrapper{
		@auraEnabled public Boolean haveContentRecordType;
		@auraEnabled public String contentRecordTypeId;
		public ContentRecordTypeWrapper(){
			this.haveContentRecordType = false;
            this.contentRecordTypeId = '';
		}
	}


	@auraEnabled
	public static ContentRecordTypeWrapper getContentRecordtypeId(String componentRecordType) {
		// List of fields
		ContentRecordTypeWrapper contentRecordTypeWP =  new ContentRecordTypeWrapper();

		String contentRecordType = ContentUtils.getRecordTypeContentFromRTComponent(componentRecordType);

		RecordType recordType = [select Id, Name from RecordType where sObjectType = 'Content__c' and Name = :contentRecordType LIMIT 1]; 
		
		if(recordType != null){
			contentRecordTypeWP.contentRecordTypeId = String.valueOf(recordType.Id);
			contentRecordTypeWP.haveContentRecordType = true;
			return contentRecordTypeWP;
		}else{
			return contentRecordTypeWP;
		}
	}



	@auraEnabled
	public static String getNavigationId(String navigationUrl) {
		String url = navigationUrl.split('/')[navigationUrl.split('/').size()-1];
		Navigation__c nav = [SELECT Id From Navigation__c WHERE Url__c =: url]; 
		if (nav != null){
			return nav.Id;
		}
		else{
			return '';
		}
	}

}