src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner content. This content will scroll or appear-fade inside a Banner. The data this type of content allows are Media elements</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RecordListLayout__c.object
<CustomObject>
    <fields>
        <fullName>FieldsToSearch__c</fullName>
        <description>Fields in which will be searched the inserted text</description>
        <inlineHelpText>The fields api names separeted by comma</inlineHelpText>
        <label>Fields To Search</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FieldsToShow__c</fullName>
        <description>Fields that will be shown</description>
        <inlineHelpText>Insert the fields api names separeted by comma</inlineHelpText>
        <label>Fields To Show</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ObjectAPIName__c</fullName>
        <description>API name of the Sobject</description>
        <inlineHelpText>Insert the API name of the Salesforce Object</inlineHelpText>
        <label>Object API Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordTypeDevName__c</fullName>
        <inlineHelpText>Insert the record type developer name</inlineHelpText>
        <label>Record Type Dev Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Record List Layout</label>
    <nameField>
        <label>Record List Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Record List Layouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RecordListLayoutTriggerTest.cls
@isTest
public with sharing class RecordListLayoutTriggerTest {
	
    @testSetup
    static void setup(){
		RecordListLayout__c rll = createListLayout('Banner','banner','Content__c','Name','Name,Description__c','Banner');
		update rll;
    }

    @isTest
    static void updateListLayout(){
    	RecordListLayout__c rll = [SELECT Id,Name,ExternalId__c,ObjectAPIName__c,FieldsToSearch__c,FieldsToShow__c,RecordTypeDevName__c 
    								FROM RecordListLayout__c
    								LIMIT 1];
    	rll.FieldsToShow__c = 'Name';
    	update rll;
    }

    @isTest
    static void updateWrongSobject(){
    	RecordListLayout__c rll = [SELECT Id,Name,ExternalId__c,ObjectAPIName__c,FieldsToSearch__c,FieldsToShow__c,RecordTypeDevName__c 
    								FROM RecordListLayout__c
    								LIMIT 1];
    	rll.ObjectAPIName__c = 'NoExistingSobject';
    	try{
    		update rll;
    	} catch(Exception e){
    		Boolean expectedExceptionThrown =  (e.getMessage().contains(Label.GlobalSearchWrongSobject)) ? true : false;
			System.AssertEquals(expectedExceptionThrown, true);
    	}
    }

    @isTest
    static void updateWrongField(){
    	RecordListLayout__c rll = [SELECT Id,Name,ExternalId__c,ObjectAPIName__c,FieldsToSearch__c,FieldsToShow__c,RecordTypeDevName__c 
    								FROM RecordListLayout__c
    								LIMIT 1];

    	rll.FieldsToSearch__c = 'NoExistingField';
    	rll.FieldsToShow__c = 'Name';
    	try{
    		update rll;
    	} catch(Exception e){
    		Boolean expectedExceptionThrown =  (e.getMessage().contains(String.format(Label.GlobalSearchWrongField, new List<String> {'NoExistingField', rll.ObjectAPIName__c}))) ? true : false;
			System.AssertEquals(expectedExceptionThrown, true);
    	}

    	rll.FieldsToSearch__c = 'Name';
    	rll.FieldsToShow__c = 'NoExistingField';
    	try{
    		update rll;
    	} catch(Exception e){
    		Boolean expectedExceptionThrown =  (e.getMessage().contains(String.format(Label.GlobalSearchWrongField, new List<String> {'NoExistingField', rll.ObjectAPIName__c}))) ? true : false;
			System.AssertEquals(expectedExceptionThrown, true);
    	}

    	rll.FieldsToSearch__c = 'Name,Description__c';
    	rll.FieldsToShow__c = 'Name';
    	try{
    		update rll;
    	} catch(Exception e){
    		Boolean expectedExceptionThrown =  (e.getMessage().contains(String.format(Label.GlobalSearchFieldNotFilterable, new List<String> {'Description__c', rll.ObjectAPIName__c}))) ? true : false;
			System.AssertEquals(expectedExceptionThrown, true);
    	}


    }

    @isTest
    static void updateWrongRT(){
    	RecordListLayout__c rll = [SELECT Id,Name,ExternalId__c,ObjectAPIName__c,FieldsToSearch__c,FieldsToShow__c,RecordTypeDevName__c 
    								FROM RecordListLayout__c
    								LIMIT 1];

    	rll.RecordTypeDevName__c = 'NoExistingRT';
    	try{
    		update rll;
    	} catch(Exception e){
    		Boolean expectedExceptionThrown =  (e.getMessage().contains(String.format(Label.GlobalSearchWrongRT, new List<String> {'NoExistingRT', rll.ObjectAPIName__c}))) ? true : false;
			System.AssertEquals(expectedExceptionThrown, true);
    	}
    }


    static RecordListLayout__c createListLayout(String name, String sectionApiName, String objectApiName, String fieldsToSearch, String fieldsToShow, String recordTypeDevName){
    	RecordListLayout__c rll = new RecordListLayout__c(
												    		Name 					= name,
												    		ExternalId__c 			= sectionApiName,
												    		ObjectAPIName__c 		= objectApiName,
												    		FieldsToSearch__c 		= fieldsToSearch,
												    		FieldsToShow__c			= fieldsToShow,
												    		RecordTypeDevName__c	= recordTypeDevName
    	);
    	insert rll;
    	return rll;
    }
}