src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HTMLContent__c</fullName>
        <inlineHelpText>If html content wants to be uploaded use this field instead of the Long Description one.</inlineHelpText>
        <label>HTML Content</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ContentTriggers.cls
public with sharing class ContentTriggers extends TriggersHandler {

    /*****************************************************************/
    /************************ CONSTRUCTOR ****************************/
    /*****************************************************************/
    public ContentTriggers(List<SObject> p_triggerNew, List<SObject> p_triggerOld){
        super(p_triggerNew, p_triggerOld);

		allow_masterLoop_BeforeInsert = true;
		allow_masterLoop_BeforeUpdate = true;
    }
    
    /*****************************************************************/
    /*********************** TRIGGER METHODS *************************/
    /*****************************************************************/
    
    //Master loops
    public override void masterLoop_BeforeInsert(SObject recNew) {
    	setExternalId((Content__c)recNew);
        checkAdvanceContentBinding((Content__c)recNew);
    }
    public override void masterLoop_BeforeUpdate(SObject recNew, SObject recOld) {
    	setExternalId((Content__c)recNew);
        checkAdvanceContentBinding((Content__c)recNew);
    }
    
    /*****************************************************************/
    /********************** USE CASE METHODS *************************/
    /*****************************************************************/
	private void setExternalId(Content__c recNew){
        if(!canMethod('setExternalId')){return;}

        if(recNew.ExternalID__c == null){
            recNew.ExternalID__c = GeneralUtils.generateExternalId(recNew.Name);
        }
    }

    private void checkAdvanceContentBinding(Content__c recNew){
        if(!canMethod('checkAdvanceContentBinding')){return;}

        if(recNew.HTMLContent__c != null && recNew.HTMLContent__c.substringBetween('[!', ']') != null){

            //Replace binding by lower case
            List<String> bindingsList = new List<String>();
            String auxTextToReplace = recNew.HTMLContent__c;
            while(auxTextToReplace.substringBetween('[!', ']') != null) {
                String bind = auxTextToReplace.substringBetween('[!', ']');
                bindingsList.add('[!' + bind + ']');
                auxTextToReplace = auxTextToReplace.replace('[!' + bind + ']', '');
            }
            for(String binding: bindingsList){
                recNew.HTMLContent__c = recNew.HTMLContent__c.replace(binding, binding.toLowerCase());
            }

            //Check consistency
            if(Limits.getQueries() < 50){
                String replacedValue = GeneralUtils.replaceDynamicFields(recNew.HTMLContent__c, 'User', UserInfo.getUserId(), false);
                if(replacedValue.substringBetween('[!', ']') != null){
                    String fieldApiName = replacedValue.substringBetween('[!', ']');
                    recNew.HTMLContent__c.addError('Dynamic user fields error. Some relationship or field doesn\'t exists: ' + bindingsList);
                }
            }
        }
    }

}