src/objects/Datatable__c.object
<CustomObject>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Datatable</label>
    <nameField>
        <label>Datatable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datatables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FE_DynamicPicklistDatatable.cls
public with sharing class FE_DynamicPicklistDatatable extends VisualEditor.DynamicPickList{
	// Default value -- The one that appears at the top
	global override VisualEditor.DataRow getDefaultValue(){
		VisualEditor.DataRow defaultValue = new VisualEditor.DataRow('--None--','');
		return defaultValue;
	}

	// getValues -- define values inside picklist / ('[Title]','[Value]')
	global override VisualEditor.DynamicPickListRows getValues(){
		VisualEditor.DynamicPicklistRows picklistValues = new VisualEditor.DynamicPicklistRows();
		VisualEditor.DataRow nullValue = new VisualEditor.DataRow('--None--','');
		picklistValues.addRow(nullValue); 

		List<Datatable__c> idsToDisplay = [SELECT Name, ExternalId__c FROM Datatable__c];
		for(Datatable__c cIds : idsToDisplay){
			picklistValues.addRow(new VisualEditor.DataRow(cIds.Name,cIds.ExternalId__c));
		}
		return picklistValues;
	}
}
// Note: The 2 methods present are REQUIRED