src/objects/Navigation__c.object
<CustomObject>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CG_CommunityComponentFrameControllerTest.cls
@isTest
private class CG_CommunityComponentFrameControllerTest
{
	@isTest
	static void getContentRecordtypeId()
	{
		// Given Exist a sObject with recordType RelatedNews


		// When
		test.startTest();
		CG_CommunityComponentFrameController.ContentRecordTypeWrapper crtw = CG_CommunityComponentFrameController.getContentRecordtypeId('RelatedNews');
		test.stopTest();


		// Then
		System.assert(crtw.haveContentRecordType);

	}

	@isTest
	static void getNavigationId()
	{
		// Given 
		//Navigation Record
        Navigation__c nav = new Navigation__c(Name = 'NavTest', URL__c = 'testNav');
        insert nav;


		// When
		test.startTest();
		String navId = CG_CommunityComponentFrameController.getNavigationId('/s/testNav');
		test.stopTest();


		// Then
		System.assertNotEquals(navId, null);

	}


}