src/objects/Translation__c.object
<CustomObject>
    <description>Translates Content or Media elements into a given language</description>
    <fields>
        <fullName>FieldApiName__c</fullName>
        <label>Field Api Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldType__c</fullName>
        <label>Field Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>TextArea</fullName>
                </value>
                <value>
                    <fullName>TextAreaRich</fullName>
                    <label>Text Area Rich</label>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LanguageCode__c</fullName>
        <label>Language Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AvailableLanguages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TranslationEmail__c</fullName>
        <label>Translation Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>TranslationTextAreaRich__c</fullName>
        <label>Translation Text Area (Rich)</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>TranslationTextArea__c</fullName>
        <label>Translation Text Area</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TranslationText__c</fullName>
        <label>Translation Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TranslationURL__c</fullName>
        <label>Translation URL</label>
        <type>Url</type>
    </fields>
    <label>Translation</label>
    <nameField>
        <label>Translation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Translations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TranslationUtils.cls
global with sharing class TranslationUtils{
    
    global static map<String, String> getTranslated(SObject record, String lang, String parentLookup){
        return getTranslated(new List<SObject>{record}, lang, parentLookup);
    }
    
    global static map<String, String> getTranslated(List<SObject> records, String lang, String parentLookup){
        map<Id, SObject> mapIdRecord = new map<Id, SObject>(records);
        map<String, String> retMap = new map<String, String>();
        set<Id> setIdRecords = mapIdRecord.keySet();
        
        for(Translation__c tra: Database.query('SELECT Id, Name, ' + parentLookup + ', FieldType__c, LanguageCode__c, FieldApiName__c, TranslationText__c, TranslationTextArea__c, TranslationEmail__c, TranslationURL__c, TranslationTextAreaRich__c FROM Translation__c WHERE ' + parentLookup + ' IN: setIdRecords AND LanguageCode__c =: lang ORDER BY FieldApiName__c')){
            SObject obj = mapIdRecord.get(String.ValueOf(tra.get(parentLookup)));

            try{
                if(tra.FieldType__c == 'Text' && obj.get(tra.FieldApiName__c) != null){
                    obj.put(tra.FieldApiName__c, tra.TranslationText__c);
                    retMap.put((retMap.containsKey(tra.FieldApiName__c) ? tra.FieldApiName__c + '-' + tra.Id : tra.FieldApiName__c), tra.TranslationText__c);
                }
                if(tra.FieldType__c == 'TextArea' && obj.get(tra.FieldApiName__c) != null){ 
                    System.debug('Text Area ' + obj.get(tra.FieldApiName__c));
                    obj.put(tra.FieldApiName__c, tra.TranslationTextArea__c);
                    retMap.put((retMap.containsKey(tra.FieldApiName__c) ? tra.FieldApiName__c + '-' + tra.Id : tra.FieldApiName__c), tra.TranslationTextArea__c);
                }
                if(tra.FieldType__c == 'Email' && obj.get(tra.FieldApiName__c) != null){
                    obj.put(tra.FieldApiName__c, tra.TranslationEmail__c);
                    retMap.put((retMap.containsKey(tra.FieldApiName__c) ? tra.FieldApiName__c + '-' + tra.Id : tra.FieldApiName__c), tra.TranslationEmail__c);
                }
                if(tra.FieldType__c == 'URL' && obj.get(tra.FieldApiName__c) != null){
                    System.debug('URL' + obj.get(String.ValueOf(tra.FieldApiName__c)));
                    obj.put(tra.FieldApiName__c, tra.TranslationURL__c);
                    retMap.put((retMap.containsKey(tra.FieldApiName__c) ? tra.FieldApiName__c + '-' + tra.Id : tra.FieldApiName__c), tra.TranslationURL__c);
                }
                if(tra.FieldType__c == 'TextAreaRich' && obj.get(tra.FieldApiName__c) != null){
                    obj.put(tra.FieldApiName__c, tra.TranslationTextAreaRich__c);
                    retMap.put((retMap.containsKey(tra.FieldApiName__c) ? tra.FieldApiName__c + '-' + tra.Id : tra.FieldApiName__c), tra.TranslationTextAreaRich__c);
                }
            }catch(Exception e){
                retMap.put(tra.FieldApiName__c + '-' + tra.Id, 'ERROR: ' + e.getMessage());
            }
        }
        return retMap;
    }
    
}